Various Fixes and enhancements
XengShi/materialYouNewTab pull request #107
Opened 2024-10-23 12:42 UTC by prem12321kumar

- added padding in feelsLike
- Czech date formatting
- Changed margin of weather condition icon to position it for better appearing
- pressing the "Enter" key on the keyboard in any input field(location, api, proxy) performs the same action as clicking the corresponding button.
say we entered a location, to save it we click on "enter" button, now we can save by pressing enter key from Keyboard too.
-userText placeholder text removal when the user starts editing and restore placeholder if the user leaves it empty after clicking, --> now works for all languages
- fixed: When refreshed or new tab is opened, "Double Tap to Edit" shows briefly before loading
- changed 'enter' to 'save' and 'search'
- translated 'save' and 'search' in all lang
- reordered language.js and script.js in index.html
- added translation function for greeting with fallback to english
- Translated greeting in all languages

2024-10-23 12:53 UTC, prem12321kumar commented
@XengShi 😅

2024-10-23 16:05 UTC, ZiClaud approved these changes

2024-10-23 18:28 UTC, prem12321kumar commented
@ceskyDJ

2024-10-23 18:35 UTC, ceskyDJ commented
Czech has more day phases ("ráno", "dopoledne", "poledne", "odpoledne", "večer", "noc"), but I think this could be sufficient.

2024-10-24 10:28 UTC, prem12321kumar commented
@ceskyDJ 'Zavřiť' for close in menuCloseText
correct?

2024-10-24 10:30 UTC, ceskyDJ commented
Almost, the correct one is "Zavřít“ (diacritical "i").

2024-10-24 10:37 UTC, prem12321kumar commented
> Almost, the correct one is "Zavřít“ (diacritical "i" and normal "t").

corrected, thanks

2024-10-24 12:37 UTC, ceskyDJ approved these changes

2024-10-24 12:38 UTC, ceskyDJ commented
> corrected, thanks

You're welcome.

2024-10-24 12:40 UTC, ceskyDJ commented on languages.js
> +        "enterBtn": "Hledat",
```suggestion
        "enterBtn": "Vyhledat",
```

2024-10-24 12:41 UTC, ceskyDJ commented on languages.js
> +        "enterBtn": "Hledat",
It's better than "Hledat" in this context.

2024-10-24 13:56 UTC, prem12321kumar commented
@itz-rj-here Translated Bengali Numerals

2024-10-24 14:09 UTC, prem12321kumar commented
I think all major elements' text are now translated

beside obvious ones, digital clock (and alerts from proxy and reset setting) left

2024-10-24 19:43 UTC, ceskyDJ commented on languages.js
> +        "timeformatinfo": "Použije 12hodinový formát času",
```suggestion
        "timeformatinfo": "Použije se 12hodinový formát času",
```

2024-10-24 19:43 UTC, ceskyDJ commented on languages.js
> +        "enableShortcutsText": "Povolí/zakáže zkratky",
```suggestion
        "enableShortcutsText": "Zapne/vypne zkratky",
```

2024-10-24 19:44 UTC, ceskyDJ commented on languages.js
> +        "enable_ai_tools": "Povolí/zakáže zkratky AI nástrojů",
```suggestion
        "enable_ai_tools": "Zapne/vypne zkratky AI nástrojů",
```

2024-10-24 19:56 UTC, ceskyDJ commented on languages.js
> +        "enable_ai_tools": "Povolí/zakáže zkratky AI nástrojů",
Maybe "Show" is better for this?

2024-10-24 19:56 UTC, ceskyDJ commented on languages.js
> +        "enableShortcutsText": "Povolí/zakáže zkratky",
Maybe "Show" is better for this?

2024-10-24 19:56 UTC, ceskyDJ commented on languages.js
> +        "digitalclockinfo": "Povolí/zakáže digitální hodiny",
```suggestion
        "digitalclockinfo": "Zapne/vypne digitální hodiny",
```

2024-10-24 19:56 UTC, ceskyDJ commented on languages.js
> +        "enableShortcutsText": "Povolí/zakáže zkratky",
This translation is for the current state; the last message is just a proposal for change.

2024-10-24 19:56 UTC, ceskyDJ commented on languages.js
> +        "enable_ai_tools": "Povolí/zakáže zkratky AI nástrojů",
This translation is for the current state; the last message is just a proposal for change.

2024-10-24 19:56 UTC, ceskyDJ commented on languages.js
> +        "digitalclockinfo": "Povolí/zakáže digitální hodiny",
I'd change it to "Switches to digital clock", but here it's pretty ok right now. My translation string change refers to the current state.

2024-10-24 19:56 UTC, ceskyDJ commented on languages.js
> +        "search_suggestions_button": "Návrhy vyhledávání",
```suggestion
        "search_suggestions_button": "Návrhy ve vyhledávání",
```

2024-10-24 19:56 UTC, ceskyDJ commented on languages.js
> +        "search_suggestions_text": "Povolí/zakáže návrhy vyhledávání",
```suggestion
        "search_suggestions_text": "Zapne/vypne návrhy vyhledávání",
```

2024-10-24 19:56 UTC, ceskyDJ commented on languages.js
> +        "useproxyText": "Pokud nefungují návrhy vyhledávání",
```suggestion
        "useproxyText": "Pokud nefungují návrhy ve vyhledávání",
```

2024-10-24 19:56 UTC, ceskyDJ commented on languages.js
> +        "ProxySubtext": "Přidejte vlastní proxy pro obcházení CORS",
```suggestion
        "ProxySubtext": "Nastavte si vlastní proxy pro obcházení CORS",
```

2024-10-24 19:56 UTC, ceskyDJ commented on languages.js
> +        "UserLocSubtext": "Pokud není poloha počasí správná",
```suggestion
        "UserLocSubtext": "Pokud není správná poloha počasí",
```

2024-10-24 19:56 UTC, ceskyDJ commented on languages.js
> +        "userText": "Klikněte sem pro úpravu",
```suggestion
        "userText": "Upravíte kliknutím",
```

2024-10-24 19:58 UTC, ceskyDJ commented
I have found some strings with bad Czech translations (resp. too machine-like, unnatural). I don't know if I overlooked some strings before or if you rewrote them via machine translation, but it'd be good if the proposed fix is accepted.

2024-10-24 20:43 UTC, prem12321kumar commented on languages.js
> +        "userText": "Klikněte sem pro úpravu",
#103 MTL

2024-10-24 20:53 UTC, prem12321kumar commented
> I have found some strings with bad Czech translations (resp. too machine-like, unnatural). I don't know if I overlooked some strings before or if you rewrote them via machine translation, but it'd be good if the proposed fix is accepted.
> 
Nah, I didn't rewrite anything. I just double-checked to confirm, lol, if I pasted old translation.

> Maybe an edition for clearance. The Czech language uses a very different way of building sentences, and some things are casually said less or more differently than in English. I try to translate it like it is written in Czech from the start, so it's friendly to Czech speakers and sounds natural (like Czech, not machine-translated English).
>
Exactly, there's no need to follow the English translation word-for-word—just aim for what sounds perfect and natural.

2024-10-24 21:11 UTC, ceskyDJ commented
> Nah, I didn't rewrite anything. I just double-checked to confirm, lol, if I pasted the old translation.

Could be. I have an experience that translations need to be done in many iterations to be of good quality :D. So, maybe it all falls just on my head. I still think there were some strings that changed from my last edit (maybe before creating this pull request). I just wanted to let you (and others) know it's not good to replace already done translations with machine-generated ones. It's better to let me know (e.g., tag me), and I'll update it if it's necessary.

2024-10-24 21:16 UTC, prem12321kumar commented
Also I think for shortcuts and AI tools, "Show/Hide" would be ideal since it determines whether they are visible or not.
For the digital clock and search suggestions, "Enable/Disable" is better as it affects their functionality or availability, not just their visibility.
I'll change them tomorrow morning

2024-10-24 22:01 UTC, ceskyDJ commented
Ok, I'll update Czech strings after.

2024-10-25 06:59 UTC, itz-rj-here approved these changes
Looks good to go.

2024-10-25 07:01 UTC, itz-rj-here commented
> @itz-rj-here Translated Bengali Numerals

Great work.

2024-10-25 07:30 UTC, prem12321kumar commented
@ceskyDJ is short date format in digital clock correct?
![image](https://github.com/user-attachments/assets/fa31b7a6-2912-419d-a9bf-5012ff506dd8)

2024-10-25 08:19 UTC, itz-rj-here approved these changes

2024-10-25 13:13 UTC, itz-rj-here approved these changes
Wow good work.

2024-10-25 16:36 UTC, prem12321kumar commented
#97 fixed

2024-10-25 17:11 UTC, prem12321kumar commented
> Wow good work.

Thanks 😌

2024-10-25 17:14 UTC, prem12321kumar commented
@XengShi  I’m all done for now. Please review my changes, and feel free to suggest any modifications. I'm happy to provide explanations for any part of the updates.

2024-10-25 17:26 UTC, XengShi commented
> @XengShi  I’m all done for now. Please review my changes, and feel free to suggest any modifications. I'm happy to provide explanations for any part of the updates.

Okay, Currently I am kinda busy, outside my home, can't access my pc...

2024-10-25 17:26 UTC, ceskyDJ commented on languages.js
> +        "enable_ai_tools": "Zapne/vypne zkratky AI nástrojů",
```suggestion
        "enable_ai_tools": "Zobrazí/skryje zkratky AI nástrojů",
```

2024-10-25 17:27 UTC, ceskyDJ commented on languages.js
> +        "enableShortcutsText": "Zapne/vypne zkratky",
```suggestion
        "enableShortcutsText": "Zobrazí/skryje zkratky",
```

2024-10-25 17:28 UTC, ceskyDJ commented on languages.js
> +        "userText": "Upravíte kliknutím",
```suggestion
        "userText": "Upravíte po kliknutí",
```
Hah, this is even better :D.

2024-10-25 17:34 UTC, prem12321kumar commented
> Okay, Currently I am kinda busy, outside my home, can't access my pc...

No worries at all! Take your time.

2024-10-25 17:35 UTC, ceskyDJ commented
> @ceskyDJ is short date format in digital clock correct?

I don't know what you want to say through the short-date format. Is is `%name_of_day_in_week%, %day_in_month%.`? In this case, it's correct.

PM for 12-hour format is correct (odp.).

2024-10-25 19:03 UTC, ceskyDJ commented
> I don't know what you want to say through the short-date format. Is is `%name_of_day_in_week%, %day_in_month%.`? In this case, it's correct.

I looked at the English variant to see what it should print. It's ok ;).

2024-10-26 05:58 UTC, prem12321kumar commented
> PM for 12-hour format is correct (odp.) with one exception – we don't use leading zeros in place of hours in time (we use it just for minutes), so these are correct: 13:00, 1:00, 1:30.

yeah, leading zeros dont generally used in other lang too. ill try to change it.
From search: In 12-hour format, a leading zero is usually context-dependent in English and Italian but not commonly used in most other languages. In the 24-hour format, the leading zero is almost universally used.

2024-10-26 09:12 UTC, prem12321kumar commented
> > PM for 12-hour format is correct (odp.) with one exception – we don't use leading zeros in place of hours in time (we use it just for minutes), so these are correct: 13:00, 1:00, 1:30.
> 
> yeah, leading zeros dont generally used in other lang too. ill try to change it. From search: In 12-hour format, a leading zero is usually context-dependent in English and Italian but not commonly used in most other languages. In the 24-hour format, the leading zero is almost universally used.

Done
you can check it at https://prem12321kumar.github.io/materialYouNewTab/

2024-10-26 09:30 UTC, itz-rj-here requested changes
Can you change the twitter shortcut icon to x.com icon?

2024-10-26 09:31 UTC, itz-rj-here commented
As the twitter.com is no longer being used, it redirects to the x.com web.

2024-10-26 10:12 UTC, prem12321kumar commented
> Can you change the twitter shortcut icon to x.com icon?

I noticed it but I don't know about svg path,
Just googled and found it, I'll try in sometime if I can do.

2024-10-26 10:16 UTC, XengShi commented
> Can you change the twitter shortcut icon to x.com icon?

That little bird 🐦 is prettier than 𝕏, so I think we should still keep using that. 🙃🙃🙃

2024-10-26 10:16 UTC, itz-rj-here commented
> > Can you change the twitter shortcut icon to x.com icon?
> 
> I noticed it but I don't know about svg path, Just googled and found it, I'll try in sometime if I can do.

I see. looks like @XengShi didn't liked the idea. :) anyways then keep it as it is.

2024-10-26 10:18 UTC, prem12321kumar commented
> > Can you change the twitter shortcut icon to x.com icon?
> 
> That little bird 🐦 is prettier than 𝕏, so I think we should still keep using that. 🙃🙃🙃


Ok lol, I also like the old icon and name, 
Will just change the redirect link
no name or icon change

2024-10-26 10:18 UTC, XengShi commented
> 
> > > Can you change the twitter shortcut icon to x.com icon?
> > 
> > I noticed it but I don't know about svg path, Just googled and found it, I'll try in sometime if I can do.
> 
> I see. looks like @XengShi didn't liked the idea. :) anyways then keep it as it is.

If you want it, simply use "𝕏" (copy & paste) and replace it with twitter svg.

2024-10-26 11:55 UTC, XengShi commented
You've done a lot of work, improving translation accuracy and other aspects, but unfortunately, I'm still facing the same issue we encountered earlier.
The weather elements are still getting stuck on 'Seems' and 'Earth.'


https://github.com/user-attachments/assets/c6353346-cdcd-48e7-b5a1-65345536cac6

@itz-rj-here Can you test this repo on your machine

2024-10-26 12:48 UTC, itz-rj-here commented
> You've done a lot of work, improving translation accuracy and other aspects, but unfortunately, I'm still facing the same issue we encountered earlier. The weather elements are still getting stuck on 'Seems' and 'Earth.'
> 
>  2024-10-26.11-34-16.mp4 
> @itz-rj-here Can you test this repo on your machine

Just a min let me download it and check it.

2024-10-26 12:53 UTC, prem12321kumar commented
> You've done a lot of work, improving translation accuracy and other aspects, but unfortunately, I'm still facing the same issue we encountered earlier. The weather elements are still getting stuck on 'Seems' and 'Earth.'
> 
>  2024-10-26.11-34-16.mp4 
> @itz-rj-here Can you test this repo on your machine

that's odd, it's working fine for me on Chrome. I'll look into the code.

Can you please confirm if :main has the same issue or not.

https://xengshi.github.io/materialYouNewTab/
and https://prem12321kumar.github.io/materialYouNewTab/
both have correct display but when refreshed, the same display like yours. I thought at first it maybe because of some issue with virtual deployment.

2024-10-26 12:57 UTC, itz-rj-here commented
https://screenrec.com/share/7YtjxoNDeF

2024-10-26 12:58 UTC, itz-rj-here commented
> You've done a lot of work, improving translation accuracy and other aspects, but unfortunately, I'm still facing the same issue we encountered earlier. The weather elements are still getting stuck on 'Seems' and 'Earth.'
> 
>  2024-10-26.11-34-16.mp4 
> @itz-rj-here Can you test this repo on your machine

It currently works fine for me. Just the weather icon sometimes doesn't load cuz of the loading timeout.

2024-10-26 12:59 UTC, itz-rj-here commented
@prem12321kumar can i know why you replaced the weather icon little bit of downwards?

2024-10-26 13:08 UTC, itz-rj-here commented
W8 i found something weird. let me screen record and show ya all.

2024-10-26 13:15 UTC, itz-rj-here commented
https://screenrec.com/share/G08aQb2hru

When I use a vpn and connect to uk ip, my weatherapi runs properly. But in my own ip the weatherapi sometimes doesn't able to give correct data and stays blank.

2024-10-26 13:30 UTC, prem12321kumar commented
> * position it for better appearing

It was appearing a bit off to me, one sided.
It is highlighted especially in clear night one

https://github.com/user-attachments/assets/2a866143-b7dc-4659-8258-9acb1004c8ee


Is it not fine?

2024-10-26 13:49 UTC, prem12321kumar commented
> https://screenrec.com/share/G08aQb2hru
> 
> When I use a vpn and connect to uk ip, my weatherapi runs properly. But in my own ip the weatherapi sometimes doesn't able to give correct data and stays blank.

huh, here no problem with display of Humidity, Feels, Earth 
but weather icon not loading but loaded with vpn... can't understand reason
Try with a different API?

2024-10-26 13:52 UTC, ceskyDJ commented
> Try with a different API?

Maybe download images and serve them locally? Is it possible?

2024-10-26 14:32 UTC, itz-rj-here commented
> > https://screenrec.com/share/G08aQb2hru
> > 
> > When I use a vpn and connect to uk ip, my weatherapi runs properly. But in my own ip the weatherapi sometimes doesn't able to give correct data and stays blank.
> 
> huh, here no problem with display of Humidity, Feels, Earth 
> but weather icon not loading but loaded with vpn... can't understand reason
> Try with a different API?

It happens cause the ip of the weatherapi takes time to connect with my ip.

2024-10-26 14:40 UTC, prem12321kumar commented
> It happens cause the ip of the weatherapi takes time to connect with my ip.

if so then maybe other data also shouldn't have loaded

can you try deleting cookies and site data of weatherapi.com
![image](https://github.com/user-attachments/assets/298c19db-c711-44f3-a913-c51bafc74215)
then open new tab and press Ctrl + Shift + R

2024-10-26 17:30 UTC, prem12321kumar commented
@XengShi what is the error in the console?

2024-10-27 05:56 UTC, prem12321kumar commented
> @XengShi what is the error in the console?

Do you face the same issue in XengShi:main/v2.2, or is it working fine?

2024-10-27 11:32 UTC, itz-rj-here commented
> > @XengShi what is the error in the console?
> 
> Do you face the same issue in XengShi:main/v2.2, or is it working fine?

https://screenrec.com/share/uPQ6t0fdAH
https://screenrec.com/share/fYztmTpOMo

2024-10-27 11:32 UTC, itz-rj-here commented
I faced some issues here.

2024-10-27 11:43 UTC, itz-rj-here commented
Also noticed that you have replaced the icon at little bit of downwards, which doesn't look good. Also ur weather icon has issue. Not on the original one as i noticed.

2024-10-27 11:48 UTC, itz-rj-here commented
I think you should look on this and try to add some other weather api's too.
https://github.com/PranshulGG/WeatherMaster/tree/v1.7.4?tab=readme-ov-file#-weather-providers

2024-10-27 12:58 UTC, XengShi commented
@prem12321kumar Today I rechecked it again, and everything works! not getting any error.

2024-10-27 13:13 UTC, merged

2024-10-28 04:37 UTC, XengShi commented
> > @XengShi what is the error in the console?
> 
> Do you face the same issue in XengShi:main/v2.2, or is it working fine?

[Windows 10, Chrome]
On the first reload or opening a new tab, it shows the location and 'Feels like' temperature for a few milliseconds, but then it goes back to displaying 'Earth' and 'Feels,' even though the temperature is shown correctly (in the pill-shaped widget).


![Screenshot 2024-10-28 043052](https://github.com/user-attachments/assets/27c63800-d1cf-4d02-bbaf-0d4f92f41f0d)
![image](https://github.com/user-attachments/assets/1cfe2e02-4310-4665-8d1e-05772c8760cb)

2024-10-28 04:53 UTC, prem12321kumar commented
> > > @XengShi what is the error in the console?
> > 
> > 
> > Do you face the same issue in XengShi:main/v2.2, or is it working fine?
> 
> [Windows 10, Chrome] On the first reload or opening a new tab, it shows the location and 'Feels like' temperature for a few milliseconds, but then it goes back to displaying 'Earth' and 'Feels,' even though the temperature is shown correctly (in the pill-shaped widget).
> 
> ![Screenshot 2024-10-28 043052](https://private-user-images.githubusercontent.com/48722764/380578001-27c63800-d1cf-4d02-bbaf-0d4f92f41f0d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzAwOTEzMjIsIm5iZiI6MTczMDA5MTAyMiwicGF0aCI6Ii80ODcyMjc2NC8zODA1NzgwMDEtMjdjNjM4MDAtZDFjZi00ZDAyLWJiYWYtMGQ0ZjkyZjQxZjBkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDI4VDA0NTAyMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQzOWRmMTM4Nzc0NWI1NjIzN2M0YWNiMTIwN2UwZWJkNTUyMTkxNTFkMDY2N2NhYWFjZDVkM2Y0OGM2ZDBmYzYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.4hhZfCEmpgoEsMCbioYKbuMiUb4xdSaskni9T12GUaE) ![image](https://private-user-images.githubusercontent.com/48722764/380578493-1cfe2e02-4310-4665-8d1e-05772c8760cb.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzAwOTEzMjIsIm5iZiI6MTczMDA5MTAyMiwicGF0aCI6Ii80ODcyMjc2NC8zODA1Nzg0OTMtMWNmZTJlMDItNDMxMC00NjY1LThkMWUtMDU3NzJjODc2MGNiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDI4VDA0NTAyMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTcxZWE3MWYwM2QzZTExY2Y1NDgzMGQ4NjYxYmVhNjlhZWIyZDNhN2Y0ZGY3NjVmYTc4OWMyYzhjZDgwNWE0MGEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.JoOuzr7Mf8ZrXPO-WM4m9xGnw1Qxktd9C7sgEH-qQ5k)

#113 
Please try resetting shortcuts 
![IMG_20241028_102337](https://github.com/user-attachments/assets/a3812718-8e4c-4d18-af8f-4c70d4be8c3d)