Supplement to the Russian translation
XengShi/materialYouNewTab pull request #130
Opened 2024-11-02 19:54 UTC by giwih

2024-11-02 20:25 UTC, giwih commented
also added a black-amoled theme 
![photo_2024-11-02_23-15-26](https://github.com/user-attachments/assets/60897267-2925-4866-8929-fd0cf28a0c5e)

2024-11-03 12:10 UTC, itz-rj-here commented
![image](https://github.com/user-attachments/assets/fb47a68d-fab2-4a76-8eb4-51f478a35249)

The theme you added is not exeptable. Cause the parts of the weather icon and clock things, are on white color. The white icons too much effects the eyes too much. Which makes the theme bad. Also the theme doesn't goes with the text colors too. Sorry but I couldn't accept your new amoled theme.

2024-11-03 12:11 UTC, itz-rj-here commented
> ![image](https://private-user-images.githubusercontent.com/86042583/382569428-fb47a68d-fab2-4a76-8eb4-51f478a35249.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzA2MzYxNDYsIm5iZiI6MTczMDYzNTg0NiwicGF0aCI6Ii84NjA0MjU4My8zODI1Njk0MjgtZmI0N2E2OGQtZmFiMi00YTc2LThlYjQtNTFmNDc4YTM1MjQ5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMDMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTAzVDEyMTA0NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTBhYzFhZjllMzAwMTk3ODhiYWJhMThkYWI0NjY0ZTJmMmVkM2E3NzZlZmNmMTc0MzM5OGM5OTViM2EwNmQ0ZGEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.a5u6r6UaPdkKODrCsR0Rkqfln7Is1QlcuURonEOpxQE)
> 
> The theme you added is not exeptable. Cause the parts of the weather icon and clock things, are on white color. The white things too much effects the eyes too much. Which makes the theme bad. Also the theme doesn't goes with the text colors too. Sorry but I couldn't accept your new amoled theme.

2024-11-03 12:12 UTC, itz-rj-here commented
@prem-k-r what you think about it?

2024-11-03 12:22 UTC, prem-k-r commented
It's a nice idea, but need some modifications, I think. The background should be pure black, and other colors should be adjusted to complement the black. Additionally, need to review the shadow effects on the close button and shortcut icons to ensure they look good against the theme.

2024-11-03 12:25 UTC, itz-rj-here commented
> It's a nice idea, but need some modifications, I think. The background should be pure black, and other colors should be adjusted to complement the black. Additionally, need to review the shadow effects on the close button and shortcut icons to ensure they look good against the theme.

Agreed.

2024-11-03 12:25 UTC, itz-rj-here requested changes
Modification needed.

2024-11-03 13:29 UTC, giwih commented
![{4F0BBD0A-6481-4C94-8AA1-3F454E9357CF}](https://github.com/user-attachments/assets/414c1889-6931-4a87-b58e-8a1cfee545a5)

2024-11-03 13:32 UTC, itz-rj-here commented
![image](https://github.com/user-attachments/assets/aeb9e9c5-e866-4b31-8e29-ebc3a200388e)
Thanks but the shortcuts and the weather info section doesn't goes with it in all way. But still i need @prem-k-r confirmation what he thinks about it.

2024-11-03 14:54 UTC, giwih commented
> shortcuts and the weather

how about this?
![{2487E572-3CF4-4C61-A90B-DD288DC67526}](https://github.com/user-attachments/assets/3be4dc29-3108-469d-a6a5-cd865e55bc56)

2024-11-03 15:46 UTC, itz-rj-here commented
Great work. Now it looks good as new. Thanks for your hard work.

2024-11-03 15:47 UTC, itz-rj-here approved these changes

2024-11-03 18:25 UTC, prem-k-r requested changes
.colorsContainer input[value="dark"] {
    background-color: #818181;
}

line 1613, please change color to #434343

2024-11-03 18:28 UTC, prem-k-r commented
How about this one? @giwih @itz-rj-here 

![image](https://github.com/user-attachments/assets/259080e8-8590-4c0f-a1c3-bf643cc43135)

/* Amoled Dark */
    --bg-color-amoled: #000; 
    --accentLightTint-amoled: #434343;
    --darkerColor-amoled: #000000;
    --darkColor-amoled: #707070;
    --textColorDark-amoled: #969696;

2024-11-03 18:45 UTC, prem-k-r commented
or a bit darker and maybe better
--accentLightTint-amoled: #353535;

2024-11-03 19:01 UTC, giwih commented
> How about this one? @giwih itz-rj-here

also looks good, but personally I like my version a bit more) let itz-rj-here decide

2024-11-03 19:10 UTC, prem-k-r commented
A bit darker than my last one

![image](https://github.com/user-attachments/assets/567f9fdf-75b1-4283-ba9a-4e5ab964770d)

/* Amoled Dark */
    --bg-color-amoled: #000000; 
    --accentLightTint-amoled: #313131;
    --darkerColor-amoled: #000000;
    --darkColor-amoled: #696969;
    --textColorDark-amoled: #969696;

2024-11-03 20:12 UTC, prem-k-r commented
![image](https://github.com/user-attachments/assets/bbe4ba2d-3ccb-42e3-b420-eabaf61c756b)
![image](https://github.com/user-attachments/assets/6595018f-8648-49f7-a861-0f6720a82b9b)
![image](https://github.com/user-attachments/assets/db7930a9-1f06-429a-b3cf-970aad5a8b42)

/* Amoled Dark */
    --bg-color-amoled: #000000; 
    --accentLightTint-amoled: #1D1D1D;
    --darkerColor-amoled: #999999;
    --darkColor-amoled: #555555;
    --textColorDark-amoled: #aaaaaa;

2024-11-04 01:01 UTC, itz-rj-here commented
> > How about this one? @giwih itz-rj-here
> 
> also looks good, but personally I like my version a bit more) let itz-rj-here decide

I will check it after i come to home.

2024-11-04 07:02 UTC, XengShi commented
![Uploading Screenshot_20241103_232354.jpg …]()

Concept for dark mode

2024-11-04 09:04 UTC, itz-rj-here commented
![image](https://github.com/user-attachments/assets/87421d1d-bcea-4701-92c4-3066197abd35)
Change this Weather temperature number color to full black, and change the shortcut to gray color like @prem-k-r just showed. and in other hand, In the menu section the github and feedback option of the text is hardly be seen. If possible please fix that issue too. 
![image](https://github.com/user-attachments/assets/60a481a5-b6ca-48b4-bd1b-96cb0b4d7ee9)

2024-11-04 09:07 UTC, itz-rj-here commented
I will come again after a few hours to check your commits/ changes. I need a nap. I just slept for only 4 hours last night cause of the exams presure. But luckily i got all my answers right thats all i need. 
I am going now. Bye.

2024-11-04 11:27 UTC, itz-rj-here commented
> ![{2E4DA39A-4E90-4879-8A27-E65CB1601111}](https://private-user-images.githubusercontent.com/107575390/382734820-e71b5642-b181-4201-ab00-f319e7cdced0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzA3MTk4NTgsIm5iZiI6MTczMDcxOTU1OCwicGF0aCI6Ii8xMDc1NzUzOTAvMzgyNzM0ODIwLWU3MWI1NjQyLWIxODEtNDIwMS1hYjAwLWYzMTllN2NkY2VkMC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTA0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTEwNFQxMTI1NThaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wNDBiZGNjZTkyZTMyM2ZiYjMyYzRjOWZlNWMxMDBhZWViZmIyOTcwZjVhYWZhZWRhM2E1ZDE0OTg5ZmQ3MmQ4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.3QpY4rkBPRvkeWbo7nl-UW4ZFaPpVbQeqsYa59s5GhU) ![{E4CFF0CB-FC5C-4BA9-B43E-C2F6C3835C59}](https://private-user-images.githubusercontent.com/107575390/382734874-d4491e05-ab1e-4c7f-b3bc-24aa7627dc16.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzA3MTk4NTgsIm5iZiI6MTczMDcxOTU1OCwicGF0aCI6Ii8xMDc1NzUzOTAvMzgyNzM0ODc0LWQ0NDkxZTA1LWFiMWUtNGM3Zi1iM2JjLTI0YWE3NjI3ZGMxNi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTA0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTEwNFQxMTI1NThaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wMzA5YzlhNGQ5ZTRmNTE4ZWUzODM2YjUzZTYwMWQ0Yjk3NTJlMzIzNWFiZmU4ZTRlOTk1ZjM0NTVmYWE3ODlkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.SBY-Fz_pgzk7kdasJ5p7dfgeVAXqYhxZQn-o8eZ3myI)

Keep it open. I need to check more things. The amoled theme changes the shortcuts too. Bruh thats should have a different color theme selection. uhh.

2024-11-04 11:34 UTC, itz-rj-here requested changes
Needed an option to change only the shortcut themes not the all themes. Needed time to add the color theme on shortcut in different option.

2024-11-04 11:41 UTC, itz-rj-here commented
@giwih The changes you made doesn't goes with the name of amoled theme. It completely changes the color theme. I would like to get some time to hopefully able to add a different option to add color code for shortcuts.

2024-11-04 13:20 UTC, prem-k-r commented
Personally, I don't like black color in dark grey background as in clock and temperature.
I would suggest to go live with something like below for now
![image](https://github.com/user-attachments/assets/95ef3597-7383-4c0b-a00f-bf48d5b9ebff)
![image](https://github.com/user-attachments/assets/5189ea9f-0568-447f-bb5c-6d55cf25a7c9)
Considered shortcuts, toggles, texts, Github/feedback, etc

To the user, Amoled name is not showing anywhere. So user may think it as Dark grey, and existing dark theme to Light grey.
Later we can change some elements, have to creates separates color variables for seperate entities, and go for full amoled

well, @itz-rj-here, upto you guys

2024-11-04 14:16 UTC, giwih commented
I like the gray temperature better too. But light gray shorcuts look not very good, as itz-rj-here said I added to be able to select color separately for shorcuts.
![{3A5F85A0-5E73-4322-9ECD-952FB7E45EEC}](https://github.com/user-attachments/assets/3c42fcd9-f92a-4c0e-9e1b-d5e0cf803fd2)

2024-11-04 14:31 UTC, itz-rj-here commented
> I like the gray temperature better too. But light gray shorcuts look not very good, as itz-rj-here said I added to be able to select color separately for shorcuts. ![{3A5F85A0-5E73-4322-9ECD-952FB7E45EEC}](https://private-user-images.githubusercontent.com/107575390/382787473-3c42fcd9-f92a-4c0e-9e1b-d5e0cf803fd2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzA3MzA5MDgsIm5iZiI6MTczMDczMDYwOCwicGF0aCI6Ii8xMDc1NzUzOTAvMzgyNzg3NDczLTNjNDJmY2Q5LWY5MmEtNGMwZS05ZTFiLWQ1ZTBjZjgwM2ZkMi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTA0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTEwNFQxNDMwMDhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02ZTQxODcwNWU0NGQ3YmUzZGJhYmExNzk0N2NmYzc3MzdkZGQ4NjVkNGY2ZjhmZjllMTVmMGEzMWU5OTg0MjNlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.ZBruLeuAm5UHs3BA_wB3psPPceLG8nIj2xjQ2PerDSY)
> 
> But I can't understand why there's a border, so if I add something lighter, it really stands out against the black background. ![{B8ACBAC9-7EBD-45C1-8A43-272F9502BEE0}](https://private-user-images.githubusercontent.com/107575390/382788814-cd278048-547f-4295-bb2a-89de658796da.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzA3MzA5MDgsIm5iZiI6MTczMDczMDYwOCwicGF0aCI6Ii8xMDc1NzUzOTAvMzgyNzg4ODE0LWNkMjc4MDQ4LTU0N2YtNDI5NS1iYjJhLTg5ZGU2NTg3OTZkYS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTA0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTEwNFQxNDMwMDhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hMDhhOWFlMzc1ZTNlYTVlZTcyNTJmZjBkYmQ3OGRlNzc2ZmVlYzc4MzgzY2QzMDFkNjRhYmJjOTMxMmI4NDMxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.Q9-YOy6x6CtIwILuSSoxQahgCRNu2foM7mkHfpfE48E)

I know but we don't have any other options for now.

2024-11-04 14:52 UTC, prem-k-r commented
@giwih 
![image](https://github.com/user-attachments/assets/959f5806-4232-44fc-8baa-bc77f09fdd28)

2024-11-05 02:41 UTC, itz-rj-here commented
![image](https://github.com/user-attachments/assets/f0760de3-10cb-48dd-8452-e1ddcaa79d06)
Great work with the changes but fix the custom shortcut colors too. Then i will tell XengShi to merge this pr.

2024-11-05 05:09 UTC, prem-k-r commented
> @giwih ![image](https://private-user-images.githubusercontent.com/60751338/382800960-959f5806-4232-44fc-8baa-bc77f09fdd28.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzA3ODMxMTMsIm5iZiI6MTczMDc4MjgxMywicGF0aCI6Ii82MDc1MTMzOC8zODI4MDA5NjAtOTU5ZjU4MDYtNDIzMi00NGZjLThiYWEtYmM3N2YwOWZkZDI4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTA1VDA1MDAxM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTc3YTRmMTY1MWQ1NWI4ZDZkMTY4ZTcxNTE0MjQ4YmVkYjRiMmJmYTczN2FjOWI4MzAzMzYzMWU0MjI3ODU5NjImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.RhIGsLetbGV6styEVtSerNl_50Wa-DfL7t6ktgWUQW4)

ah sorry, I missed to copy some changes in script.js. It's working normal.
![image](https://github.com/user-attachments/assets/bc883e60-fccc-48ff-9db4-951c762fe5c1)

It's great, thanks for your efforts.

icon color a little bit light grey will be better, I think
--shortcutIconColor-amoled:#5d5d5d;
![image](https://github.com/user-attachments/assets/619ca40b-3ca7-453d-adcf-7df41e717ea0)

2024-11-05 06:33 UTC, prem-k-r commented
or how about this?
![image](https://github.com/user-attachments/assets/61dfb405-52c3-491b-9ef4-054004807134)
--shortcutColor-amoled: #414141;
--shortcutIconColor-amoled:#000;
![image](https://github.com/user-attachments/assets/17d5b007-b3dd-413b-81c1-5dbb070fd1b6)

2024-11-05 06:46 UTC, prem-k-r commented
Also close button doesnt look good to me
maybe change back line 1744 to background-color: #fff
![image](https://github.com/user-attachments/assets/b0b3e946-ec57-45d4-9527-682e779922c7)
to (what it was earlier):
![image](https://github.com/user-attachments/assets/45f38358-7b01-42b0-b3df-7894931e0c25)

and if we can do something about the outer circle in close button 
![image](https://github.com/user-attachments/assets/32de1843-da37-4d7e-9f3e-a68d287f80db)

2024-11-05 08:09 UTC, itz-rj-here commented
@giwih can you resolve the conflicts please

2024-11-05 11:37 UTC, itz-rj-here approved these changes
Accepted @XengShi Can you please merge this pr.

2024-11-05 11:50 UTC, giwih commented on script.js
what do you mean?

2024-11-05 11:55 UTC, itz-rj-here commented on script.js
Well it was my mistake. I was watching your changes from mobile. Not from computer thats why i didn't saw some of the codes clearly.

2024-11-05 12:02 UTC, prem-k-r approved these changes

2024-11-06 09:26 UTC, itz-rj-here commented
Bruh what happened again -_- why it again shows conflicts.

2024-11-06 09:27 UTC, itz-rj-here commented
@giwih Can you resolve the conflicts one more time please
and
@XengShi Can you merge this pr please.

2024-11-06 14:49 UTC, prem-k-r commented
Conflict resolved, good to go, @XengShi please merge

2024-11-06 15:04 UTC, itz-rj-here commented
> Conflict resolved, good to go, @XengShi please merge

he is offline everywhere.

2024-11-06 18:44 UTC, XengShi commented
![IMG_20241107_001055.jpg](https://github.com/user-attachments/assets/a3b89805-6257-4261-b10c-2462c3699700)

Kindly make texts more readable/brighter, take some inspiration from the image

2024-11-09 12:25 UTC, itz-rj-here commented
Hmm looks like i have to do something with this. 😐

2024-11-09 14:29 UTC, prem-k-r commented
> Kindly make texts more readable/brighter, take some inspiration from the image

![image](https://github.com/user-attachments/assets/8dfd3af6-473c-403b-afc6-8f8460fe2f74)
@XengShi How about this?

2024-11-09 14:42 UTC, itz-rj-here commented
> > Kindly make texts more readable/brighter, take some inspiration from the image
> 
> ![image](https://private-user-images.githubusercontent.com/60751338/384614377-8dfd3af6-473c-403b-afc6-8f8460fe2f74.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzExNjM1NzcsIm5iZiI6MTczMTE2MzI3NywicGF0aCI6Ii82MDc1MTMzOC8zODQ2MTQzNzctOGRmZDNhZjYtNDczYy00MDNiLWFmYzYtOGY4NDYwZmUyZjc0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTA5VDE0NDExN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWJiMDNlZGNjNWQ4MGVmZGI1MWQxZTI5MjcxNzNiODExMjg2ODM5NmQzZDc1YzMzNjFkNjViM2I5MGQ3ZGE2MDQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.laACxl6LE2Y_06oD8V4ZswasH45ybQlAz3iFthX-x5E) @XengShi How about this?

Yup as he wanted.

2024-11-09 14:46 UTC, itz-rj-here commented
Currently it looks like this. 
![image](https://github.com/user-attachments/assets/0f4211ae-f5df-4560-9bca-ec402b42f320)
![image](https://github.com/user-attachments/assets/3f53d0b3-a3b5-45e4-bdba-cd4f9d31ed5a)

2024-11-09 14:51 UTC, itz-rj-here commented
Lets do a thing. @XengShi will merge this changes and you will fix the text color code.
What do you think? @prem-k-r

2024-11-09 14:55 UTC, prem-k-r commented
Yep, but it's up to him.. if he likes or not

2024-11-09 15:04 UTC, itz-rj-here commented
> Yep, but it's up to him.. if he likes or not

Im sure he would like your changes.

2024-11-10 04:29 UTC, XengShi commented
> @giwih conflict 
> XengShi has modified the existing dark theme instead.
> It might be better to close this PR and open a new one focusing solely on the Russian translation.
> 
> 

Do you guys liked the new dark theme ?
@giwih @prem-k-r @itz-rj-here ?

2024-11-10 05:00 UTC, prem-k-r commented
> > @giwih conflict
> > XengShi has modified the existing dark theme instead.
> > It might be better to close this PR and open a new one focusing solely on the Russian translation.
> 
> Do you guys liked the new dark theme ? @giwih @prem-k-r @itz-rj-here ?

Yep, almost perfect, it’s better than what we were suggesting.
But I think having two dark themes would’ve been great: one in light grey and the other in the black you changed it to. The grey theme needed some modifications too though.

2024-11-10 08:11 UTC, itz-rj-here commented
> > @giwih conflict 
> > XengShi has modified the existing dark theme instead.
> > It might be better to close this PR and open a new one focusing solely on the Russian translation.
> > 
> > 
> 
> Do you guys liked the new dark theme ?
> @giwih @prem-k-r @itz-rj-here ?

Actually yeah looks better than the gray one. Using the gray one at night, it kind of hurts my eyes. Thats way i liked the black theme idea.

2024-11-11 07:22 UTC, itz-rj-here requested changes
Looks like the file has some conflicts :)

2024-11-11 07:44 UTC, prem-k-r commented
> @giwih conflict 
XengShi has modified the existing dark theme instead. It might be better to close this PR and open a new one focusing solely on the Russian translation.

..

2024-11-11 07:50 UTC, closed without merging