Improved responsiveness of shortcuts section
XengShi/materialYouNewTab pull request #227
Opened 2024-11-29 10:30 UTC by sohan10012

Enhanced Visual Appeal: Adjusted the CSS to align the `#shortcuts-section` to the right, making it look more organized and visually appealing.
  - For screens wider than 1400px, the section is positioned 320px from the right edge.
  - For screens between 1400px and 1200px, the right margin decreases dynamically to keep the 
     section aligned to the right.
  - For screens narrower than 1200px, the section is centered horizontally.
  - For screens narrower than 900px, the section remains centered and takes the full width.
- Responsive Design: Added media queries to handle different screen widths and ensure smooth  
                                   transitions.
- Consistent Layout: Utilized flexbox properties such as `flex-wrap` and `justify-content` to maintain 
                               
- Uniform Spacing: Applied consistent padding and gap values to ensure uniform spacing.

Impact:
- Improved the overall look and feel of the shortcuts section, making it more user-friendly and aesthetically pleasing across various screen sizes.
- Enhanced the user experience by maintaining consistent positioning and alignment of the shortcuts section on different devices.
![shortcut-change-ss](https://github.com/user-attachments/assets/134b1efe-d9fc-449b-b61d-46f2f466a14a)

2024-11-29 11:01 UTC, itz-rj-here requested changes
Requesting changes

2024-11-29 11:01 UTC, itz-rj-here commented on style.css
> +    right: 320px; /* Adjusted margin for shortcuts to align right */
Sorry @sohan10012 but we can't let the shortcuts align at the right side.
You should change it.

2024-11-29 11:57 UTC, sohan10012 commented
Oh ok thank you 😄

On Fri, 29 Nov, 2024, 4:27 pm XengShi, ***@***.***> wrote:

> Screencast from 2024-11-29 16-18-10.webm
> <https://github.com/user-attachments/assets/dacf9549-11e9-4826-a5ba-f1353f9e906b>
>
> I see weird positioning of shortcuts for larger devices, Please don't
> change its position keep it centered
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/XengShi/materialYouNewTab/pull/227#issuecomment-2507568915>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/BHX3ONNBQ743V23TDLDXDRL2DBB7ZAVCNFSM6AAAAABSWZ5IEWVHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMZDKMBXGU3DQOJRGU>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2024-11-29 12:32 UTC, sohan10012 commented
i resolved that isse and now can u please check once >??

2024-11-29 12:40 UTC, itz-rj-here commented
@XengShi @prem-k-r

2024-11-29 12:43 UTC, sohan10012 commented
> Screencast.from.2024-11-29.16-18-10.webm 
> I see weird positioning of shortcuts for larger devices, Please don't change its position keep it centered

the shortcut tab position is in fixed position , so the shortcut section looked weird ,, but if u insepect the page and check for its views in differents screen widths , the shortcut centre is completely alligned ,
i request u to check once by inspect element option because i referred that , because by default the round button in right corner has its postion fixed 
i request u to please review by checking in the inspect page option , 

Thank you for the reviews

2024-11-29 12:52 UTC, sohan10012 commented
https://github.com/user-attachments/assets/1c23a56b-21ff-404b-a6ad-016bbafc5bb5

this is the screen recording

2024-11-29 13:10 UTC, prem-k-r requested changes
it is not centered
![image](https://github.com/user-attachments/assets/332370a5-7244-4ce3-a760-5eecb4b2f5f4)
![image](https://github.com/user-attachments/assets/ff62a518-4090-49d7-a564-663cc3adb990)

2024-11-29 13:15 UTC, sohan10012 commented
> it is not centered ![image](https://private-user-images.githubusercontent.com/60751338/391095129-332370a5-7244-4ce3-a760-5eecb4b2f5f4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzI4ODYzMzQsIm5iZiI6MTczMjg4NjAzNCwicGF0aCI6Ii82MDc1MTMzOC8zOTEwOTUxMjktMzMyMzcwYTUtNzI0NC00Y2UzLWE3NjAtNWVlY2I0YjJmNWY0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTI5VDEzMTM1NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTY5NjU3NDVmMzY2ZGYxMDIxYjdmYjhmNDNiOTE2NWM1MDM1NjA4OGY2N2Q4M2M0YjFlYmVkNGQ3NDNmMmJlMDEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.JD04PpSJk7hZ92JmjngSVDe0H_Vod9WoUJx2ZI0aUmc) ![image](https://private-user-images.githubusercontent.com/60751338/391095140-ff62a518-4090-49d7-a564-663cc3adb990.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzI4ODYzMzQsIm5iZiI6MTczMjg4NjAzNCwicGF0aCI6Ii82MDc1MTMzOC8zOTEwOTUxNDAtZmY2MmE1MTgtNDA5MC00OWQ3LWE1NjQtNjYzY2MzYWRiOTkwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTI5VDEzMTM1NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTZjYmM2NDIxNzczOTMxMDJjMmYxN2VhYWJlZGViOTQ4NzQwMjFkZTg5NTkyOTIwMDc3MDhlODZhOTgxYzMyNTcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.kBe9p0u0bsfiVFsbEn-5Oj8U5DgF9IC4eJv84omdVBY)

actually my goal was to keep it in the right side so that it looks organised , that was the idea behind my code update , i am sorry if u didnt like it , I just felt it looked organised in the right so suggested with an change of code

2024-11-29 13:21 UTC, prem-k-r commented
> > it is not centered ![image](https://private-user-images.githubusercontent.com/60751338/391095129-332370a5-7244-4ce3-a760-5eecb4b2f5f4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzI4ODYzMzQsIm5iZiI6MTczMjg4NjAzNCwicGF0aCI6Ii82MDc1MTMzOC8zOTEwOTUxMjktMzMyMzcwYTUtNzI0NC00Y2UzLWE3NjAtNWVlY2I0YjJmNWY0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTI5VDEzMTM1NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTY5NjU3NDVmMzY2ZGYxMDIxYjdmYjhmNDNiOTE2NWM1MDM1NjA4OGY2N2Q4M2M0YjFlYmVkNGQ3NDNmMmJlMDEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.JD04PpSJk7hZ92JmjngSVDe0H_Vod9WoUJx2ZI0aUmc) ![image](https://private-user-images.githubusercontent.com/60751338/391095140-ff62a518-4090-49d7-a564-663cc3adb990.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzI4ODYzMzQsIm5iZiI6MTczMjg4NjAzNCwicGF0aCI6Ii82MDc1MTMzOC8zOTEwOTUxNDAtZmY2MmE1MTgtNDA5MC00OWQ3LWE1NjQtNjYzY2MzYWRiOTkwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTI5VDEzMTM1NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTZjYmM2NDIxNzczOTMxMDJjMmYxN2VhYWJlZGViOTQ4NzQwMjFkZTg5NTkyOTIwMDc3MDhlODZhOTgxYzMyNTcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.kBe9p0u0bsfiVFsbEn-5Oj8U5DgF9IC4eJv84omdVBY)
> 
> actually my goal was to keep it in the right side so that it looks organised , that was the idea behind my code update , i am sorry if u didnt like it , I just felt it looked organised in the right so suggested with an change of code

**Coreng Reply:**  
Oh, no worries! I understand your intention to keep it organized, but I personally don't prefer the right-aligned change.

2024-11-29 13:30 UTC, itz-rj-here commented
> > > it is not centered ![image](https://private-user-images.githubusercontent.com/60751338/391095129-332370a5-7244-4ce3-a760-5eecb4b2f5f4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzI4ODYzMzQsIm5iZiI6MTczMjg4NjAzNCwicGF0aCI6Ii82MDc1MTMzOC8zOTEwOTUxMjktMzMyMzcwYTUtNzI0NC00Y2UzLWE3NjAtNWVlY2I0YjJmNWY0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTI5VDEzMTM1NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTY5NjU3NDVmMzY2ZGYxMDIxYjdmYjhmNDNiOTE2NWM1MDM1NjA4OGY2N2Q4M2M0YjFlYmVkNGQ3NDNmMmJlMDEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.JD04PpSJk7hZ92JmjngSVDe0H_Vod9WoUJx2ZI0aUmc) ![image](https://private-user-images.githubusercontent.com/60751338/391095140-ff62a518-4090-49d7-a564-663cc3adb990.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzI4ODYzMzQsIm5iZiI6MTczMjg4NjAzNCwicGF0aCI6Ii82MDc1MTMzOC8zOTEwOTUxNDAtZmY2MmE1MTgtNDA5MC00OWQ3LWE1NjQtNjYzY2MzYWRiOTkwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTI5VDEzMTM1NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTZjYmM2NDIxNzczOTMxMDJjMmYxN2VhYWJlZGViOTQ4NzQwMjFkZTg5NTkyOTIwMDc3MDhlODZhOTgxYzMyNTcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.kBe9p0u0bsfiVFsbEn-5Oj8U5DgF9IC4eJv84omdVBY)
> > 
> > 
> > actually my goal was to keep it in the right side so that it looks organised , that was the idea behind my code update , i am sorry if u didnt like it , I just felt it looked organised in the right so suggested with an change of code
> 
> Oh, no worries! I understand your intention to keep it organized, but I personally don't prefer the right-aligned change.

Mee too.

2024-11-29 13:54 UTC, sohan10012 commented
> > > it is not centered ![image](https://private-user-images.githubusercontent.com/60751338/391095129-332370a5-7244-4ce3-a760-5eecb4b2f5f4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzI4ODYzMzQsIm5iZiI6MTczMjg4NjAzNCwicGF0aCI6Ii82MDc1MTMzOC8zOTEwOTUxMjktMzMyMzcwYTUtNzI0NC00Y2UzLWE3NjAtNWVlY2I0YjJmNWY0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTI5VDEzMTM1NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTY5NjU3NDVmMzY2ZGYxMDIxYjdmYjhmNDNiOTE2NWM1MDM1NjA4OGY2N2Q4M2M0YjFlYmVkNGQ3NDNmMmJlMDEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.JD04PpSJk7hZ92JmjngSVDe0H_Vod9WoUJx2ZI0aUmc) ![image](https://private-user-images.githubusercontent.com/60751338/391095140-ff62a518-4090-49d7-a564-663cc3adb990.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzI4ODYzMzQsIm5iZiI6MTczMjg4NjAzNCwicGF0aCI6Ii82MDc1MTMzOC8zOTEwOTUxNDAtZmY2MmE1MTgtNDA5MC00OWQ3LWE1NjQtNjYzY2MzYWRiOTkwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTI5VDEzMTM1NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTZjYmM2NDIxNzczOTMxMDJjMmYxN2VhYWJlZGViOTQ4NzQwMjFkZTg5NTkyOTIwMDc3MDhlODZhOTgxYzMyNTcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.kBe9p0u0bsfiVFsbEn-5Oj8U5DgF9IC4eJv84omdVBY)
> > 
> > 
> > actually my goal was to keep it in the right side so that it looks organised , that was the idea behind my code update , i am sorry if u didnt like it , I just felt it looked organised in the right so suggested with an change of code
> 
> Oh, no worries! I understand your intention to keep it organized, but I personally don't prefer the right-aligned change.

okay bro , thank you , i hope i can contribute in this project , if there are any issues related to frontend please ping me up , i am willing to help

2024-11-29 14:00 UTC, itz-rj-here commented
> > > > it is not centered ![image](https://private-user-images.githubusercontent.com/60751338/391095129-332370a5-7244-4ce3-a760-5eecb4b2f5f4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzI4ODYzMzQsIm5iZiI6MTczMjg4NjAzNCwicGF0aCI6Ii82MDc1MTMzOC8zOTEwOTUxMjktMzMyMzcwYTUtNzI0NC00Y2UzLWE3NjAtNWVlY2I0YjJmNWY0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTI5VDEzMTM1NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTY5NjU3NDVmMzY2ZGYxMDIxYjdmYjhmNDNiOTE2NWM1MDM1NjA4OGY2N2Q4M2M0YjFlYmVkNGQ3NDNmMmJlMDEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.JD04PpSJk7hZ92JmjngSVDe0H_Vod9WoUJx2ZI0aUmc) ![image](https://private-user-images.githubusercontent.com/60751338/391095140-ff62a518-4090-49d7-a564-663cc3adb990.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzI4ODYzMzQsIm5iZiI6MTczMjg4NjAzNCwicGF0aCI6Ii82MDc1MTMzOC8zOTEwOTUxNDAtZmY2MmE1MTgtNDA5MC00OWQ3LWE1NjQtNjYzY2MzYWRiOTkwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTI5VDEzMTM1NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTZjYmM2NDIxNzczOTMxMDJjMmYxN2VhYWJlZGViOTQ4NzQwMjFkZTg5NTkyOTIwMDc3MDhlODZhOTgxYzMyNTcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.kBe9p0u0bsfiVFsbEn-5Oj8U5DgF9IC4eJv84omdVBY)
> > > 
> > > 
> > > actually my goal was to keep it in the right side so that it looks organised , that was the idea behind my code update , i am sorry if u didnt like it , I just felt it looked organised in the right so suggested with an change of code
> > 
> > 
> > Oh, no worries! I understand your intention to keep it organized, but I personally don't prefer the right-aligned change.
> 
> okay bro , thank you , i hope i can contribute in this project , if there are any issues related to frontend please ping me up , i am willing to help

Just make the shortcuts stay centered and resolve the conflicts.

2024-11-29 14:10 UTC, XengShi commented
@sohan10012 
Thank you for your efforts and contributions; they are greatly appreciated.

Your idea of aligning the shortcut position with the search bar section is quite creative, but I believe it works best when there are only a few shortcuts.

For contributing to the project:
When expanding the AI tools on smaller displays, the layout (Ai tools shortcuts) extends horizontally instead of wrapping to the next line, which affects usability.
Fix it if you can!

Happy Coding!

2024-11-29 15:33 UTC, sohan10012 commented
https://github.com/user-attachments/assets/4e0238ec-5e69-4e1e-8785-7958a5cc0b17

does this work ?? i mean when the tools wrap up they get overlapped on the above tools , vivibility becomes quite bad and also difficult

2024-11-29 15:51 UTC, itz-rj-here commented
> 
> https://github.com/user-attachments/assets/4e0238ec-5e69-4e1e-8785-7958a5cc0b17
> 
> does this work ?? i mean when the tools wrap up they get overlapped on the above tools , vivibility becomes quite bad and also difficult 

I don't think someone will use portrait monitor for the extention 😄

2024-11-29 15:59 UTC, sohan10012 commented
so should i push ?? if u have any tips u give me , i will try implementing it
like adding a glassmorphism so something ...

2024-11-29 15:59 UTC, prem-k-r commented
Btw current responsiveness:

https://github.com/user-attachments/assets/0a4ae8cc-7ef1-4ee9-88f6-aa9cce833967

2024-11-29 16:00 UTC, prem-k-r commented
> so should i push ?? if u have any tips u give me , i will try implementing it like adding a glassmorphism so something ...

glassmorphism .. maybe not
rest let's wait for XengShi

2024-11-29 16:03 UTC, sohan10012 commented
https://github.com/user-attachments/assets/612d98ea-1137-4621-b517-2634f9b5df9f

this is how it looks right now, 

yeah okay i can wait✌️

2024-11-29 16:05 UTC, prem-k-r commented
> Screen.Recording.2024-11-29.213217.mp4 
> this is how it looks right now,
> 
> yeah okay i can wait✌️

seems fine, please push it

2024-11-29 16:07 UTC, sohan10012 commented
Pushed it

2024-11-29 16:08 UTC, prem-k-r commented
> Btw current responsiveness:
> 
>  responsiveness.shortcuts.mp4

can we fix postion of shortcuts such that it dont go above search with and all

2024-11-29 16:09 UTC, sohan10012 commented
i didnt get sorry, can u explain ?

2024-11-29 16:15 UTC, prem-k-r commented
> Btw current responsiveness:
> 
>  responsiveness.shortcuts.mp4

see responsiveness of shortcuts in this video, it went on top of search engines

2024-11-29 16:17 UTC, sohan10012 commented
do u want the shortcuts section to be always sticky at the bottom ??

2024-11-29 16:19 UTC, prem-k-r commented
It is showing this branch has conflicts to me. XengShi prettified code recently and you did too, probably it's causing conflits.
Maybe replicate the changes in copy of current main

2024-11-29 16:21 UTC, sohan10012 commented
i reverted all the changes i did , i mean all about the shortcut section .

2024-11-29 16:22 UTC, prem-k-r commented
> do u want the shortcuts section to be always sticky at the bottom ??

no, not fixed position wrt screen. but below search with, search engines.. shortcuts are displayed in front of them.. I want them to be below

2024-11-29 16:24 UTC, prem-k-r commented
> i reverted all the changes i did , i mean all about the shortcut section .

yeah, your code is not affecting them

2024-11-29 16:25 UTC, sohan10012 commented
yeah i will try implementing that if i can , but i need some time for that

2024-11-29 16:26 UTC, prem-k-r commented
appreciate it, no hurry

2024-11-29 16:28 UTC, sohan10012 commented
cool then ☺️

2024-11-29 16:41 UTC, prem-k-r commented
> It is showing this branch has conflicts to me. XengShi prettified code recently and you did too, probably it's causing conflits. Maybe replicate the changes in new branch with copy of current main

@sohan10012 please fix conflicts

2024-11-29 17:32 UTC, prem-k-r requested changes
![image](https://github.com/user-attachments/assets/94e934bf-e58d-488c-ab5e-272d4ec32088)
1. when page refreshed or new tab opened AI-Tool menu is still open, with low opacity and decreased size.
2. in general when ai tool closed, left side circular area of ai tool, can see the closing shortcuts to hide, reverting back border-radius fix this one 
3. and for long screen, during closing AI tools by clicking again. transition is not smooth, it hesitate for .5 sec then fall down lol

2024-11-29 17:39 UTC, sohan10012 commented
sure , i will fix that

2024-11-30 13:23 UTC, sohan10012 commented
> ![image](https://private-user-images.githubusercontent.com/60751338/391156767-94e934bf-e58d-488c-ab5e-272d4ec32088.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzI5NjY3MTIsIm5iZiI6MTczMjk2NjQxMiwicGF0aCI6Ii82MDc1MTMzOC8zOTExNTY3NjctOTRlOTM0YmYtZTU4ZC00ODhjLWFiNWUtMjcyZDRlYzMyMDg4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTMwVDExMzMzMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTJhMDAyODA1NTE5NWU2NTdkZGIzNDY3ZDQ4NDk1Mzg3OWFhN2Y0YjI4MTBlNjgwYmU3YzMwODViYzIzNTgzNTMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.wtxS_iv0bLGIc-XitS09PpqjA0_7Ts1eZF1rHzuDM0g)
> 
> 1. when page refreshed or new tab opened AI-Tool menu is still open, with low opacity and decreased size.
> 2. in general when ai tool closed, left side circular area of ai tool, can see the closing shortcuts to hide, reverting back border-radius fix this one
> 3. and for potrait screen, during closing AI tools by clicking again. transition is not smooth, it hesitate for .5 sec then fall down lol

i fixed all the three issue and there is only 1 error which i am facing which is while aicontent box is closing the content fox isnt tanslating itself away from the left side , it is working while its opening but not while its closing , other than that i tried to fix rest of the issues

2024-11-30 13:26 UTC, sohan10012 commented
https://github.com/user-attachments/assets/45a58e80-7554-4884-9187-c6cf7a40208a

this is the screen recording , if you are okay i will push the file , the thing i feel is there some other css rule which is affecting it but i am unable to figure it out 😭😭

2024-11-30 13:48 UTC, sohan10012 commented
https://github.com/user-attachments/assets/294ee23c-5e49-4806-a892-621dc06cd762

just   a different animation style

2024-11-30 14:25 UTC, sohan10012 commented
https://github.com/user-attachments/assets/72007324-2d0d-40f4-8440-e9ab80b44944

final screen recording

2024-12-01 08:05 UTC, itz-rj-here requested changes
Conflicts

2024-12-01 10:02 UTC, prem-k-r commented
>Conflicts... Maybe replicate the changes in new branch with copy of current main

..

2024-12-01 10:15 UTC, itz-rj-here commented
> > Conflicts... Maybe replicate the changes in new branch with copy of current main
> 
> ..

Yup it's a better idea.

2024-12-01 16:38 UTC, sohan10012 commented
ok sure , i will do it tomorrow

2024-12-01 17:38 UTC, sohan10012 commented
Done with the conflicts 👍, please check once

2024-12-02 08:17 UTC, XengShi commented
![image](https://github.com/user-attachments/assets/2b5ebdca-45f5-4b43-acc9-f96295fa4741)

On the first load or after reloading the page, the "AI Tools" section occupies extra space, overlapping the shortcut icons and making them unclickable.

And, the animations feel quite slow,

2024-12-02 13:54 UTC, prem-k-r requested changes

2024-12-02 13:54 UTC, prem-k-r commented on style.css
> +    border-radius: 10px;
border radius I mean

2024-12-02 14:34 UTC, sohan10012 commented
Uploading Screen Recording 2024-12-02 200420.mp4…

screen recording of the changes

2024-12-02 14:36 UTC, sohan10012 commented
https://github.com/user-attachments/assets/3a0cf49b-35f8-42e0-beb1-137a72e982d4

screen record of the ai tools

2024-12-02 14:43 UTC, prem-k-r commented
![image](https://github.com/user-attachments/assets/e43986fb-68ba-4ac0-90d7-6f79c4f98ece)

2024-12-02 14:50 UTC, prem-k-r submitted a review, later dismissed

2024-12-02 15:34 UTC, itz-rj-here approved these changes

2024-12-04 09:12 UTC, sohan10012 commented
Hi @prem-k-r  @itz-rj-here , could you please provide an update on my PR? Thank you!

2024-12-04 09:14 UTC, prem-k-r commented
Seems good to merge.. 
@XengShi can test, give suggestions if any, and merge it

2024-12-04 09:18 UTC, itz-rj-here submitted a review, later dismissed
The code looks ok for me

2024-12-05 16:00 UTC, XengShi commented
@sohan10012 
Everything is looking fine but 'AI Tools' button shouldn't change its position:

https://github.com/user-attachments/assets/17e28c8f-c2b0-484b-9993-27fcb3b24f83

2024-12-06 05:27 UTC, sohan10012 commented
I will try to fix that 👍🏻

2024-12-06 06:21 UTC, sohan10012 commented
> @sohan10012 
> Everything is looking fine but 'AI Tools' button shouldn't change its position:
> 
> https://github.com/user-attachments/assets/17e28c8f-c2b0-484b-9993-27fcb3b24f83
> 
> 
> 
> 

Sorry I am unable to do that , the height of the page isn't getting altered to fix the overflow of the container .

2024-12-07 07:15 UTC, XengShi commented
> > @sohan10012 
> > Everything is looking fine but 'AI Tools' button shouldn't change its position:
> > 
> > https://github.com/user-attachments/assets/17e28c8f-c2b0-484b-9993-27fcb3b24f83
> > 
> > 
> > 
> > 
> 
> Sorry I am unable to do that , the height of the page isn't getting altered to fix the overflow of the container . 

Checkout [https://github.com/XengShi/materialYouNewTab/tree/chrome-v2.5](this) 

I have added a scrolling effect instead of wrapping

2024-12-08 07:12 UTC, sohan10012 commented
Sure I will look into it

2025-01-21 04:59 UTC, prem-k-r commented
Thank you very much for your efforts and hardwork. 
Sorry :(

2025-01-21 04:59 UTC, closed without merging