Adding Feature/search engine selection
XengShi/materialYouNewTab pull request #257
Opened 2024-12-02 03:07 UTC by princevora

- Added DropDown Support With all the supported search engine In the materialYouNewTab.
- The DropDown Supports all the colors which are currently active as it has used the pre written css classes and styles.
- The Feature has short code and i have focused on clean and readable code
- The Dropdown stores the selected search engine in the local storage same as the radio button does.
- It will automatically detect and select the appropriate search engine from local storage when ever the new tab is been created.

> ###  I have Shared A few Screen Shots Of my work below.

> ### Dark theme

![image](https://github.com/user-attachments/assets/00530277-ad00-4fc4-b883-6aaa949505b4)

> ### Light Theme

![image](https://github.com/user-attachments/assets/12ed1161-5e1a-4cc3-be75-a975acc7c167)

> ### Brave New Tab interface

![image](https://github.com/user-attachments/assets/9d99fef2-5da7-45ad-b6d6-f961281a9983)

> ### Option For Enabling Or Disabling the shortcut search
![image](https://github.com/user-attachments/assets/c643d956-0515-4b25-af30-0416e7e33fb6)

2024-12-02 03:08 UTC, princevora commented
This Fork Has all the recent code and added a feature to enable or disable the shortcut search.

2024-12-02 07:23 UTC, itz-rj-here commented
if you don't have any problem can you place the type here... Text little bit of right side please...

2024-12-02 07:28 UTC, prem-k-r commented
> 
> > ### Option For Enabling Or Disabling the shortcut search
> 
> ![image](https://private-user-images.githubusercontent.com/122656064/391397510-c643d956-0515-4b25-af30-0416e7e33fb6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzMxMjQ1NzIsIm5iZiI6MTczMzEyNDI3MiwicGF0aCI6Ii8xMjI2NTYwNjQvMzkxMzk3NTEwLWM2NDNkOTU2LTA1MTUtNGIyNS1hZjMwLTA0MTZlN2UzM2ZiNi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjAyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIwMlQwNzI0MzJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lM2U3Y2QwYTE5NzYyZGNkNWJjN2E5MjIxZjY2OWUzNDkzZGI2ZDExNTI2MTQzNWM0ZTJlODEyN2QxNTg1MmJhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.kjrzUO1hYIpuL5YeOFm76_JUHXqpYdJayOUda0acRwk)

Great. Please rearrange it before search suggestions toggle.. proxy and search suggestions are related.. so adding in between is not good

2024-12-02 07:58 UTC, XengShi commented
Your code works well overall, but I noticed a couple of minor issues that could be improved:

https://github.com/user-attachments/assets/a3c99b1c-7cc0-4cd7-98e1-6e32936a929d


**Upon reloading the page, the radio button momentarily appears for a fraction of a second before disappearing.**



https://github.com/user-attachments/assets/b9673e21-72b9-4260-8f7b-1c5fab204b5a


**On the first load of the extension, both options—'Search with' and 'Dropdown selection'—are enabled simultaneously, whereas initially, only the 'Search with' option should be active.**

2024-12-02 08:13 UTC, itz-rj-here commented
> Your code works well overall, but I noticed a couple of minor issues that could be improved:
> 
>  Screencast.From.2024-12-02.13-16-05.mp4 
> **Upon reloading the page, the radio button momentarily appears for a fraction of a second before disappearing.**
> 
>  Screencast.From.2024-12-02.13-17-37.mp4 
> **On the first load of the extension, both options—'Search with' and 'Dropdown selection'—are enabled simultaneously, whereas initially, only the 'Search with' option should be active.**

i can fell that the position of the icon's doesn't looks good.
Need more perfection :)

2024-12-02 11:37 UTC, prem-k-r commented
I recently learn that we can use `<use>` element, it allows us to reference an SVG symbol.. so can avoid svg code writing again if using same svg.. making it cleaner too


example:
```
<!-- Define the SVG symbol in the <defs> block -->
<svg style="display: none;">
  <symbol id="custom-icon" viewBox="0 0 28 28">
    <rect class="accentColor" fill="#FF000F" height="28" rx="14" width="28" />
    <path class="darkIconForDarkTheme"
          d="M22.9991 13.1645C22.9954 13.0734 22.9651 12.9855 22.9119 12.9118C22.8588 12.8382 22.7853 12.7822 22.7007 12.751L13.8694 9.98251C13.7046 9.93107 13.6294 10.0197 13.7018 10.1788L15.3442 13.8304C15.4167 13.9904 15.604 14.18 15.7602 14.2524L18.0135 15.2966C18.1697 15.369 18.1735 15.4957 18.021 15.5776L8.40754 20.7525C8.25601 20.8345 8.23624 20.8059 8.36425 20.6887L12.0575 17.3219C12.197 17.1796 12.28 16.9905 12.291 16.7904L12.2947 6.58526C12.291 6.49394 12.2606 6.40578 12.2073 6.33199C12.154 6.25821 12.0803 6.20212 11.9954 6.17084L8.2993 5.01334C8.13459 4.9619 8 5.06383 8 5.24008V20.7211C8 20.8974 8.11483 21.1241 8.25601 21.2251L12.0114 23.9183C12.1526 24.0193 12.3879 24.0279 12.5357 23.9373L22.7308 17.723C22.8093 17.6688 22.8744 17.597 22.921 17.5133C22.9677 17.4295 22.9947 17.336 23 17.24V13.1645H22.9991Z"
          fill="white" />
  </symbol>
</svg>

<!-- Reuse the SVG with <use> -->
<svg class="icon" width="28" height="28">
  <use href="#custom-icon"></use>
</svg>

<svg class="icon-large" width="56" height="56">
  <use href="#custom-icon"></use>
</svg>
```

2024-12-02 13:20 UTC, prem-k-r commented on index.html
> +            <div class="searchWithCont" style="visibility: hidden;;" id="search-with-container">
extra semi-colon

2024-12-02 13:30 UTC, prem-k-r commented
Is it just me?
getting error
![image](https://github.com/user-attachments/assets/64f453f2-5072-4fab-9ac3-2c5167e94644)
![image](https://github.com/user-attachments/assets/57f8c1c4-a818-422f-8ba1-e6d16c40aa3a)
![image](https://github.com/user-attachments/assets/a3891719-c129-4444-9f1d-110960f883c4)

2024-12-02 13:47 UTC, prem-k-r commented
Also I suggest if toggle is on then shift `rightdiv` a little down

2024-12-02 13:59 UTC, princevora commented
> Is it giving error lol ![image](https://private-user-images.githubusercontent.com/60751338/391561783-64f453f2-5072-4fab-9ac3-2c5167e94644.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzMxNDgxNTUsIm5iZiI6MTczMzE0Nzg1NSwicGF0aCI6Ii82MDc1MTMzOC8zOTE1NjE3ODMtNjRmNDUzZjItNTA3Mi00ZmFiLTlhYzMtMmM1MTY3ZTk0NjQ0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjAyVDEzNTczNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTdkYmI4ZjRlZGQ4OTkyMmM0YmFiNmIzMTM0NDAzNTQ0YzMzNmQyNGM2NDM1NjE1ZDBlMGFkZDA2NjQzOThmYjImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.zCbzuEyg4rFpltK7SKEuPrpRRfpcV0L-0Nq4v1ZfZFI) ![image](https://private-user-images.githubusercontent.com/60751338/391561797-57f8c1c4-a818-422f-8ba1-e6d16c40aa3a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzMxNDgxNTUsIm5iZiI6MTczMzE0Nzg1NSwicGF0aCI6Ii82MDc1MTMzOC8zOTE1NjE3OTctNTdmOGMxYzQtYTgxOC00MjJmLThiYTEtZTZkMTZjNDBhYTNhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjAyVDEzNTczNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWFmZWYxYWUwYmU5MGUyZjQ1NmEyYjg1ZTdlZGQ1MmFlODI2NjgxNGE4ZDZhZjgxMjUwNDI4NWYxNWUyYzM1OTkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.h-U1CtBVQ4RvsyColCn8VC5z0DhCl6IgweYKtYbeVFk) ![image](https://private-user-images.githubusercontent.com/60751338/391561773-a3891719-c129-4444-9f1d-110960f883c4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzMxNDgxNTUsIm5iZiI6MTczMzE0Nzg1NSwicGF0aCI6Ii82MDc1MTMzOC8zOTE1NjE3NzMtYTM4OTE3MTktYzEyOS00NDQ0LTlmMWQtMTEwOTYwZjg4M2M0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjAyVDEzNTczNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQxOWUyYjY0YTliNDI0OGFmNDM3MzA1MmY4YjY4ZTJkNTdkNzAwZDAyMWYzZDcwNDg2M2UzMjk5MmFiNTFiMDImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.Qa1EsYBUafOSzeNi_TPTGaGstsoHjTQeDZ9opzhgzDg)

its all good from my side bro
![image](https://github.com/user-attachments/assets/3c046aa8-ae55-40ac-8c0e-6f98c473f723)

Your page doesnt have the container "Search With"

2024-12-02 14:00 UTC, princevora commented
I have updated your suggestions you told me

2024-12-02 14:01 UTC, prem-k-r commented
> > Is it giving error lol
> 
> its all good from my side bro ![image](https://private-user-images.githubusercontent.com/122656064/391571007-3c046aa8-ae55-40ac-8c0e-6f98c473f723.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzMxNDgzMDksIm5iZiI6MTczMzE0ODAwOSwicGF0aCI6Ii8xMjI2NTYwNjQvMzkxNTcxMDA3LTNjMDQ2YWE4LWFlNTUtNDBhYy04YzBlLTZmOThjNDczZjcyMy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjAyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIwMlQxNDAwMDlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hZDUwMWVmNTNlNGE2NjQwNjY4ZDA1OTAwNjFlODAwMzM5OGRiZmNhYTkyNmYxMWJjZTE5N2Q4YmY4MzRhOTJmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.oNI1lFQOWtoCprG_QYomUpll2OJyiCQYsatD1yyTVhw)
> 
> Your page doesnt have the container "Search With"

that was coz of semi color, it's resolved

2024-12-02 14:02 UTC, princevora commented
> > > Is it giving error lol
> > 
> > 
> > its all good from my side bro ![image](https://private-user-images.githubusercontent.com/122656064/391571007-3c046aa8-
> that was coz of semi color, it's resolved

Ohh i see

2024-12-02 14:03 UTC, princevora commented
I have added the default as search with option

2024-12-02 14:21 UTC, prem-k-r approved these changes

2024-12-02 14:28 UTC, prem-k-r requested changes
ah sorry, 
toggle on -> after reloading page, toggle got off
state not saving

2024-12-02 14:38 UTC, princevora commented
> ah sorry, toggle on -> after reloading page, toggle got off state not saving

It was calling the function before initializing the html values, its fixed now

2024-12-02 14:47 UTC, prem-k-r approved these changes
great

2024-12-05 17:24 UTC, merged

2024-12-05 19:00 UTC, prem-k-r commented
I just realised a case.. search engine dropdown menu should hide automatically when resultBox from search suggestions pops up

2024-12-06 03:43 UTC, princevora commented
> I just realised a case.. search engine dropdown menu should hide automatically when resultBox from search suggestions pops up

done