New language translation: Urdu
XengShi/materialYouNewTab pull request #329
Opened 2024-12-17 08:28 UTC by asfand-dev

## Description
Added Urdu language support and localization

## Related Issues
- Issue #<issue_number>

## Checklist
- [x] I have read and followed the [Contributing Guidelines](../CONTRIBUTING.md).
- [x] I have added necessary tests.
- [x] The project builds and runs without issues.

2024-12-17 08:29 UTC, asfand-dev commented
Here are the screenshots:

<img width="1448" alt="Screenshot 2024-12-17 at 9 20 30 AM" src="https://github.com/user-attachments/assets/0e272b01-d69a-44cf-8963-c685fd3d3d79" />

<img width="1448" alt="Screenshot 2024-12-17 at 9 20 37 AM" src="https://github.com/user-attachments/assets/c77d4ec6-c456-409e-8c65-bef30eae5ce8" />

2024-12-17 08:34 UTC, itz-rj-here commented
@asfand-dev I appreciate your thoughtful adjustments. It would be very appreciated if you could include the language detail in the readme file too. Thanks.
![image](https://github.com/user-attachments/assets/ec5c975e-1f24-4edb-bcb6-e665e6284779)

2024-12-17 08:35 UTC, itz-rj-here requested changes
Add the language name in the readme file too.

2024-12-17 09:13 UTC, prem-k-r commented
> Here are the screenshots:
> 
> <img alt="Screenshot 2024-12-17 at 9 20 30 AM" width="1448" src="https://private-user-images.githubusercontent.com/71268133/396418302-0e272b01-d69a-44cf-8963-c685fd3d3d79.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQ0MjY0MTAsIm5iZiI6MTczNDQyNjExMCwicGF0aCI6Ii83MTI2ODEzMy8zOTY0MTgzMDItMGUyNzJiMDEtZDY5YS00NGNmLTg5NjMtYzY4NWZkM2QzZDc5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjE3VDA5MDE1MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTFhNDhjMDFjMzk2ZTczYzg1ODA1MDhiODc3YjMwNTJiZGYxZDgwMTJlYzBmMjcwMWY2ZTk3Njg0MmEwNWRmYjcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0._wVrY8KSjcqIQf_-vt9YIqHWwNmrMUqtGcHHCjngjb8"> <img alt="Screenshot 2024-12-17 at 9 20 37 AM" width="1448" src="https://private-user-images.githubusercontent.com/71268133/396418351-c77d4ec6-c456-409e-8c65-bef30eae5ce8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQ0MjY0MTAsIm5iZiI6MTczNDQyNjExMCwicGF0aCI6Ii83MTI2ODEzMy8zOTY0MTgzNTEtYzc3ZDRlYzYtYzQ1Ni00MDllLThjNjUtYmVmMzBlYWU1Y2U4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjE3VDA5MDE1MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTJmMTFkY2E1ZmJiN2EzMzFiYzBjM2U3M2IwNzEzMDg5NWNiMTU2MjI3YzMyZTAwZjVlMzk0OTZlMTBiNjI2YjImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.nVZeREACgRMjvmU1kjHm_se8NELxlnMSZOZ-AAWHIi8">

can you please provide ss for digital clock too

there seems some issue with Feels-like unit.. 

btw for decimal separator isn't dot or ۔ (Arabic decimal separator) is used? I could be wrong

2024-12-17 09:50 UTC, itz-rj-here commented
> > Here are the screenshots:
> > <img alt="Screenshot 2024-12-17 at 9 20 30 AM" width="1448" src="https://private-user-images.githubusercontent.com/71268133/396418302-0e272b01-d69a-44cf-8963-c685fd3d3d79.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQ0MjY0MTAsIm5iZiI6MTczNDQyNjExMCwicGF0aCI6Ii83MTI2ODEzMy8zOTY0MTgzMDItMGUyNzJiMDEtZDY5YS00NGNmLTg5NjMtYzY4NWZkM2QzZDc5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjE3VDA5MDE1MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTFhNDhjMDFjMzk2ZTczYzg1ODA1MDhiODc3YjMwNTJiZGYxZDgwMTJlYzBmMjcwMWY2ZTk3Njg0MmEwNWRmYjcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0._wVrY8KSjcqIQf_-vt9YIqHWwNmrMUqtGcHHCjngjb8"> <img alt="Screenshot 2024-12-17 at 9 20 37 AM" width="1448" src="https://private-user-images.githubusercontent.com/71268133/396418351-c77d4ec6-c456-409e-8c65-bef30eae5ce8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQ0MjY0MTAsIm5iZiI6MTczNDQyNjExMCwicGF0aCI6Ii83MTI2ODEzMy8zOTY0MTgzNTEtYzc3ZDRlYzYtYzQ1Ni00MDllLThjNjUtYmVmMzBlYWU1Y2U4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjE3VDA5MDE1MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTJmMTFkY2E1ZmJiN2EzMzFiYzBjM2U3M2IwNzEzMDg5NWNiMTU2MjI3YzMyZTAwZjVlMzk0OTZlMTBiNjI2YjImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.nVZeREACgRMjvmU1kjHm_se8NELxlnMSZOZ-AAWHIi8">
> 
> can you please provide ss for digital clock too
> 
> you can add translation for google apps and to-do list too there seems some issue with Feels-like unit..
> 
> btw for decimal separator isn't dot or ۔ (Arabic decimal separator) is used? I could be wrong

Simply we write everything from left to right. But in arabic or urdu, we have to write from right to left. thats all others are the same as usual.

2024-12-17 09:53 UTC, prem-k-r commented
I know bro

2024-12-17 09:55 UTC, itz-rj-here commented
> I know bro

Good.

2024-12-17 09:58 UTC, prem-k-r commented
> > I know bro
> 
> Good.

Humidity is like `76 ytidimuH %`
It probably should be `76% ytidimuH`
Similarly for feels like

2024-12-17 10:00 UTC, itz-rj-here commented
> > > I know bro
> > 
> > 
> > Good.
> 
> Humidity is like `76 ytidimuH%` It probably should be `76% ytidimuH` Similarly for feels like

Uhhh. I accidently forgot about the numberings in arabic bruh

2024-12-17 10:01 UTC, XengShi commented
> > > I know bro
> > 
> > Good.
> 
> Humidity is like `76 ytidimuH%`
> It probably should be `76% ytidimuH`
> Similarly for feels like

Bro literally wrote urdu using english letters
'ytidimuH' 🙃

2024-12-18 06:20 UTC, prem-k-r commented on languages.js
> +        "googleAppsMenuText": "Google Apps",
please translate/transliterate this too

2024-12-18 06:20 UTC, prem-k-r commented on languages.js
> +        "todoListText": "To Do List",
please translate/transliterate this too

2024-12-18 06:20 UTC, prem-k-r commented on languages.js
> +        "todoListHover": "ToDo List",
please translate/transliterate these too

2024-12-18 06:21 UTC, prem-k-r commented on languages.js
> +    ur: '450px',
not needed, please remove

2024-12-18 06:23 UTC, prem-k-r commented on languages.js
> +    const specialDecimalLanguages = ['cs', 'it', 'pt', 'ru', 'tr', 'vi', 'uz', 'es', 'ko', 'idn', 'fr', 'ur']; // Add more languages here as needed
please confirm for decimal separator (28.6), comma is used (=28,6)
isn't dot or ۔ (Arabic decimal separator) is used?

2024-12-18 06:24 UTC, prem-k-r commented on script.js
> +            ur: `${dayName}, ${dayOfMonth} ${monthName}`,
urdu version comma `،` will be used, no?

2024-12-18 06:25 UTC, prem-k-r commented on script.js
> +        ur: `${dayName}, ${dayOfMonth}`,
also here `،`

2024-12-18 06:27 UTC, prem-k-r requested changes
For `humidity` and `feels like` we have to change in code. 
See if you can add else we will do it.. also adding Urdu in `readme`

2024-12-18 06:30 UTC, prem-k-r commented
@asfand-dev

2024-12-18 08:16 UTC, XengShi commented
Thank you for the contribution! Could you please consider changing the font for Urdu? You can use fonts from [fonts.google.com](https://fonts.google.com/) as the current one looks a bit unappealing.

And, please change ` محسوس 23.2°C` to ` 23.2°C محسوس`  so that the temperature appears before the unit.
and also `12 گھنٹے کا فارمیٹ` to   `  گھنٹے کا فارمیٹ‎ 12 `


![Screenshot From 2024-12-18 13-20-56](https://github.com/user-attachments/assets/3604e16b-8e89-4fcb-915a-76956d3a1685)
![Screenshot From 2024-12-18 13-20-42](https://github.com/user-attachments/assets/49b74ef7-fd9c-4a8c-888a-02d4f3cb4064)


Example of new font:
![Screenshot From 2024-12-18 13-28-18](https://github.com/user-attachments/assets/dcd18f9c-fca9-4109-9f17-b8562775a966)
![Screenshot From 2024-12-18 13-27-52](https://github.com/user-attachments/assets/664418a5-8fc6-4446-a9dd-3e22f6ba0ee9)

2024-12-18 08:30 UTC, prem-k-r commented
for me, it is showing in this font
![image](https://github.com/user-attachments/assets/cd39a629-ada5-4c5a-946c-57cf2c2bd066)

2024-12-18 08:33 UTC, XengShi commented
> for me, it is showing in this font
> ![image](https://github.com/user-attachments/assets/cd39a629-ada5-4c5a-946c-57cf2c2bd066)
> 

I guess it is using the font from the system, and I have the ugly one

2024-12-21 15:38 UTC, prem-k-r commented
hi @asfand-dev, please fix conflicts

2025-02-22 16:13 UTC, prem-k-r commented
moved to #548

2025-02-22 16:13 UTC, closed without merging