add Azerbaijani language
XengShi/materialYouNewTab pull request #348
Opened 2024-12-19 21:02 UTC by hasanbakhtiar

## Description
I added the Azerbaijani language in language.js. I also gave it as an option in index.html, I tested it, there were no problems, it worked normally. I registered myself in the readme.md file.

## Related Issues
- Issue #<issue_number>

## Checklist
- [ ] I have read and followed the [Contributing Guidelines](../CONTRIBUTING.md).
- [ ] I have added necessary tests.
- [ ] The project builds and runs without issues.

2024-12-19 21:02 UTC, hasanbakhtiar commented
I added the Azerbaijani language in language.js. I also gave it as an option in index.html, I tested it, there were no problems, it worked normally. I registered myself in the readme.md file.

2024-12-20 00:40 UTC, itz-rj-here commented
@prem-k-r

2024-12-20 06:14 UTC, prem-k-r commented on README.md
> +## 🌐 Currently Supported Languages (18)
line 27, please update the link too, 17 to 18

2024-12-20 06:15 UTC, prem-k-r commented on README.md
> +| <img src='https://flagcdn.com/az.svg' width=20> &nbsp; **Azerbaijani** - Azərbaycanca    |  az   | [Hasan Bakhtiar](https://github.com/hasanbakhtiar/)                                   |
You can place it right after english

2024-12-20 06:16 UTC, prem-k-r commented on index.html
> +                            <option value="az">Azərbaycanca (Azerbaijani)</option>
please rearrange, place it between english and bangla.

2024-12-20 06:18 UTC, prem-k-r commented on languages.js
> +    // Azerbaijani
You could have placed it after french.. why put it in the middle
well technically no issue, but still

2024-12-20 06:21 UTC, prem-k-r commented on languages.js
> +        },
It seems incomplete to me.. A lot of strings are untranslated.
It would be good if you translate rest of the elements too.

2024-12-20 06:23 UTC, prem-k-r commented on languages.js
> +        "metaAI": "Meta AI",
line 1945: please include az in the list if comma is used as the decimal separator instead of a dot

2024-12-20 06:26 UTC, prem-k-r requested changes
Also in script.js, search for `fr:` , you will find two results. Please add date localisation for az if needed. For both analog and digital clock.

2024-12-20 06:28 UTC, prem-k-r commented
@hasanbakhtiar Great work!
please look at the suggestions

2024-12-20 13:58 UTC, XengShi commented
@prem-k-r  is this ready for merge?

2024-12-20 14:02 UTC, prem-k-r commented
I don't think so

2024-12-20 15:32 UTC, itz-rj-here commented
> @prem-k-r  is this ready for merge?
> 

Nope

2024-12-21 06:29 UTC, hasanbakhtiar commented on index.html
> +                            <option value="az">Azərbaycanca (Azerbaijani)</option>
Hi, sure, this is ready.

2024-12-21 06:29 UTC, hasanbakhtiar commented on README.md
> +| <img src='https://flagcdn.com/az.svg' width=20> &nbsp; **Azerbaijani** - Azərbaycanca    |  az   | [Hasan Bakhtiar](https://github.com/hasanbakhtiar/)                                   |
this is ready.

2024-12-21 06:31 UTC, hasanbakhtiar commented on README.md
> +## 🌐 Currently Supported Languages (18)
These are now ready

2024-12-21 06:32 UTC, hasanbakhtiar commented on languages.js
> +    // Azerbaijani
I put this after English

2024-12-21 06:33 UTC, prem-k-r commented on README.md
> +| <img src='https://flagcdn.com/az.svg' width=20> &nbsp; **Azerbaijani** - Azərbaycanca    |  az   | [Hasan Bakhtiar](https://github.com/hasanbakhtiar/)                                   |
Deleted some unnecessary things.. it broke the table. Please check

2024-12-21 06:33 UTC, hasanbakhtiar commented on languages.js
> +        },
I couldn't find exactly where it was when I looked, but if you tell me I can fix it.

2024-12-21 06:34 UTC, prem-k-r commented on README.md
> +| <img src='https://flagcdn.com/az.svg' width=20> &nbsp; **Azerbaijani** - Azərbaycanca    |  az   | [Hasan Bakhtiar](https://github.com/hasanbakhtiar/)                                   |
![IMG_20241221_120350](https://github.com/user-attachments/assets/519b2e32-5d50-406f-b0db-c710c17346ca)

2024-12-21 06:36 UTC, prem-k-r commented on languages.js
> +    // Azerbaijani
Not this one.. alphabetically only in html and readme.. (visible to others)
Here you can place it after last translated language- French

2024-12-21 06:47 UTC, hasanbakhtiar commented on languages.js
> +    // Azerbaijani
I solved it.

2024-12-21 06:47 UTC, hasanbakhtiar commented on README.md
> +| <img src='https://flagcdn.com/az.svg' width=20> &nbsp; **Azerbaijani** - Azərbaycanca    |  az   | [Hasan Bakhtiar](https://github.com/hasanbakhtiar/)                                   |
I solved it.

2024-12-21 06:50 UTC, hasanbakhtiar commented on languages.js
> +        },
I added

2024-12-21 06:53 UTC, prem-k-r commented
@hasanbakhtiar Thanks!

2024-12-21 06:53 UTC, prem-k-r approved these changes

2024-12-21 06:53 UTC, prem-k-r commented
Seems ok, please review and merge @XengShi

2024-12-21 06:54 UTC, hasanbakhtiar commented on languages.js
> +        "metaAI": "Meta AI",
Ready

2024-12-21 06:56 UTC, hasanbakhtiar commented
Thank you very much for reporting the problems. I am very happy to contribute to this project.

2024-12-21 06:59 UTC, prem-k-r commented
Appreciate the work..
Can you confirm the date formats are localized and align with Azerbaijani conventions

2024-12-21 07:05 UTC, hasanbakhtiar commented
az: `${dayName.substring(0, 3)}, ${dayOfMonth} ${monthName.substring(0, 3)}`,
in this section?

2024-12-21 07:11 UTC, prem-k-r commented
> az: `${dayName.substring(0, 3)}, ${dayOfMonth} ${monthName.substring(0, 3)}`, in this section?

Yeah, it shows as `Cüm, 21 Dek`
You can tweak it if it's not aligning with convention.

2024-12-21 07:50 UTC, hasanbakhtiar commented
> > az: `${dayName.substring(0, 3)}, ${dayOfMonth} ${monthName.substring(0, 3)}`, in this section?
> 
> Yeah, it shows as `Cüm, 21 Dek` You can tweak it if it's not aligning with convention. If it's already correct then good to go

This is normal, we can continue.

2024-12-21 08:09 UTC, itz-rj-here approved these changes

2024-12-21 15:26 UTC, merged