Introducing New Bookmark System for the Extention
XengShi/materialYouNewTab pull request #349
Opened 2024-12-20 09:14 UTC by itz-rj-here

## Description
This pull request introduces an enhanced bookmark sidebar extension for Chrome, aimed at providing a seamless and intuitive way to manage bookmarks.

This work is still in progress. When it is done, the users who requested for the bookmarks will be mentioned to check this pr. if they liked the bookmark system or they want any more changes to it.

## Related Issues
Closes #234 
Closes #262 
Closes #259 
#316 (Not used to close this issue cause, it also includes for some more improvements and customizations.)

## Checklist
- [ ] I have read and followed the [Contributing Guidelines](../CONTRIBUTING.md).
- [ ] I have added necessary tests.
- [ ] The project builds and runs without issues.

2024-12-20 09:18 UTC, itz-rj-here commented
@XengShi @prem-k-r @Thunder-Blaze 

Requesting to give it a review and give me some suggestions for improvements...

Thanks...

2024-12-20 09:20 UTC, itz-rj-here commented on background.js
Which part?

2024-12-20 09:20 UTC, itz-rj-here commented on background.js
Ohh the bg i got it ok...

2024-12-20 09:21 UTC, itz-rj-here commented on background.js
I still didn't checked this feature on firefox fr

2024-12-20 09:30 UTC, prem-k-r commented on background.js
You can delete the license text though if you want :)

2024-12-20 09:30 UTC, itz-rj-here commented on background.js
I wanted to completely remove it but no use as firefox needed this....

2024-12-20 09:33 UTC, prem-k-r commented
Maybe a toggle? but let's confirm from xengshi first

2024-12-20 09:42 UTC, Thunder-Blaze commented
Nice, have to adjust its color theming and animations, I can do those once this PR gets merged into main

btw see if you can also add a "Add Bookmark" functionality, then it will become a fully fledged bookmark sidebar

2024-12-20 09:47 UTC, Thunder-Blaze commented
lol no not that, Like one which will take input of website to add a bookmark but this is also great as it is without add button

2024-12-20 09:52 UTC, Thunder-Blaze commented
its having some error when I loaded it unpacked in chrome

![image](https://github.com/user-attachments/assets/359e0aa5-d9a7-42e8-895a-f3eb5921e6e1)

2024-12-20 10:07 UTC, itz-rj-here commented
@Thunder-Blaze Can you now check once more. I guess the issue is fixed now.

2024-12-20 10:15 UTC, Thunder-Blaze commented
Yeah it's fixed, no more errors

2024-12-20 18:50 UTC, prem-k-r commented
Awesome work!

Aside from the UI, here are some suggestions for functionality tweaks:
- Unable to open bookmarks without a name.
- Ctrl + Click should open in a new tab.
- For bookmarks with no favicon or an error in fetching it, I see console errors, and sometimes the issue overflows. Location -> Earth.
- Unable to search by website URL.

2024-12-20 18:53 UTC, prem-k-r commented
btw, wouldn’t the left side be better for the bookmarks list?

2024-12-20 18:55 UTC, prem-k-r commented
And is it possible to show Mobile Bookmarks folder too?

2024-12-20 19:04 UTC, prem-k-r commented
some styling are overflowing
like h2 tag
![image](https://github.com/user-attachments/assets/48ac766f-ae64-4b32-b0e2-6fb66f371151)

2024-12-21 02:10 UTC, itz-rj-here commented
> And is it possible to show Mobile Bookmarks folder too?
> 

Idk i only tested it on chrome. On my computer.

2024-12-21 02:11 UTC, itz-rj-here commented
> btw, wouldn’t the left side be better for the bookmarks list?

Idk but i thought it would be nice if we add it to the right. Cause right is always right 😄

2024-12-21 02:11 UTC, itz-rj-here commented
> some styling are overflowing
> like h2 tag
> ![image](https://github.com/user-attachments/assets/48ac766f-ae64-4b32-b0e2-6fb66f371151)
> 

Then what should i do?

2024-12-21 05:09 UTC, Thunder-Blaze commented
@itz-rj-here I think you can use try catch statements to deal with the overflowing issue

I'll fix the styles ig, so you can work on functionality 

Idk about the side, any side is fine tbh, you guys can discuss that:)

2024-12-21 05:21 UTC, prem-k-r commented
> > some styling are overflowing
> > like h2 tag
> > ![image](https://private-user-images.githubusercontent.com/60751338/397838681-48ac766f-ae64-4b32-b0e2-6fb66f371151.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQ3NTg1MzUsIm5iZiI6MTczNDc1ODIzNSwicGF0aCI6Ii82MDc1MTMzOC8zOTc4Mzg2ODEtNDhhYzc2NmYtYWU2NC00YjMyLWIwZTItNmZiNjZmMzcxMTUxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjIxVDA1MTcxNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTk3ZWE5M2FmY2JmZTY3NzI0ODIwNTYzNGI4MTg1ODA2NWYxNmFkMGQ3OTFmODZlZTQxZmFhYjhlNDBlYzM0MjMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.hg9BW4ZAOYe5xN9XsACG_L1eZR9AdvATFis0A9kNKP0)
> 
> Then what should i do?

`<h2>Bookmarks</h2>`
You can change it to `<span id ="bookmarksHeader">Bookmarks</span>`
And replace h2 with id in css

2024-12-21 05:25 UTC, prem-k-r commented
> > And is it possible to show Mobile Bookmarks folder too?
> 
> Idk i only tested it on chrome. On my computer.

Nah, not that.. there are 3 default bookmark folders: Bookmarks bar, Other bookmarks, Mobile bookmarks. One can create more folders too.
Bookmarks bar and Other bookmarks are visible, but mobile bookmark isn't.
You can leave it if it's complicated..

2024-12-21 06:02 UTC, Thunder-Blaze commented
@itz-rj-here do lmk that should I make PR of modified CSS rn in your patch-1 branch or should I wait for this to get merged ?

2024-12-21 06:04 UTC, itz-rj-here commented
> @itz-rj-here do lmk that should I make PR of modified CSS rn in your patch-1 branch or should I wait for this to get merged ?

Do the changes to my patch-1 i will be on my computer after 2 hours.

2024-12-21 07:40 UTC, itz-rj-here commented
![image](https://github.com/user-attachments/assets/8f1129a3-b544-4426-a8ed-b5ff12abcd94)
Does anyone of you are getting this same icon?

2024-12-21 07:41 UTC, prem-k-r commented
Yep

2024-12-21 07:43 UTC, itz-rj-here commented
> Yep

Odd. I don't see any issue on the manifest code...
Then where could be the issue???

2024-12-21 07:45 UTC, prem-k-r commented
Is it showing extension icon for other newtab extensions asking permission?

2024-12-21 07:47 UTC, itz-rj-here commented
> Is it showing extension icon for other newtab extensions asking permission?

What? I dont understand actually.
If i guessed right then yeah in other newtabs it asks permission for the bookmark usage.

2024-12-21 07:49 UTC, prem-k-r commented
When they ask for permission, do they show their own icon? 

Jigsaw puzzle piece icon could be default one

2024-12-21 07:50 UTC, itz-rj-here commented
> When they ask for permission, do they show their own icon?
> 
> Jigsaw puzzle piece icon could be default one

Yup. W8 let me show you an example.

2024-12-21 07:52 UTC, itz-rj-here commented
![image](https://github.com/user-attachments/assets/1e5aad37-ef64-41bd-b471-7089c8edbb50)

2024-12-21 07:54 UTC, Thunder-Blaze commented
btw @itz-rj-here please try not to change many things before I make a pr as I am changing class names of most things with a bookmark- suffix

Current Progress -

![17347676279357357957732759405407](https://github.com/user-attachments/assets/408a13cd-8d37-4294-be72-287f899c85b9)

2024-12-21 07:55 UTC, itz-rj-here commented
> btw @itz-rj-here please try not to change many things before I make a pr as I am changing class names of most things with a bookmark- suffix
> 
> Current Progress -
> 
> ![17347676279357357957732759405407](https://private-user-images.githubusercontent.com/68265106/397913348-408a13cd-8d37-4294-be72-287f899c85b9.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQ3Njc5OTgsIm5iZiI6MTczNDc2NzY5OCwicGF0aCI6Ii82ODI2NTEwNi8zOTc5MTMzNDgtNDA4YTEzY2QtOGQzNy00Mjk0LWJlNzItMjg3Zjg5OWM4NWI5LmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjIxVDA3NTQ1OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWUxMTU2ZDAyMjRiOWU2MDVhZTlmZGQ0NTc1OGFiMmRkYmYzODM0ZDBkNjlmZWMxOTkwYmIwYjhmNDY2YzgwMTgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.m_pAWDhtASimDdxJdLqBoPppUrIN0ml1hnGITtJ6qaQ)

Np. Im not. Im trying to figure it out why the icon is not working or showing.

2024-12-21 08:01 UTC, itz-rj-here commented
@prem-k-r i found a problem when i reset settings, the bookmark doesn't again asks for bookmark permission. Can you give me any suggestion for this?

2024-12-21 08:09 UTC, prem-k-r commented
> @prem-k-r i found a problem when i reset settings, the bookmark doesn't again asks for bookmark permission. Can you give me any suggestion for this?

In reset settings function, you can chrome.permissions.remove({ permissions: ['bookmarks'] }

2024-12-21 08:10 UTC, itz-rj-here commented
> > @prem-k-r i found a problem when i reset settings, the bookmark doesn't again asks for bookmark permission. Can you give me any suggestion for this?
> 
> In reset settings function, you can chrome.permissions.remove({ permissions: ['bookmarks'] }

Got it.

2024-12-21 08:11 UTC, prem-k-r commented
Btw, reset settings don't delete wallpaper.. shall i include that?

2024-12-21 08:11 UTC, itz-rj-here commented
> Btw, reset settings don't delete wallpaper.. shall i include that?

Yup you should actually.

2024-12-21 08:12 UTC, prem-k-r commented
Ok

2024-12-21 08:17 UTC, XengShi commented
> Btw, reset settings don't delete wallpaper.. shall i include that? 

Since there is already a delete button for wallpaper so not needed. If the user wants to reset the settings they probably don't wanna change the wallpaper

2024-12-21 08:20 UTC, itz-rj-here commented
> > Btw, reset settings don't delete wallpaper.. shall i include that?
> 
> Since there is already a delete button for wallpaper so not needed. If the user wants to reset the settings they probably don't wanna change the wallpaper

As you think. @prem-k-r

2024-12-21 08:21 UTC, prem-k-r commented
> > Btw, reset settings don't delete wallpaper.. shall i include that?
> 
> Since there is already a delete button for wallpaper so not needed. If the user wants to reset the settings they probably don't wanna change the wallpaper

Yeah ok.. that's why I didn't included delete of indexeddb... Currently only clear local storage

2024-12-21 08:23 UTC, itz-rj-here commented
> > > Btw, reset settings don't delete wallpaper.. shall i include that?
> > 
> > 
> > Since there is already a delete button for wallpaper so not needed. If the user wants to reset the settings they probably don't wanna change the wallpaper
> 
> Yeah ok.. that's why I didn't included delete of indexeddb... Currently only clear local storage

@prem-k-r it's not working. I used this code.

`    // Reset settings (clear localStorage)
    resetbtn.addEventListener("click", () => {
        if (confirm(translations[currentLanguage]?.confirmRestore || translations['en'].confirmRestore)) {
            localStorage.clear();
            if (chrome.permissions) {
                chrome.permissions.remove({
                    permissions: ['bookmarks', 'favicon']
                }, (removed) => {
                    if (removed) {
                        console.log('Permissions removed');
                    } else {
                        console.log('Permissions not removed');
                    }
                    location.reload();
                });
            } else {
                console.error('chrome.permissions API is unavailable.');
                location.reload();
            }
        }
    });`

2024-12-21 08:36 UTC, Thunder-Blaze commented
![image](https://github.com/user-attachments/assets/80777dcc-0d1e-4efa-a418-49517a0e5b8a)

Any more suggestions to enhance UI ?
btw @itz-rj-here nice idea of right arrow toggle

2024-12-21 08:53 UTC, prem-k-r commented
Looking better 

How about a touch of this.. ofc maintaining current color 
![IMG_20241221_142155_029](https://github.com/user-attachments/assets/d57b3672-d221-4de7-a383-4c4e744a5e74)

2024-12-21 08:56 UTC, Thunder-Blaze commented
Oh sure, I can do that

Just have to check browser compatibility of that code

2024-12-21 08:58 UTC, prem-k-r commented
> > > > Btw, reset settings don't delete wallpaper.. shall i include that?
> > > 
> > > 
> > > Since there is already a delete button for wallpaper so not needed. If the user wants to reset the settings they probably don't wanna change the wallpaper
> > 
> > 
> > Yeah ok.. that's why I didn't included delete of indexeddb... Currently only clear local storage
> 
> @prem-k-r it's not working. I used this code.
> 
> `
> 
> ```
> // Reset settings (clear localStorage)
> resetbtn.addEventListener("click", () => {
>     if (confirm(translations[currentLanguage]?.confirmRestore || translations['en'].confirmRestore)) {
>         localStorage.clear();
>         if (chrome.permissions) {
>             chrome.permissions.remove({
>                 permissions: ['bookmarks', 'favicon']
>             }, (removed) => {
>                 if (removed) {
>                     console.log('Permissions removed');
>                 } else {
>                     console.log('Permissions not removed');
>                 }
>                 location.reload();
>             });
>         } else {
>             console.error('chrome.permissions API is unavailable.');
>             location.reload();
>         }
>     }
> });
> ```
> 
> `

Will check

2024-12-21 09:00 UTC, prem-k-r commented
> Oh sure, I can do that
> 
> Just have to check browser compatibility of that code

Currently this is supported in chrome, edge and brave.. we have to add a toggle in menu to hide.. and for unsupported browser show text ctrl+ shift + b to show bookmark bar.. like in chrome web store version v2.5

2024-12-21 09:04 UTC, prem-k-r commented
We can maybe remove the gear icon and show recently added all the time.. it is at the bottom so doesn't affect much. 
And if we are planning to add add bookmark option too.. then can place there

2024-12-21 09:08 UTC, Thunder-Blaze commented
Oh, nice idea
I'll modify the pr in evening rn got irl work 😔

2024-12-21 10:02 UTC, prem-k-r commented
@itz-rj-here the icons that you are using have padding.. 
You can use from this:
https://www.transfernow.net/dl/20241221arTUbKxU

2024-12-21 10:44 UTC, itz-rj-here commented
> @itz-rj-here the icons that you are using have padding.. 
> You can use from this:
> https://www.transfernow.net/dl/20241221arTUbKxU

Okkk

2024-12-21 11:12 UTC, Thunder-Blaze commented
![image](https://github.com/user-attachments/assets/6e1d6b6c-f8c8-4a68-bb57-9e820d2c629b)

removed the gear and made the cross appear only when bookmark is hovered

![image](https://github.com/user-attachments/assets/ce76a69c-d67a-4995-b76d-c288cbfb2e2c)

Also recently added now remains there by default

2024-12-21 13:04 UTC, Thunder-Blaze commented
btw in Brave, only folders are loading, the ungrouped bookmarks are not appearing
I know this feature is only for chrome but thought I'd let you know

2024-12-21 13:05 UTC, itz-rj-here commented
> btw in Brave, only folders are loading, the ungrouped bookmarks are not appearing I know this feature is only for chrome but thought I'd let you know

Can you also include a screenshot of it?

2024-12-21 13:08 UTC, itz-rj-here commented
> btw in Brave, only folders are loading, the ungrouped bookmarks are not appearing I know this feature is only for chrome but thought I'd let you know
> 
> ![image](https://private-user-images.githubusercontent.com/68265106/397929164-0890cb45-e746-4b12-85be-6ec6a8912a8a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQ3ODY4MTUsIm5iZiI6MTczNDc4NjUxNSwicGF0aCI6Ii82ODI2NTEwNi8zOTc5MjkxNjQtMDg5MGNiNDUtZTc0Ni00YjEyLTg1YmUtNmVjNmE4OTEyYThhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjIxVDEzMDgzNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWUwMDA1ZmQ4YjJiMGYxMjBlZDExZTViZmM2MmYzZjI4YzRlZmFmNGQxNGRiODdhOTM1NGIyMzNjZGJlNmNkYTQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.GqFEVja8Y4cPNpxune6P3SgJCzn_T1LIT2D5n5au9y0)
> 
> as you can see I have this bookmark but its not appearing nor there is any error except for favicon not found errors

Weird.

2024-12-21 13:08 UTC, Thunder-Blaze commented
![image](https://github.com/user-attachments/assets/1e9a5a54-7b9b-4e58-b7f8-98efa8c7e4f6)
this screenshot works better ig

2024-12-21 13:09 UTC, itz-rj-here commented
> ![image](https://private-user-images.githubusercontent.com/68265106/397929254-1e9a5a54-7b9b-4e58-b7f8-98efa8c7e4f6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQ3ODY4MzIsIm5iZiI6MTczNDc4NjUzMiwicGF0aCI6Ii82ODI2NTEwNi8zOTc5MjkyNTQtMWU5YTVhNTQtN2I5Yi00ZTU4LWI3ZjgtOThlZmE4YzdlNGY2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjIxVDEzMDg1MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTg5MTg4YmFkYjg1ZTQyMjE5MWZjMjMxZjRiMDcxNTczNzEzOGFhYTg5NTg5YTYzNzAzOTk5NDdlMGJiYjI5YjcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.X5s-I7D8CvKxSwXBIJJTViGO0qsNY5yX06jH88fNXLo) this screenshot works better ig

yup

2024-12-21 13:10 UTC, itz-rj-here commented
> ![image](https://private-user-images.githubusercontent.com/68265106/397929254-1e9a5a54-7b9b-4e58-b7f8-98efa8c7e4f6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQ3ODY5MDgsIm5iZiI6MTczNDc4NjYwOCwicGF0aCI6Ii82ODI2NTEwNi8zOTc5MjkyNTQtMWU5YTVhNTQtN2I5Yi00ZTU4LWI3ZjgtOThlZmE4YzdlNGY2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjIxVDEzMTAwOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTFlYWY0YWNiOGMyMzM2ZDE2MmRhOTZmNmI3NTlkNmFiMDU0Y2I3ODhiM2M3NTQzNDJkZDUwZGQyNjhmMWRjMWImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.khX2Ltmv-xsOVMqFNAfrSI-8ukxoSOOxnKrV5CAX1yg) this screenshot works better ig
> 
> while in chrome ![image](https://private-user-images.githubusercontent.com/68265106/397929326-dd801c07-0c2d-4fa8-a92b-1e2bb5b62be7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQ3ODY5MDgsIm5iZiI6MTczNDc4NjYwOCwicGF0aCI6Ii82ODI2NTEwNi8zOTc5MjkzMjYtZGQ4MDFjMDctMGMyZC00ZmE4LWE5MmItMWUyYmI1YjYyYmU3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjIxVDEzMTAwOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTAzZWZlM2JiN2UwNWZkZTJhN2UwNGEwNGE3NmNmNGI1YWJmYjE3NDkzNzdkZTc0OTFjY2VmNjFhOTgxNjFmMmEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.EFfZjseDbKvofZQkIcLuRM7cJNn_F2jJyYL8RwRMqVU)

Wait let me check the js code one more time if i find any solution.

2024-12-21 13:14 UTC, Thunder-Blaze commented
![image](https://github.com/user-attachments/assets/490d9064-0e7e-42eb-9d23-357c3f1abe37)
btw see this, we can also add mobile bookmarks

2024-12-21 13:15 UTC, itz-rj-here commented
> ![image](https://private-user-images.githubusercontent.com/68265106/397929499-490d9064-0e7e-42eb-9d23-357c3f1abe37.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQ3ODcyMDksIm5iZiI6MTczNDc4NjkwOSwicGF0aCI6Ii82ODI2NTEwNi8zOTc5Mjk0OTktNDkwZDkwNjQtMGU3ZS00MmViLTlkMjMtMzU3YzNmMWFiZTM3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjIxVDEzMTUwOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTIzYmYxMWIyZWU1MDIxMzFiN2FlYTJjZjA2OWIzYzlkNDRkZDUyMGYxMmExOGU4NzBiNzAwOTdjNDkwMWE2OGYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.6d19r-obyxO7-O_iUYtSbD5jUFn4mfXelSr1IE2ricE) btw see this, we can also add mobile bookmarks

KK let me look into it.

2024-12-21 13:19 UTC, itz-rj-here commented
@Thunder-Blaze Check this code if it works.
![image](https://github.com/user-attachments/assets/7b18f589-dbaa-4447-b523-47c2d51e600d)

2024-12-21 13:19 UTC, Thunder-Blaze commented
![image](https://github.com/user-attachments/assets/fe2fa1d2-d215-4789-aa1c-e9088010ad6d)
I think I found it, the node titles are different for chrome it is "Bookmarks Bar" while for brave it is "Bookmarks"

2024-12-21 13:20 UTC, itz-rj-here commented
> ![image](https://private-user-images.githubusercontent.com/68265106/397929744-fe2fa1d2-d215-4789-aa1c-e9088010ad6d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQ3ODc0ODksIm5iZiI6MTczNDc4NzE4OSwicGF0aCI6Ii82ODI2NTEwNi8zOTc5Mjk3NDQtZmUyZmExZDItZDIxNS00Nzg5LWFhMWMtZTkwODgwMTBhZDZkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjIxVDEzMTk0OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTk3YzM3NzE0NTkyOWEwMjAyZWYwMWQ1MGRhMmRlNjk4OWU4OGY1NDE4NDYyYWYyY2EzNDY3OGYzZmJjZDc1YWQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.RffE1GqfFUNfb_N5zbZ8n-amqV2QW1I7AJ153C-cKto) I think I found it, the node titles are different for chrome it is "Bookmarks Bar" while for brave it is "Bookmarks"

Yup thats is. You can use to change that too. NP.

2024-12-21 13:22 UTC, Thunder-Blaze commented
![image](https://github.com/user-attachments/assets/30c1b07a-dfd2-44cc-8771-1c5da2a1a808)

Yes mobile bookmarks working

2024-12-21 13:22 UTC, itz-rj-here commented
> ![image](https://private-user-images.githubusercontent.com/68265106/397929923-30c1b07a-dfd2-44cc-8771-1c5da2a1a808.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQ3ODc2MzUsIm5iZiI6MTczNDc4NzMzNSwicGF0aCI6Ii82ODI2NTEwNi8zOTc5Mjk5MjMtMzBjMWIwN2EtZGZkMi00NGNjLTg3NzEtMWM1ZGEyYTFhODA4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjIxVDEzMjIxNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWVmYjhkMTk3OWVhMGZhZTk5YTgxYzliYzQ2NTM4ODQ3MDgzZTY3MTA2MWE4YTRhMDc2OGZlNWMxNGQyZTJlOTAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.Yx7ar6f-9nFCKQtUC3ZugGxFxsTAkbcA0EqWoB5cdus)
> 
> Yes mobile bookmarks working

Great...

2024-12-21 13:24 UTC, Thunder-Blaze commented
![image](https://github.com/user-attachments/assets/5a04b70b-66e7-49e0-ad3f-22199a7e85b1)
this also worked 👍🏻

2024-12-21 13:25 UTC, itz-rj-here commented
> ![image](https://private-user-images.githubusercontent.com/68265106/397930029-5a04b70b-66e7-49e0-ad3f-22199a7e85b1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQ3ODc3NzksIm5iZiI6MTczNDc4NzQ3OSwicGF0aCI6Ii82ODI2NTEwNi8zOTc5MzAwMjktNWEwNGI3MGItNjZlNy00OWUwLWFkM2YtMjIxOTlhN2U4NWIxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjIxVDEzMjQzOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWFhOTQ5OGQ1NzI3ODQzYWZkZGEyNTJmYzhmZjYyN2Y5NDE2ZWNlZjRmMGJiMTBhYWZlYWQxNmM4ODMxZTI5YTImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.KPOrcf8FTzFQU6IwENS62XBXs_jWZpF8Rw6u_lzeTRA) this also worked 👍🏻

Great to know.

2024-12-21 13:30 UTC, Thunder-Blaze commented
![image](https://github.com/user-attachments/assets/bede0e6e-548b-44d0-a62b-e56bb430f863)
btw should I just do it like this or check the browser using navigator ?

2024-12-21 13:36 UTC, itz-rj-here commented
> ![image](https://private-user-images.githubusercontent.com/68265106/397930309-bede0e6e-548b-44d0-a62b-e56bb430f863.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQ3ODgxMzQsIm5iZiI6MTczNDc4NzgzNCwicGF0aCI6Ii82ODI2NTEwNi8zOTc5MzAzMDktYmVkZTBlNmUtNTQ4Yi00NGQwLWE2MmItZTU2YmI0MzBmODYzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjIxVDEzMzAzNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTMwMTcyZmFjMWU0Y2FmOGQ0MjBhZTVkMGNlNGQ0MWFiMWU2ZWEwNGRmZTIwMTZiMWI4MWY0OWJmMzM3Y2JlOWImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.zMCL66mvJR74mv2FhLvixingcqkDeMDXC5RCQIXxnTg) btw should I just do it like this or check the browser using navigator ?

Hmm... I can't tell actually. Maybe use the Feature-detection. Like this if you can. 
![image](https://github.com/user-attachments/assets/87fdd0fe-77cf-4659-82d7-c054e0b4b550)

As you told to me im not doing any significant changes until you open a pr on my repo.

2024-12-21 13:38 UTC, Thunder-Blaze commented
huh PR is there since evening isn't it ?

2024-12-21 13:38 UTC, itz-rj-here commented
> huh PR is there since evening isn't it ?

No ig

2024-12-21 13:39 UTC, Thunder-Blaze commented
![image](https://github.com/user-attachments/assets/968c03d7-bbfa-4f65-bb53-146b16002c0e)
?? is this wrong repo

2024-12-21 13:40 UTC, prem-k-r commented
> ![image](https://private-user-images.githubusercontent.com/68265106/397930309-bede0e6e-548b-44d0-a62b-e56bb430f863.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQ3ODg0NzcsIm5iZiI6MTczNDc4ODE3NywicGF0aCI6Ii82ODI2NTEwNi8zOTc5MzAzMDktYmVkZTBlNmUtNTQ4Yi00NGQwLWE2MmItZTU2YmI0MzBmODYzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjIxVDEzMzYxN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTdjMTU3NTBjNjBhZmQ4MTA3MmUzMzdkZjBmOGU0NTM2MGI5ZWEzOGJhOGJjZjVkMTZhODhmM2M0MWZiNDQ4NDAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.0TxvJ2t337twhk9-yorTt3kM5lY0UgIpVktJnVKeFQE)
> 
> btw should I just do it like this or check the browser using navigator like this?
> 
> ![image](https://private-user-images.githubusercontent.com/68265106/397930610-8043d626-f027-4699-a06b-1e0d0ae7bf78.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQ3ODg0NzcsIm5iZiI6MTczNDc4ODE3NywicGF0aCI6Ii82ODI2NTEwNi8zOTc5MzA2MTAtODA0M2Q2MjYtZjAyNy00Njk5LWEwNmItMWUwZDBhZTdiZjc4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjIxVDEzMzYxN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWM0MDIzZjhiM2IyNDIxOTQxYWY3MTBhMzlhODhjM2MzNGNkYjgyODU0YzRhODI1NjNkYWVmYzkyYjgyNjgzMmImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.hH53ORfsrPTADV_ywxTAaMp5AyXkZSQccdziB0qwo4A)

yeah.. `navigator.brave && navigator.brave.isBrave`

2024-12-21 13:41 UTC, itz-rj-here commented
> > ![image](https://private-user-images.githubusercontent.com/68265106/397930309-bede0e6e-548b-44d0-a62b-e56bb430f863.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQ3ODg0NzcsIm5iZiI6MTczNDc4ODE3NywicGF0aCI6Ii82ODI2NTEwNi8zOTc5MzAzMDktYmVkZTBlNmUtNTQ4Yi00NGQwLWE2MmItZTU2YmI0MzBmODYzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjIxVDEzMzYxN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTdjMTU3NTBjNjBhZmQ4MTA3MmUzMzdkZjBmOGU0NTM2MGI5ZWEzOGJhOGJjZjVkMTZhODhmM2M0MWZiNDQ4NDAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.0TxvJ2t337twhk9-yorTt3kM5lY0UgIpVktJnVKeFQE)
> > btw should I just do it like this or check the browser using navigator like this?
> > ![image](https://private-user-images.githubusercontent.com/68265106/397930610-8043d626-f027-4699-a06b-1e0d0ae7bf78.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQ3ODg0NzcsIm5iZiI6MTczNDc4ODE3NywicGF0aCI6Ii82ODI2NTEwNi8zOTc5MzA2MTAtODA0M2Q2MjYtZjAyNy00Njk5LWEwNmItMWUwZDBhZTdiZjc4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjIxVDEzMzYxN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWM0MDIzZjhiM2IyNDIxOTQxYWY3MTBhMzlhODhjM2MzNGNkYjgyODU0YzRhODI1NjNkYWVmYzkyYjgyNjgzMmImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.hH53ORfsrPTADV_ywxTAaMp5AyXkZSQccdziB0qwo4A)
> 
> yeah.. `navigator.brave && navigator.brave.isBrave`

@Thunder-Blaze

2024-12-21 13:42 UTC, prem-k-r commented
> ![image](https://private-user-images.githubusercontent.com/68265106/397929499-490d9064-0e7e-42eb-9d23-357c3f1abe37.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQ3ODg0NzcsIm5iZiI6MTczNDc4ODE3NywicGF0aCI6Ii82ODI2NTEwNi8zOTc5Mjk0OTktNDkwZDkwNjQtMGU3ZS00MmViLTlkMjMtMzU3YzNmMWFiZTM3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjIxVDEzMzYxN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTcxMjk3ODFlZTIzNjE2MWU4NjQ4MGU1OWUzYTQ2YWZmNDY5ZTU2NDU4N2FjMmU5YTg3Y2Q2NjE3ZWQ0MGRlY2QmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.hIWi20EMI_fJy3fQ_eSNBITopaOyhrGo3BmG7gAbiUM) btw see this, we can also add mobile bookmarks

nice observation.. i think custom bookmark folder should also be possible now lol

2024-12-21 13:51 UTC, prem-k-r commented
great! please also change `searchbar` to bookmarkSearch or something.. conflicting name

2024-12-21 13:51 UTC, itz-rj-here commented
> great! please also change `searchbar` to bookmarkSearch or something.. conflicting name

Wait a bit

2024-12-21 13:52 UTC, Thunder-Blaze commented
> > ![image](https://private-user-images.githubusercontent.com/68265106/397929499-490d9064-0e7e-42eb-9d23-357c3f1abe37.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQ3ODg0NzcsIm5iZiI6MTczNDc4ODE3NywicGF0aCI6Ii82ODI2NTEwNi8zOTc5Mjk0OTktNDkwZDkwNjQtMGU3ZS00MmViLTlkMjMtMzU3YzNmMWFiZTM3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjIxVDEzMzYxN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTcxMjk3ODFlZTIzNjE2MWU4NjQ4MGU1OWUzYTQ2YWZmNDY5ZTU2NDU4N2FjMmU5YTg3Y2Q2NjE3ZWQ0MGRlY2QmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.hIWi20EMI_fJy3fQ_eSNBITopaOyhrGo3BmG7gAbiUM) btw see this, we can also add mobile bookmarks
> 
> nice observation.. i think custom bookmark folder should also be possible now lol

though first ig we gotta deal with favicon not found issue, if the favicon is not found, it should quietly replace the favicon with default one without creating a console.error msg

I tried, but couldn't fix it

2024-12-21 14:03 UTC, prem-k-r commented
![image](https://github.com/user-attachments/assets/e110ade3-82c6-4c3d-aca6-236313f6974d)
google apps..
please check z index

2024-12-21 14:03 UTC, itz-rj-here commented
> bookmarkSearch

Already updated it.

2024-12-21 14:09 UTC, Thunder-Blaze commented
> ![image](https://private-user-images.githubusercontent.com/60751338/397932185-e110ade3-82c6-4c3d-aca6-236313f6974d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQ3OTAyOTcsIm5iZiI6MTczNDc4OTk5NywicGF0aCI6Ii82MDc1MTMzOC8zOTc5MzIxODUtZTExMGFkZTMtODJjNi00YzNkLWFjYTYtMjM2MzEzZjY5NzRkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjIxVDE0MDYzN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTlmY2NiMTI1NDA5OGI0YjU3MDcwNDg3YmUwYWQ1M2M2ZDlhOTVmNDU0NWYzYWY3ZmMxMzIzMGU4OTFhZGE2NzcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.SAo3BPiXuJiOkXt-ZHchblV9ALpjQpNpUDeFGWaJCA4) google apps.. please check z index

oh I forgot to test with google apps being on
gimme a min

2024-12-21 14:10 UTC, itz-rj-here commented
> > ![image](https://private-user-images.githubusercontent.com/60751338/397932185-e110ade3-82c6-4c3d-aca6-236313f6974d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQ3OTAyOTcsIm5iZiI6MTczNDc4OTk5NywicGF0aCI6Ii82MDc1MTMzOC8zOTc5MzIxODUtZTExMGFkZTMtODJjNi00YzNkLWFjYTYtMjM2MzEzZjY5NzRkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjIxVDE0MDYzN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTlmY2NiMTI1NDA5OGI0YjU3MDcwNDg3YmUwYWQ1M2M2ZDlhOTVmNDU0NWYzYWY3ZmMxMzIzMGU4OTFhZGE2NzcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.SAo3BPiXuJiOkXt-ZHchblV9ALpjQpNpUDeFGWaJCA4) google apps.. please check z index
> 
> oh I forgot to test with google apps being on gimme a min

I fixed it np...

2024-12-21 14:14 UTC, prem-k-r commented
comments were good lol

2024-12-21 14:15 UTC, itz-rj-here commented
> comments were good lol

Uhhh. Ok i will revert the comments :)
I thought it looks too odd with that much comment actually.

2024-12-21 14:19 UTC, Thunder-Blaze commented
btw set z-index of arrow to 5 when side bar is opened in line 524 otherwise keep it 2 else it gets on top of google apps
it disappears when the sidebar is opened

2024-12-21 14:20 UTC, itz-rj-here commented
> btw set z-index of arrow to 5 when side bar is opened in line 524 otherwise keep it 2 else it gets on top of google apps it disappears when the sidebar is opened

Lol. I didn't saw that thanks for mentioning...

2024-12-21 14:23 UTC, itz-rj-here commented
@prem-k-r @Thunder-Blaze what about the firefox. I just realized.

2024-12-21 14:24 UTC, Thunder-Blaze commented
And lol I was making PR but commits are getting stacked so can't change it myself rn

it ain't working in firefox

2024-12-21 14:26 UTC, Thunder-Blaze commented
I think you'll have to use browser.bookmarks.getTree() for firefox

2024-12-21 14:26 UTC, itz-rj-here commented
> I think you'll have to use browser.bookmarks.getTree() for firefox

Let me check the dev web first

2024-12-21 14:29 UTC, prem-k-r commented
> browser.bookmarks.getTree()

yep

2024-12-21 14:39 UTC, itz-rj-here commented
@Thunder-Blaze can you help me with one thing?
Can you add the toggle permission in menu section please.
and when the settings for bookmark is toggled, make the bookmark permission message appears. Not when the arrow button is clicked.

2024-12-21 14:39 UTC, itz-rj-here commented
> @Thunder-Blaze can you help me with one thing? Can you add the toggle permission in menu section please. and when the settings for bookmark is toggled, make the bookmark permission message appears. Not when the arrow button is clicked.

If you can't i will try it tomorrow.

2024-12-21 14:40 UTC, Thunder-Blaze commented
yeah sure np 👍🏻

2024-12-21 15:00 UTC, XengShi commented
![Bookmarks](https://github.com/user-attachments/assets/d1555f7f-12d2-4775-9989-86611ec71849)
Here is the concept for bookmarks
@itz-rj-here

2024-12-21 15:02 UTC, itz-rj-here commented
> ![Bookmarks](https://private-user-images.githubusercontent.com/48722764/397935180-d1555f7f-12d2-4775-9989-86611ec71849.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQ3OTM1MTgsIm5iZiI6MTczNDc5MzIxOCwicGF0aCI6Ii80ODcyMjc2NC8zOTc5MzUxODAtZDE1NTVmN2YtMTJkMi00Nzc1LTk5ODktODY2MTFlYzcxODQ5LmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjIxVDE1MDAxOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTA0OTIwZDY0NWQ1NGViMjcwODFiODA0OWZhZDYwOTIxZjA5ZDA3ZGJhZjdmNWUwYTAzM2E2MjQ1OTE5ODQzYzUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.aV4nvRaWyiNVEQOGmvAX_P4aGHV-X-bZHdrN7K_Du-s) Here is the concept for bookmarks @itz-rj-here

Bruh. What is that. Umm. I have an idea. We can use to add a Express mode or something to the menu section to show this ui if the user wants to use it.

2024-12-21 15:04 UTC, itz-rj-here commented
> I don't know about Express mode!

W8 Let me show you.

2024-12-21 15:07 UTC, itz-rj-here commented
![image](https://github.com/user-attachments/assets/155990ef-def4-488f-82d9-793420b1dc88)

This is what it looks when express mode is off
![image](https://github.com/user-attachments/assets/c7646a14-33b5-4521-a835-73bed2dec7a3)

This is what it looks when express mode is on
![image](https://github.com/user-attachments/assets/57c5917b-67d1-478e-9223-de1c78230471)


Actually it means it makes the bookmark system to a new look.

2024-12-21 15:10 UTC, Thunder-Blaze commented
woah nice concept design
btw @itz-rj-here I wanted to ask why the functions are in DOM Content Loaded
I mean the script has defer attribute so it will always load after DOM has loaded
is it necessary for them to be inside DOM content loaded event listener ?

and @XengShi can you please review the old PRs as I wanted to delete some branches here and there

2024-12-21 15:21 UTC, prem-k-r commented
> though first ig we gotta deal with favicon not found issue, if the favicon is not found, it should quietly replace the favicon with default one without creating a console.error msg
> 
> I tried, but couldn't fix it

Me too.. earlier i have tried for shortcuts too.. no result..
But i got a hint this time.. there is a favicon permission in manifest.. i dont think we are using it atm..
we can use chrome.bookmarks.getFavicon() to get the favicons

@itz-rj-here can you plese check

2024-12-21 15:25 UTC, itz-rj-here commented
> 
> > though first ig we gotta deal with favicon not found issue, if the favicon is not found, it should quietly replace the favicon with default one without creating a console.error msg
> > 
> > I tried, but couldn't fix it
> 
> Me too.. earlier i have tried for shortcuts too.. no result..
> But i got a hint this time.. there is a favicon permission in manifest.. i dont think we are using it atm..
> we can use chrome.bookmarks.getFavicon() to get the favicons
> 
> @itz-rj-here can you plese check

Maybe we can use the shortcuts icon code here. Ig

2024-12-21 15:26 UTC, prem-k-r commented
> > > though first ig we gotta deal with favicon not found issue, if the favicon is not found, it should quietly replace the favicon with default one without creating a console.error msg
> > > I tried, but couldn't fix it
> > 
> > 
> > Me too.. earlier i have tried for shortcuts too.. no result..
> > But i got a hint this time.. there is a favicon permission in manifest.. i dont think we are using it atm..
> > we can use chrome.bookmarks.getFavicon() to get the favicons
> > @itz-rj-here can you plese check
> 
> Maybe we can use the shortcuts icon code here. Ig If it works on both browsers.

nah.. it dont work that way.. and favicon problem is aslo there

2024-12-21 15:30 UTC, Thunder-Blaze commented
https://stackoverflow.com/questions/10301636/how-can-i-get-the-bookmark-icon-in-chrome

Check this out

2024-12-21 15:32 UTC, Thunder-Blaze commented
I can design the UI as @XengShi but I am not much familiar with Extensions and advanced JS so it'll need to be done by you ppl ig

and right this
![image](https://github.com/user-attachments/assets/db355eaa-e392-42dc-913c-4638c9bb4d69)

2024-12-21 15:35 UTC, itz-rj-here commented
> woah nice concept design
> btw @itz-rj-here I wanted to ask why the functions are in DOM Content Loaded
> I mean the script has defer attribute so it will always load after DOM has loaded
> is it necessary for them to be inside DOM content loaded event listener ?
> 
> and @XengShi can you please review the old PRs as I wanted to delete some branches here and there

Yes actually. Keeping it inside is maybe necessary as my knowledge says.

2024-12-21 15:40 UTC, XengShi commented
> I can design the UI as @XengShi wants but I am not much familiar with Extensions and advanced JS so it'll need to be done by you ppl ig
> 
> and right this
> ![image](https://github.com/user-attachments/assets/db355eaa-e392-42dc-913c-4638c9bb4d69)
> 

I don't think this will require advanced JS. Even if it does, ChatGPT is there to help!

2024-12-21 15:43 UTC, Thunder-Blaze commented
@itz-rj-here oh sure, then I'll try to make the toggle keeping them inside

@XengShi sure I'll try
btw I was talking about modifying favicons which require manifest and permission changes

2024-12-21 15:44 UTC, itz-rj-here commented
> I can design the UI as @XengShi wants but I am not much familiar with Extensions and advanced JS so it'll need to be done by you ppl ig
> 
> and right this
> ![image](https://github.com/user-attachments/assets/db355eaa-e392-42dc-913c-4638c9bb4d69)
> 

I will try to help you whenever you need it. There is already chatgpt and copilot. I use these most of the time to code this complicated codes. :)

2024-12-21 15:44 UTC, XengShi commented
> ![image](https://github.com/user-attachments/assets/155990ef-def4-488f-82d9-793420b1dc88)
> 
> This is what it looks when express mode is off
> ![image](https://github.com/user-attachments/assets/c7646a14-33b5-4521-a835-73bed2dec7a3)
> 
> This is what it looks when express mode is on
> ![image](https://github.com/user-attachments/assets/57c5917b-67d1-478e-9223-de1c78230471)
> 
> 
> Actually it means it makes the bookmark system to a new look.

But it doesn't match the extension, so what's the point of adding all those bookmarks? Remember, people are using the extension primarily for its appearance rather than its functionality.

2024-12-21 15:45 UTC, itz-rj-here commented
> @itz-rj-here oh sure, then I'll try to make the toggle keeping them inside
> 
> @XengShi sure I'll try
> btw I was talking about modifying favicons which require manifest and permission changes

I want to hear some suggestions from @prem-k-r what he thinks about the icon code.

2024-12-21 15:52 UTC, XengShi commented
@prem-k-r @itz-rj-here @Thunder-Blaze 
I am going to upload the chrome-store branch to the Chrome Web Store. We don't have much time left.

Please test the branch and add all the changes from the main branch, like the latest to-do list pin feature.

2024-12-21 15:54 UTC, itz-rj-here commented
> @prem-k-r @itz-rj-here @Thunder-Blaze 
> I am going to upload the chrome-store branch to the Chrome Web Store. We don't have much time left.
> 
> Please test the branch and add all the changes from the main branch, like the latest to-do list pin feature.

I can't currently. I will do it later. I have a small test tomorrow. So i need to study for a bit.

2024-12-21 15:55 UTC, itz-rj-here commented
Sorry.

2024-12-21 15:56 UTC, prem-k-r commented
> > @itz-rj-here oh sure, then I'll try to make the toggle keeping them inside
> > @XengShi sure I'll try
> > btw I was talking about modifying favicons which require manifest and permission changes
> 
> I want to hear some suggestions from @prem-k-r what he thinks about the icon code.

I think chrome.bookmarks.getFavicon() can help.. have to utilise it in displayBookmarks()

2024-12-21 15:57 UTC, XengShi commented
> Sorry.
Why Sorrying 🙃🙃🙃 it's okay

2024-12-21 15:58 UTC, Thunder-Blaze commented
@prem-k-r can u send the screenshot of its output cuz I am unable to use that function

@itz-rj-here btw toggle done, I am creating a PR

2024-12-21 15:59 UTC, prem-k-r commented
> @prem-k-r @itz-rj-here @Thunder-Blaze I am going to upload the chrome-store branch to the Chrome Web Store. We don't have much time left.
> 
> Please test the branch and add all the changes from the main branch, like the latest to-do list pin feature.

if todo pin and page flashing branches are not deleted yet, @Thunder-Blaze can pull PR
rest are some minor translation related
maybe a toggle to hide quote and we are good to go

2024-12-21 15:59 UTC, itz-rj-here commented
> @prem-k-r can u send the screenshot of its output cuz I am unable to use that function
> 
> @itz-rj-here btw toggle done, I am creating a PR

I will merge the pr from my phone. Just mention me to the pr.

2024-12-21 16:03 UTC, Thunder-Blaze commented
@prem-k-r aa I just deleted the branches 
they are present on my system tho
should I make pr on chrome branch ?

2024-12-21 16:03 UTC, Thunder-Blaze commented
> > @prem-k-r @itz-rj-here @Thunder-Blaze I am going to upload the chrome-store branch to the Chrome Web Store. We don't have much time left.
> > Please test the branch and add all the changes from the main branch, like the latest to-do list pin feature.
> 
> if todo pin and page flashing branches are not deleted yet, @Thunder-Blaze can pull PR rest are some minor translation related maybe a toggle to hide quote and we are good to go

which quote ?

2024-12-21 16:05 UTC, itz-rj-here commented
> > > @prem-k-r @itz-rj-here @Thunder-Blaze I am going to upload the chrome-store branch to the Chrome Web Store. We don't have much time left.
> > > Please test the branch and add all the changes from the main branch, like the latest to-do list pin feature.
> > 
> > if todo pin and page flashing branches are not deleted yet, @Thunder-Blaze can pull PR rest are some minor translation related maybe a toggle to hide quote and we are good to go
> 
> which quote ?

Uhh. 😅
A text from some writers shows instead of the search engine selector

2024-12-21 16:05 UTC, prem-k-r commented
> chrome.bookmarks.getFavicon

yes please

2024-12-21 16:07 UTC, prem-k-r commented
> @prem-k-r can u send the screenshot of its output cuz I am unable to use that function

i dont know, it probably dont have direct api call

2024-12-21 16:08 UTC, prem-k-r commented
> > > @prem-k-r @itz-rj-here @Thunder-Blaze I am going to upload the chrome-store branch to the Chrome Web Store. We don't have much time left.
> > > Please test the branch and add all the changes from the main branch, like the latest to-do list pin feature.
> > 
> > 
> > if todo pin and page flashing branches are not deleted yet, @Thunder-Blaze can pull PR rest are some minor translation related maybe a toggle to hide quote and we are good to go
> 
> which quote ?

it is there in chrome store branch
random quotes in place of `Search with` search engines selector

2024-12-21 16:09 UTC, itz-rj-here commented
Guys you do all the required changes as needed. When you guys need to add a pull just remember to mention me. Now im going bye.

2024-12-21 16:11 UTC, XengShi commented
> @prem-k-r aa I just deleted the branches 
> they are present on my system tho
> should I make pr on chrome branch ?

Chrome branch is missing latest to-do-list pinning option please make pr for this

2024-12-21 16:12 UTC, Thunder-Blaze commented
@XengShi got it lemme try

2024-12-21 16:17 UTC, Thunder-Blaze commented
@XengShi it's having merge conflicts, should I continue or should I pull it make changes and then push ?

2024-12-21 16:17 UTC, prem-k-r commented
wait @XengShi maybe u can do it one pr
![image](https://github.com/user-attachments/assets/f066bff1-4e85-4c48-85da-f33cc19551c1)
please check
https://github.com/XengShi/materialYouNewTab/compare/XengShi:chrome-store...XengShi:main

2024-12-21 16:18 UTC, prem-k-r commented
Just dont force push.. it revert some changes

2024-12-21 16:22 UTC, prem-k-r commented
> @XengShi it's having merge conflicts, should I continue or should I pull it make changes and then push ?

ah right.. it will have conflicts.. maybe we have to manually make all changes :(

2024-12-21 16:23 UTC, Thunder-Blaze commented
sadge, do lemme know if I need to manually do the changes

2024-12-21 16:27 UTC, Thunder-Blaze commented
Ig I'll do it before 11 if nobody else is doing as I am free rn

2024-12-21 16:27 UTC, prem-k-r commented
yeah lets do it manually.. please do both flashing and todo pin
i'll do for rest.. new lang and translation related ones

2024-12-21 16:30 UTC, Thunder-Blaze commented
Sure, I'll start in 10 min 👍🏻

2024-12-21 16:53 UTC, prem-k-r commented
> > > > @prem-k-r @itz-rj-here @Thunder-Blaze I am going to upload the chrome-store branch to the Chrome Web Store. We don't have much time left.
> > > > Please test the branch and add all the changes from the main branch, like the latest to-do list pin feature.
> > > 
> > > 
> > > if todo pin and page flashing branches are not deleted yet, @Thunder-Blaze can pull PR rest are some minor translation related maybe a toggle to hide quote and we are good to go
> > 
> > 
> > which quote ?
> 
> it is there in chrome store branch random quotes in place of `Search with` search engines selector

I gotta logout for the day..
can you also add a toggle if you dont mind
default off = hide searchWithCont div
when on = show searchWithCont div
![image](https://github.com/user-attachments/assets/60c7eba3-5198-453a-96b4-38929a99d697)

2024-12-21 16:58 UTC, prem-k-r commented
@XengShi I retried the slider code from v2.5 branch.. something is wrong

https://github.com/user-attachments/assets/247dc19c-4b40-43d0-be79-0f2ddf0aac8a

2024-12-21 17:01 UTC, Thunder-Blaze commented
> > > > > @prem-k-r @itz-rj-here @Thunder-Blaze I am going to upload the chrome-store branch to the Chrome Web Store. We don't have much time left.
> > > > > Please test the branch and add all the changes from the main branch, like the latest to-do list pin feature.
> > > > 
> > > > 
> > > > if todo pin and page flashing branches are not deleted yet, @Thunder-Blaze can pull PR rest are some minor translation related maybe a toggle to hide quote and we are good to go
> > > 
> > > 
> > > which quote ?
> > 
> > 
> > it is there in chrome store branch random quotes in place of `Search with` search engines selector
> 
> I gotta logout for the day.. can you also add a toggle if you dont mind default off = hide searchWithCont div when on = show searchWithCont div ![image](https://private-user-images.githubusercontent.com/60751338/397941107-60c7eba3-5198-453a-96b4-38929a99d697.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQ4MDAyOTQsIm5iZiI6MTczNDc5OTk5NCwicGF0aCI6Ii82MDc1MTMzOC8zOTc5NDExMDctNjBjN2ViYTMtNTE5OC00NTNhLTk2YjQtMzg5MjlhOTlkNjk3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjIxVDE2NTMxNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTdjZjgyMWVjNGU4MjZkOTgxMDdjZDA2YWI4OGRkOTUxNDQ0NzhlMjA2YTNmZGQyYjM2YWI5MGU1ZGNlYjU5ODImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.6oUEG0-O8lZp2wKQZ5BK4_WpxLqAkQgu13Ti0bNa9Q0)

@prem-k-r sure

2024-12-21 17:39 UTC, Thunder-Blaze commented
wait @prem-k-r which branch are you on ?
I don't see the toggle to switch off and on Motivational Quotes ?

![image](https://github.com/user-attachments/assets/2a608df4-f973-4ed4-a648-5d29ddffeebd)

2024-12-21 17:41 UTC, prem-k-r commented
> wait @prem-k-r which branch are you on ? I don't see the toggle to switch off and on Motivational Quotes ?
> 
> ![image](https://private-user-images.githubusercontent.com/68265106/397943645-2a608df4-f973-4ed4-a648-5d29ddffeebd.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQ4MDMxNDUsIm5iZiI6MTczNDgwMjg0NSwicGF0aCI6Ii82ODI2NTEwNi8zOTc5NDM2NDUtMmE2MDhkZjQtZjk3My00ZWQ0LWE2NDgtNWQyOWRkZmZlZWJkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjIxVDE3NDA0NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWRiMTljY2YxODcxZjk1YzMzMjZlMWEzOTJmZGZlMzEwMTEzODkwMmRhMjBkMjIwZjE4MmFiYjhiYjQ0ZThhOTQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.npJ-P9VXL4Hcfn9PY3r9w8-3T8le2m2DWPP85NywgCU)

Actually the toggle is not there, we have to add it

2024-12-21 17:44 UTC, Thunder-Blaze commented
So I have to add Motivation Quote toggle ?
and what is searchwithCont then ? is it set to display none rn ?

2024-12-21 17:45 UTC, Thunder-Blaze commented
Oh so searchwithCont is Motivational Quotes

2024-12-21 17:47 UTC, XengShi commented
> Oh so searchwithCont is Motivational Quotes

Yes, we have to remove the search engine selector for chrome guide-lines

2024-12-21 17:50 UTC, prem-k-r commented
> So I have to add Motivation Quote toggle ? and what is searchwithCont then ? is it set to display none rn ?

Check the code in chrome-store branch.. you will understand. There us no search engines selector there.. it us replaced by quotes.. it is still in same div searchwithCont. 

If it's late for you.. you can leave it :)
We can go without it but users will be seeing the quotes all the time.

2024-12-21 17:50 UTC, Thunder-Blaze commented
nah dw I am adding it
@XengShi you can review and merge till then
I'll be done in 5 min

2024-12-22 06:30 UTC, prem-k-r commented
Great @Thunder-Blaze!
I had thought of doing it today

added few more, will draft pr

Clickable Nameless Bookmarks
Ctrl+Click to Open in a New Tab
Search by URL

2024-12-22 06:33 UTC, Thunder-Blaze commented
Alright, I'll start working on the bookmarks grid CSS

Btw I tried to add bookmarks in firefox too using browser.bookmarks but was unsuccessful see if anybody finds a way to make them work. Currently Edge, Brave and Chrome are working and now all the bookmark folders are getting shown

![image](https://github.com/user-attachments/assets/e2987dcc-bc9e-459d-a9c5-ca986c096b47)
also can anyone lmk which branches can I delete with no problems (Which doesn't require getting merged in branches like chrome-store, etc), its a mess here

@prem-k-r nice 👍🏻 
Les go

2024-12-22 06:35 UTC, Thunder-Blaze commented
oh btw the Nameless problem will get fixed automatically in grid layout, so focus on other 2 first

2024-12-22 07:05 UTC, itz-rj-here commented
Lol @XengShi made this pr ready for review. 
I didn’t even noticed.

2024-12-22 07:05 UTC, itz-rj-here commented
@prem-k-r @Thunder-Blaze what are you guys going to do?

2024-12-22 07:15 UTC, prem-k-r commented
there is a conflicts here.. probably some minor change.. please check

2024-12-22 07:19 UTC, itz-rj-here commented
@prem-k-r @Thunder-Blaze I have a doubt on this
![image](https://github.com/user-attachments/assets/ff116a73-7f8b-4b57-b902-044309f3fed0)

2024-12-22 07:23 UTC, itz-rj-here commented
@prem-k-r are you on?

2024-12-22 07:25 UTC, Thunder-Blaze commented
@itz-rj-here keep both changes

2024-12-22 07:25 UTC, Thunder-Blaze commented
> @prem-k-r @Thunder-Blaze what are you guys going to do?

I was working on grid view

2024-12-22 07:26 UTC, itz-rj-here commented
> > @prem-k-r @Thunder-Blaze what are you guys going to do?
> 
> I was working on grid view

Ohh. Ok you work. I will be there when you needed me.

2024-12-22 07:28 UTC, prem-k-r commented
I m trying to fix favicon issue

2024-12-22 07:28 UTC, itz-rj-here commented
> I m trying to fix favicon issue

it's fixed i guess...

2024-12-22 07:31 UTC, XengShi commented
> Lol @XengShi made this pr ready for review. 
> I didn’t even noticed.

I accidentally clicked on my phone

2024-12-22 08:00 UTC, Thunder-Blaze commented
@XengShi 
![image](https://github.com/user-attachments/assets/6a172e8d-4489-43c7-8ace-8c392185c267)
Should I keep 4 in one row ?
I think 5 are looking too messy

2024-12-22 08:03 UTC, itz-rj-here commented
> @XengShi ![image](https://private-user-images.githubusercontent.com/68265106/397971763-6a172e8d-4489-43c7-8ace-8c392185c267.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQ4NTQ4MDMsIm5iZiI6MTczNDg1NDUwMywicGF0aCI6Ii82ODI2NTEwNi8zOTc5NzE3NjMtNmExNzJlOGQtNDQ4OS00M2M3LThhY2UtOGMzOTIxODVjMjY3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjIyVDA4MDE0M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTYxYjFkNWJmZmIzMjUwNmU0YjdhZGIzOTRlN2Y5YjQ1N2RjYjI4NWNkMzQ4ZGZlMjI4NGY4MTU3M2U3NmVkMTcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.s4cX3xmnD-EWvUvzIAPjBvDYzWWDCk9Uwki_YIhO4dY) Should I keep 4 in one row ? I think 5 are looking too messy or should I increase width of bookmarks section

keep 4

2024-12-22 08:04 UTC, XengShi commented
> @XengShi 
> ![image](https://github.com/user-attachments/assets/6a172e8d-4489-43c7-8ace-8c392185c267)
> Should I keep 4 in one row ?
> I think 5 are looking too messy
> or should I increase width of bookmarks section

Sure you can keep 4 and try to keep only websites names instead of full titles (only in grid view)

2024-12-22 08:05 UTC, itz-rj-here commented
> > @XengShi
> > ![image](https://private-user-images.githubusercontent.com/68265106/397971763-6a172e8d-4489-43c7-8ace-8c392185c267.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQ4NTQ5ODQsIm5iZiI6MTczNDg1NDY4NCwicGF0aCI6Ii82ODI2NTEwNi8zOTc5NzE3NjMtNmExNzJlOGQtNDQ4OS00M2M3LThhY2UtOGMzOTIxODVjMjY3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjIyVDA4MDQ0NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTE4NjZiM2Y2NGEwYmIzNTE1YTk3YzFiMjBkNmM1OWI0ZDIwYzlhYTg3ZTI3Y2RkNTliMGViZGFlN2UxOTZmYWMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.VQnQEBfJWH6uVHTaiarb5twwl5g8tNEwQkrQfS-x5Ys)
> > Should I keep 4 in one row ?
> > I think 5 are looking too messy
> > or should I increase width of bookmarks section
> 
> Sure you can keep 4 and try to keep only websites names instead of full titles (only in grid view)

Yeah thats a good idea actually. @Thunder-Blaze

2024-12-22 08:05 UTC, prem-k-r commented
> @XengShi ![image](https://private-user-images.githubusercontent.com/68265106/397971763-6a172e8d-4489-43c7-8ace-8c392185c267.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQ4NTQ4MDMsIm5iZiI6MTczNDg1NDUwMywicGF0aCI6Ii82ODI2NTEwNi8zOTc5NzE3NjMtNmExNzJlOGQtNDQ4OS00M2M3LThhY2UtOGMzOTIxODVjMjY3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjIyVDA4MDE0M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTYxYjFkNWJmZmIzMjUwNmU0YjdhZGIzOTRlN2Y5YjQ1N2RjYjI4NWNkMzQ4ZGZlMjI4NGY4MTU3M2U3NmVkMTcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.s4cX3xmnD-EWvUvzIAPjBvDYzWWDCk9Uwki_YIhO4dY) Should I keep 4 in one row ? I think 5 are looking too messy or should I increase width of bookmarks section

maybe we can show only icons for grid view.. so inc icon size too

also pls review
https://github.com/XengShi/materialYouNewTab/pull/349/commits/e739233ef488a33e9e8a05777cd37492b2e0c41c

2024-12-22 08:10 UTC, itz-rj-here commented
> > @XengShi ![image](https://private-user-images.githubusercontent.com/68265106/397971763-6a172e8d-4489-43c7-8ace-8c392185c267.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQ4NTQ4MDMsIm5iZiI6MTczNDg1NDUwMywicGF0aCI6Ii82ODI2NTEwNi8zOTc5NzE3NjMtNmExNzJlOGQtNDQ4OS00M2M3LThhY2UtOGMzOTIxODVjMjY3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjIyVDA4MDE0M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTYxYjFkNWJmZmIzMjUwNmU0YjdhZGIzOTRlN2Y5YjQ1N2RjYjI4NWNkMzQ4ZGZlMjI4NGY4MTU3M2U3NmVkMTcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.s4cX3xmnD-EWvUvzIAPjBvDYzWWDCk9Uwki_YIhO4dY) Should I keep 4 in one row ? I think 5 are looking too messy or should I increase width of bookmarks section
> 
> maybe we can show only icons for grid view.. so inc icon size too
> 
> also pls review [e739233](https://github.com/XengShi/materialYouNewTab/commit/e739233ef488a33e9e8a05777cd37492b2e0c41c)

It works for me actually. No such issue...

2024-12-22 08:10 UTC, itz-rj-here commented
Having problem with firefox. Does even firefox support bookmark management???

2024-12-22 08:17 UTC, prem-k-r commented
> Having problem with firefox. Does even firefox support bookmark management???

chromium use chrome.bookmarks api
firefox browser.bookmarks api
safari's is inaccessible

2024-12-22 08:17 UTC, itz-rj-here commented
> > Having problem with firefox. Does even firefox support bookmark management???
> 
> chromium use chrome.bookmarks api firefox browser.bookmarks api safari's is inaccessible

firefox doesn't work. I also tried chatgpt's help. Still doesn't work. :(
idk where is the issue...

2024-12-22 08:23 UTC, Thunder-Blaze commented
yeah I also tried yesterday, wasn't working for me

btw should I extract Website name from the title and then show it ?

rn it looks like this 
![image](https://github.com/user-attachments/assets/b2821715-c0a3-45fc-9f2b-c02badd6abb8)
I still need to center the text somehow

and can't increase the icon size, they break (become pixelated) as the fetched icons are 16x16px

2024-12-22 08:39 UTC, prem-k-r commented
changed some things.. working for firefox

2024-12-22 08:39 UTC, Thunder-Blaze commented
![image](https://github.com/user-attachments/assets/fe831add-c5e1-4fb3-bff5-7659a550580d)
how this ?

2024-12-22 08:40 UTC, Thunder-Blaze commented
> changed some things.. working for firefox

nicee

2024-12-22 08:46 UTC, prem-k-r commented
> changed some things.. working for firefox

but not everything :(

2024-12-22 08:53 UTC, Thunder-Blaze commented
![image](https://github.com/user-attachments/assets/6d25fc4a-eb9d-4407-b14c-dbf9bdbc16ca)
current progress

todo
- Add a icon in searchbar

other than that any more suggestions ?

2024-12-22 08:59 UTC, prem-k-r commented
looks nice.. can you change width to 380px, please check this https://github.com/XengShi/materialYouNewTab/pull/349/commits/e739233ef488a33e9e8a05777cd37492b2e0c41c.. have changed few styles

2024-12-22 09:10 UTC, Thunder-Blaze commented
oh ig I should pull first else conflicts will rise ☠️

2024-12-22 09:23 UTC, Thunder-Blaze commented
![image](https://github.com/user-attachments/assets/bceffb32-f1a8-4587-ba5c-c7c72cfecd63)
@prem-k-r after merging your changes

2024-12-22 09:25 UTC, Thunder-Blaze commented
Should I inrease the size of circles behind icons ?
btw I toggle is not yet functional, I will fix it tonight

2024-12-22 09:26 UTC, prem-k-r commented
Maybe increase width to 400px and keep 5 in a row.. if only it looks good

2024-12-22 09:31 UTC, Thunder-Blaze commented
Sure, I'll try putting 5 in a row

And regarding the icon size, can we get favicons of 32px
I mean ik generally it is always 16px but somehow if we can get ?

2024-12-22 09:39 UTC, prem-k-r commented
Now bookmark start loading after html and page load, Is it possible to start loading only when bookmark list is open and close when bookmark. 
It might also solve favicon errors overflowing

2024-12-22 10:00 UTC, Thunder-Blaze commented
Yeah I might be able to do that but I'll be able to do them tonight as rn got assignments to complete

2024-12-22 10:07 UTC, prem-k-r commented
no hurry.. take your time..
if this done then 32px favicon shouldn't cause any performance issue

2024-12-22 10:53 UTC, itz-rj-here commented
![image](https://github.com/user-attachments/assets/e3ef3aaf-aa64-45ea-80e7-97d0cbeeb468)
Fixed this issue.

2024-12-22 11:24 UTC, itz-rj-here commented
@prem-k-r @Thunder-Blaze I don't see other bookmarks in brave...
![image](https://github.com/user-attachments/assets/590d49c3-7013-4807-ad83-9a6c75a3fb4f)

2024-12-22 11:25 UTC, Thunder-Blaze commented
huh 
![image](https://github.com/user-attachments/assets/27f73f40-d7a0-4db5-862b-c3f7e460803c)

I can see

2024-12-22 11:28 UTC, Thunder-Blaze reviewed
And wait didn't we fix this thing a few days ago ?

2024-12-22 11:28 UTC, itz-rj-here commented
> huh ![image](https://private-user-images.githubusercontent.com/68265106/397981753-27f73f40-d7a0-4db5-862b-c3f7e460803c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQ4NjcwNTUsIm5iZiI6MTczNDg2Njc1NSwicGF0aCI6Ii82ODI2NTEwNi8zOTc5ODE3NTMtMjdmNzNmNDAtZDdhMC00ZGI1LTg2MmItYzNmN2U0NjA4MDNjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjIyVDExMjU1NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWFkZGQ2YjIxN2VmOWNmYmViNzI0YTliMjk4YjYwM2IxMjE3ODcyYTdhYTc1YWJlMmE0M2I4NDk2ODRhYTZjMDMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.cOt7p-lAu48Av_UNgTPuFPH82a8Ngvpt684repu-5H0)
> 
> I can see

Lol. Silly me. I used my old pr code on brave.

2024-12-22 11:29 UTC, Thunder-Blaze commented on style.css
>  }
this thing

2024-12-22 11:29 UTC, Thunder-Blaze commented
lol

2024-12-22 11:29 UTC, itz-rj-here commented on style.css
>  }
Uhh. I found that issue a few mins ago and fixed it.

2024-12-22 11:31 UTC, itz-rj-here commented
But i found another issue. When a folder is in a folder the inner folder can't be unfolded.
![image](https://github.com/user-attachments/assets/188fc5f9-836f-432f-90fd-2379a8a3e498)
Clicked on the Other bookmarks but folder doesn't unfolds.

2024-12-22 11:31 UTC, itz-rj-here commented
> But i found another issue. When a folder is in a folder the inner folder can't be unfolded. ![image](https://private-user-images.githubusercontent.com/86042583/397982059-188fc5f9-836f-432f-90fd-2379a8a3e498.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQ4NjczNjcsIm5iZiI6MTczNDg2NzA2NywicGF0aCI6Ii84NjA0MjU4My8zOTc5ODIwNTktMTg4ZmM1ZjktODM2Zi00MzJmLTkwZmQtMjM3OWE4YTNlNDk4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjIyVDExMzEwN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTI4MjMwMzY4ODYxMDc0MWE5NDM5Zjc2MTZjZjRkMjRlYjE0NmU0MGI2NTMzZGJjNThhOWU3ZjEyNGNmOWZmZTEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.Zg1DSUW8hMtQO5cH0tekjW-Lq5uxFUXgxgzwkVmV-HI) Clicked on the Other bookmarks but folder doesn't unfolds.

Same as chrome.

2024-12-22 11:34 UTC, Thunder-Blaze commented
test the new pr

2024-12-22 11:38 UTC, Thunder-Blaze commented
I'm fixing the unfolding issue, u can check other things till then

2024-12-22 11:41 UTC, prem-k-r commented
minor issue: when a bookmark is searched, close bar, open again.. search text still show up

2024-12-22 11:42 UTC, itz-rj-here commented
> minor issue: when a bookmark is searched, close bar, open again.. search text still show up

Means?

2024-12-22 11:43 UTC, Thunder-Blaze commented
Done fixing unfolding, lemme make a PR again ig

2024-12-22 11:43 UTC, itz-rj-here commented
> Done fixing unfolding, lemme make a PR again ig

:)

2024-12-22 11:43 UTC, Thunder-Blaze commented
![image](https://github.com/user-attachments/assets/bb462749-a258-4f87-a002-33efe3c62523)
this ? @prem-k-r

2024-12-22 11:43 UTC, itz-rj-here commented
You guys are too fast...

2024-12-22 11:44 UTC, itz-rj-here commented
> ![image](https://private-user-images.githubusercontent.com/68265106/397982642-bb462749-a258-4f87-a002-33efe3c62523.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQ4NjgxMzAsIm5iZiI6MTczNDg2NzgzMCwicGF0aCI6Ii82ODI2NTEwNi8zOTc5ODI2NDItYmI0NjI3NDktYTI1OC00Zjg3LWEwMDItMzNlZmUzYzYyNTIzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjIyVDExNDM1MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTY2MzUyNDk1NTkzMTI1NWZlOGIwOTFhMDA5NWFiY2MzZmEyYWJhYWQ3ZDQzYmFkYzE1MDg4MDdhMzI0NDA4OTUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.j8scpWPdBwS-miAXsOp4S21ZTqdxNSqNqH_93j2ZAsE) this ? @prem-k-r

Ohh yeah. When selecting grid and searching something keeps the folders folded.

2024-12-22 11:45 UTC, itz-rj-here commented
Uhhhhhhhhhhhhhhhhhhhhhhhhh. Silly me. I didn't even noticed it. bruh.

2024-12-22 11:45 UTC, itz-rj-here commented
Guys, I will come after 1 hour. I will do my homeworks.

2024-12-22 11:46 UTC, Thunder-Blaze commented
> You guys are too fast...

I mean college is closed so yeah free most time except when seniors take extra classes and give assignments, have to make an android app before 24 😢 

And that is occurring in List too
I am fixing that

2024-12-22 11:57 UTC, Thunder-Blaze commented
fixed both issues, you can check and merge the PR after completing your HW
wait you in school or college ?

2024-12-22 12:31 UTC, itz-rj-here commented
> fixed both issues, you can check and merge the PR after completing your HW
> wait you in school or college ?

School actually. Will be in college after maybe 6 months ig.

2024-12-22 12:32 UTC, itz-rj-here commented
> > You guys are too fast...
> 
> I mean college is closed so yeah free most time except when seniors take extra classes and give assignments, have to make an android app before 24 😢 
> 
> And that is occurring in List too
> I am fixing that

You guys are at a good place of knowledge and i'm in a place where people even don't know what is pdf or coding or developer 🥲.

2024-12-22 12:33 UTC, itz-rj-here commented
In my ict book. There are too many old texts and knowledge. Also has too many mistakes. I had to remember the mistakes to get my marks in my exams. 😭

2024-12-22 12:36 UTC, Thunder-Blaze commented
Damn, you're quite skilled at your age
I didn't knew anything when I was in school

ahh yes I had ICT too in 9th and 10th lol
in 11th and 12th there was IP ig

schools like to remain outdated ngl

2024-12-22 12:41 UTC, Thunder-Blaze commented
> > > You guys are too fast...
> > 
> > 
> > I mean college is closed so yeah free most time except when seniors take extra classes and give assignments, have to make an android app before 24 😢
> > And that is occurring in List too
> > I am fixing that
> 
> You guys are at a good place of knowledge and i'm in a place where people even don't know what is pdf or coding or developer 🥲.

Don't worry, you'll reach a good enviornment soon
When I first came to college a few months ago, many people haven't even touched PC's in their lives but now they are much better than me (who atleast knew how to play games on PC), I am trying my best to catch up tho

2024-12-22 12:44 UTC, itz-rj-here commented
> Damn, you're quite skilled at your age
> I didn't knew anything when I was in school
> 
> ahh yes I had ICT too in 9th and 10th lol
> in 11th and 12th there was IP ig
> 
> schools like to remain outdated ngl

I first used a computer approximately in 2011. Since that year i have been interested in these things... 🙃🫠
It’s my fav hobby.

2024-12-22 12:50 UTC, Thunder-Blaze commented
Wow started much earlier than me even though being younger, I started in about 2013 ig 🫡

2024-12-22 14:21 UTC, itz-rj-here commented
@XengShi Requesting for review.

2024-12-22 14:23 UTC, prem-k-r requested changes
when in search bar.. right arrow key shouldn't works to open side bookmark

2024-12-22 14:24 UTC, itz-rj-here commented
> when in search bar.. right arrow key shouldn't works to open side bookmark

Like?

2024-12-22 14:25 UTC, itz-rj-here commented
I guess we should also add translation for these things too
![image](https://github.com/user-attachments/assets/4f522f26-e498-4db1-988d-352acf0834a9)

2024-12-22 14:25 UTC, prem-k-r commented
You can open bookmark by clicking right arrow key in keyboard.. this works even when you are writting something in extension searchbar and press arrow key

2024-12-22 14:26 UTC, prem-k-r commented
> I guess we should also add translation for these things too ![image](https://private-user-images.githubusercontent.com/86042583/397991505-4f522f26-e498-4db1-988d-352acf0834a9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQ4Nzc4MDQsIm5iZiI6MTczNDg3NzUwNCwicGF0aCI6Ii84NjA0MjU4My8zOTc5OTE1MDUtNGY1MjJmMjYtZTQ5OC00ZGIxLTk4OGQtMzUyYWNmMDgzNGE5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjIyVDE0MjUwNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPThjMGYyYzU3MjY2N2UyOWEyYjQxYjBkZDUzMDZiZWUxYmMwNzRkNzJmYThkNGU4YWRmNTY0ZDg0M2FiYTJlNDYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.2fbG23hBhNTo3eFiKaE3lvUjTY26FjC1lXGCaFWnYqc)

yep translation, dark theme color.. need to work on

2024-12-22 14:27 UTC, prem-k-r commented
> You can open bookmark by clicking right arrow key in keyboard.. this works even when you are writting something in extension searchbar and press arrow key

same with left arrow key in bookmark search bar.. it closes it

2024-12-22 14:28 UTC, itz-rj-here commented
> You can open bookmark by clicking right arrow key in keyboard.. this works even when you are writting something in extension searchbar and press arrow key

You mean clicking the keyboard's right arrow key opens the bookmark sidebar?...
Ohh yeah. Wtf how did it happen 0.0

2024-12-22 14:29 UTC, itz-rj-here commented
Is it somehow related to the main searchbar arrow code?

2024-12-22 14:29 UTC, itz-rj-here commented
Lemme check.

2024-12-22 14:31 UTC, prem-k-r commented
> Is it somehow related to the main searchbar arrow code?

no

2024-12-22 14:32 UTC, Thunder-Blaze commented
yeah ig we will have to add a condition to the arrow event like it only triggers when event target is not input box ?

2024-12-22 14:34 UTC, itz-rj-here commented
> > Is it somehow related to the main searchbar arrow code?
> 
> no ![image](https://private-user-images.githubusercontent.com/60751338/397991980-9897e38e-7aaa-486f-8ed8-6a0555818cf6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQ4NzgyOTUsIm5iZiI6MTczNDg3Nzk5NSwicGF0aCI6Ii82MDc1MTMzOC8zOTc5OTE5ODAtOTg5N2UzOGUtN2FhYS00ODZmLThlZDgtNmEwNTU1ODE4Y2Y2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjIyVDE0MzMxNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTdjODQ3NjhkOTA2YjI0YjE2MTM4NWU5OGJjMGRjNGM5ZDRiMmUzY2NiMGEwMWIwZTgxMjYyMTNjNWQ1NzMzY2MmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.io6kQnnoT5HYwrSeGzmsUcaMmrhJEj1jQ_AirxEOVIU)

Thats the issue -__-
W8 Lemme fix it. Or anyone of you will do?

2024-12-22 14:35 UTC, Thunder-Blaze commented
@itz-rj-here u can check the PR, its working for me

2024-12-22 14:36 UTC, itz-rj-here commented
> @itz-rj-here u can check the PR, its working for me

@prem-k-r I just have to remove the arrow key execute thing from the bookmark right?

2024-12-22 14:38 UTC, Thunder-Blaze commented
> > @itz-rj-here u can check the PR, its working for me
> 
> @prem-k-r I just have to remove the arrow key execute thing from the bookmark right?

but That'll kill the whole right key functionality 💭

2024-12-22 14:39 UTC, itz-rj-here commented
> > > @itz-rj-here u can check the PR, its working for me
> > 
> > 
> > @prem-k-r I just have to remove the arrow key execute thing from the bookmark right?
> 
> but That'll kill the whole right key functionality 💭

Then what is the plan? :|

2024-12-22 14:40 UTC, prem-k-r commented
> > > > @itz-rj-here u can check the PR, its working for me
> > > 
> > > 
> > > @prem-k-r I just have to remove the arrow key execute thing from the bookmark right?
> > 
> > 
> > but That'll kill the whole right key functionality 💭
> 
> Then what is the plan? :|

merge pr

2024-12-22 14:44 UTC, itz-rj-here commented
@prem-k-r Is it fixed now?

2024-12-22 14:48 UTC, Thunder-Blaze commented
![image](https://github.com/user-attachments/assets/71aaa78e-22b8-477a-ab86-5253c9772e33)
how these for colors ?

2024-12-22 14:55 UTC, prem-k-r commented
> ![image](https://private-user-images.githubusercontent.com/68265106/397992900-71aaa78e-22b8-477a-ab86-5253c9772e33.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQ4NzkzNTYsIm5iZiI6MTczNDg3OTA1NiwicGF0aCI6Ii82ODI2NTEwNi8zOTc5OTI5MDAtNzFhYWE3OGUtMjJiOC00NzdhLWFiODYtNTI1M2M5NzcyZTMzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjIyVDE0NTA1NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWEyZWFlZTk3YjE4MDI3NGQ2NmM2ODVjOGYxYTg2ZmUxOTFjOTE2YzVhZDUxNGUyMzM3OTc0YThlZGZmNmFiYmYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.cmu3_L7shU1qr0aXN6gFFUkMJqOLPONTMZ2W_QLrUoQ) how these for colors ?

nice..
grid-list color.. a bit dark grey
View as, font size decrease a bit
maybe add drop-shadow filter to favicon

2024-12-22 14:59 UTC, prem-k-r commented
maybe we should remove view as? there we can place two more button like grid-list
it is for sorting.. A-Z, Oldest-Newest..
It's complicated

2024-12-22 15:01 UTC, prem-k-r commented
![image](https://github.com/user-attachments/assets/560a4fc1-ac93-4a05-83f3-3b30ce9dd960)
the sub-folder is also being alphabetically placed in between

2024-12-22 15:06 UTC, Thunder-Blaze commented
@prem-k-r buttons like this ?
![image](https://github.com/user-attachments/assets/54ad05a9-0b09-422a-b6bb-b63484ba3531)

2024-12-22 15:12 UTC, prem-k-r commented
> hmm I don't think I will be able to implement that (can try later tho) though I'll remove view as if u say ig

nw, we are good for now.. 
let's decreased text size of `view as` slightly

2024-12-22 15:13 UTC, Thunder-Blaze commented
I set it to 1 rem in my recent PR

2024-12-22 15:53 UTC, prem-k-r commented
seems everything ok, but in firefox I feel laggy when opening bookmark sidebar.

2024-12-22 16:19 UTC, prem-k-r commented
> ![image](https://private-user-images.githubusercontent.com/60751338/397993708-560a4fc1-ac93-4a05-83f3-3b30ce9dd960.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQ4ODQwMzUsIm5iZiI6MTczNDg4MzczNSwicGF0aCI6Ii82MDc1MTMzOC8zOTc5OTM3MDgtNTYwYTRmYzEtYWM5My00YTA1LTgzZjMtM2IzMGNlOWRkOTYwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjIyVDE2MDg1NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWVmODE5NzgwODMxODEyMTRjOTI4NmU0MTUwYjgzNzIwNzA4NWYwOGZiODZlZmFmYTkyMWFlMTMxYjE2NWIwNzcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.NtjjLRhY3s5gDY0kE9enUcdqgwJrZcO0-i71IIgRVgU) the sub-folder is also being alphabetically placed in between

i'm on it

2024-12-22 16:42 UTC, prem-k-r approved these changes

2024-12-22 17:26 UTC, Thunder-Blaze approved these changes

2024-12-22 17:28 UTC, prem-k-r commented
@itz-rj-here conflicts

2024-12-23 00:55 UTC, itz-rj-here commented
Fixing conflicts from phone is so hard. I will fix it all after i come home. I will come home after 1 pm

2024-12-23 07:32 UTC, merged