Added Weather Data Retaining for 15 Mins
XengShi/materialYouNewTab pull request #363
Opened 2024-12-23 12:39 UTC by Thunder-Blaze

## Description
- Added Retaining of Weather Data when fetched within 15 minutes

2024-12-23 12:39 UTC, Thunder-Blaze commented
@prem-k-r You can check
I am unable to test it as the Weather API key are non-functional rn

2024-12-23 13:49 UTC, prem-k-r commented
Ok sure

2024-12-23 14:57 UTC, prem-k-r commented on script.js
> +        if (!parsedData || (Date.now() - weatherParsedTime) > 90000) {
missed a zero

2024-12-23 15:05 UTC, prem-k-r requested changes
![image](https://github.com/user-attachments/assets/918a67f7-157f-4893-b905-2aacf0247954)
It's switching back to default, when manual entered location is used

2024-12-23 15:06 UTC, Thunder-Blaze commented on script.js
> +        if (!parsedData || (Date.now() - weatherParsedTime) > 90000) {
oh lmao this became just 90 sec instead of 15min
gimme a min

2024-12-23 15:08 UTC, Thunder-Blaze commented
> ![image](https://private-user-images.githubusercontent.com/60751338/398192723-918a67f7-157f-4893-b905-2aacf0247954.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQ5NjY2MDksIm5iZiI6MTczNDk2NjMwOSwicGF0aCI6Ii82MDc1MTMzOC8zOTgxOTI3MjMtOTE4YTY3ZjctMTU3Zi00ODkzLWI5MDUtMmFhY2YwMjQ3OTU0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjIzVDE1MDUwOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTZjNDUwOGYyMDViN2E2NTA3NGMzMTI3YjU2YWZhOWQ2N2U4ZDQ1N2I5ZWMzNGEyYmJjNThkYjdjOTU5ZGU2NzQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.kQi4-bpoIUBeW0xe2w4RUVN0_Mj1ZjXiqlbsUhUa9RQ) It's switching back to default

did you update the API ?
After updating, try clearing the "weatherParsedTime" and "weatherParsedData" items

2024-12-23 15:10 UTC, prem-k-r commented
yeah.. only happening when manual entered location is used

2024-12-23 15:12 UTC, prem-k-r commented
Its working fine with automatic ip based location

2024-12-23 15:16 UTC, Thunder-Blaze commented
is any of the API keys working or all of them are dead ?
I changed something but Idk if it's working or not, should I push without checking ?

2024-12-23 15:17 UTC, prem-k-r commented
grab them from #347

2024-12-23 15:26 UTC, Thunder-Blaze commented
nah can't find working one, am pushing, you can check ig, if it doesn't work, I'll revert the changes

2024-12-23 15:27 UTC, Thunder-Blaze commented
try checking now

2024-12-23 15:31 UTC, prem-k-r commented
not working :(

2024-12-23 15:32 UTC, prem-k-r commented
> nah can't find working one, am pushing, you can check ig, if it doesn't work, I'll revert the changes

'f59e58d7735d4739ae953115241912'

2024-12-23 15:51 UTC, Thunder-Blaze commented
hmm wait its working for me with the API key you provided

2024-12-23 16:01 UTC, prem-k-r commented
translation

2024-12-23 16:08 UTC, Thunder-Blaze commented
no something even after that
![image](https://github.com/user-attachments/assets/0959b2ec-b447-4b89-8fc7-1022d4341453)
I tried logging at the end of function, but the function was running as it is supposed to, some other function later overwrites the data

2024-12-23 16:11 UTC, prem-k-r commented
yep its changed in like 0.05 sec

2024-12-23 16:12 UTC, Thunder-Blaze commented
![image](https://github.com/user-attachments/assets/bfbaa1ce-b1ee-41a7-b7e6-5b95b52731a1)
and whichever that function is, it is not overwriting temp and icon only the location somehow

2024-12-23 16:29 UTC, Thunder-Blaze commented
No, you were right, its translations in language.js
I tried commenting it and then it remained as it should be

2024-12-23 16:33 UTC, prem-k-r commented
I dont know :(

2024-12-23 16:40 UTC, Thunder-Blaze commented
@prem-k-r try now, its working for me

2024-12-23 16:56 UTC, Thunder-Blaze commented on script.js
> +            console.log("function ran")
lol done now

2024-12-23 16:58 UTC, prem-k-r commented
15 min seems so long.. lets switch to 10 min lol
and please reduce call for ipinfo too.. time half of weatherapi.. 5 min

a seperate note, the page loading wikipedia 1x1.png please download the image and put it any existing folder, and remove the link.. html line 28

2024-12-23 17:07 UTC, Thunder-Blaze commented
hmm sure wait a min

2024-12-23 17:10 UTC, Thunder-Blaze commented
wait ipinfo runs only when there is no saved data, not like weather api which runs on every tab reload so there's no need to add anything imo

2024-12-23 17:14 UTC, Thunder-Blaze commented
Done the things you asked except for the ipinfo one as it already takes the saved data, if it is not in local storage only then it tries to fetch

2024-12-23 17:20 UTC, prem-k-r commented
um yeah if we do use same method, it will autofill in location input too
actually, if one clicks like crazy a certain number of times within an hour it temp block the ip for few hours..
limit is pretty high.. only happened twice so far while testing lol

we can skip it, nvm
Thanks, awesome work :)

2024-12-23 17:21 UTC, prem-k-r commented
@XengShi good to go, you can review and merge it

2024-12-24 12:52 UTC, XengShi commented
![image](https://github.com/user-attachments/assets/c50da913-722b-4d0d-baed-97af2cc4a752)

Not loading the info

2024-12-24 13:01 UTC, Thunder-Blaze commented
can you send me what's the console output ?

2024-12-24 13:08 UTC, itz-rj-here commented
> ![image](https://github.com/user-attachments/assets/c50da913-722b-4d0d-baed-97af2cc4a752)
> 
> Not loading the info

@XengShi its cause of the weather api reached the limit. Try using your own api.

2024-12-24 13:32 UTC, XengShi commented
> > ![image](https://github.com/user-attachments/assets/c50da913-722b-4d0d-baed-97af2cc4a752)
> > 
> > Not loading the info
> 
> @XengShi its cause of the weather api reached the limit. Try using your own api.

Ohh, is there a different Api key 
This is working fine
https://xengshi.github.io/materialYouNewTab/

2024-12-24 13:33 UTC, prem-k-r commented
wait, found an issue

2024-12-24 13:35 UTC, prem-k-r commented
when language is changed, we need to fetch weather data too

const conditionText = parsedData.current.condition.text;
else we see this  in previous language

2024-12-24 13:38 UTC, prem-k-r requested changes

2024-12-24 13:38 UTC, prem-k-r commented on script.js
> +        if (!parsedData || ((Date.now() - weatherParsedTime) > 600000) || weatherParsedLocation !== currentUserLocation) {
please add another condition

2024-12-24 13:50 UTC, prem-k-r commented
> > > ![image](https://private-user-images.githubusercontent.com/48722764/398415365-c50da913-722b-4d0d-baed-97af2cc4a752.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzUwNDg0ODIsIm5iZiI6MTczNTA0ODE4MiwicGF0aCI6Ii80ODcyMjc2NC8zOTg0MTUzNjUtYzUwZGE5MTMtNzIyYi00ZDBkLWJhZWQtOTdhZjJjYzRhNzUyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjI0VDEzNDk0MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTY1ZDJkOTc1ZDQ4Njc4MWI0MDI1OTU0ZTI1ODE3YWUxZGY5ZDI3ZTZiZDUxMGYzNWMzMzVkZTI0MTA4NDJkMDAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.uXn7Q_JpfKbcJsZ6F-KfhR7_BBB3hg8hNjR_wgjrOMs)
> > > Not loading the info
> > 
> > 
> > @XengShi its cause of the weather api reached the limit. Try using your own api.
> 
> Ohh, is there a different Api key This is working fine [xengshi.github.io/materialYouNewTab](https://xengshi.github.io/materialYouNewTab/)

https://github.com/XengShi/materialYouNewTab/pull/347

2024-12-24 13:52 UTC, Thunder-Blaze commented on script.js
> +        if (!parsedData || ((Date.now() - weatherParsedTime) > 600000) || weatherParsedLocation !== currentUserLocation) {
done, should I add a API condition too ?
though I think it would be unecessary as it won't save data to Local Storage if there's an error

2024-12-24 14:07 UTC, prem-k-r commented on script.js
> +        if (!parsedData || ((Date.now() - weatherParsedTime) > 600000) || weatherParsedLocation !== currentUserLocation) {
yep, not needed

2024-12-24 14:19 UTC, prem-k-r approved these changes

2024-12-24 14:20 UTC, itz-rj-here approved these changes

2024-12-24 15:33 UTC, prem-k-r commented
optimised @Thunder-Blaze 
```
if (!parsedData.error) {
                // Extract only the necessary fields before saving
                const filteredData = {
                    location: {
                        name: parsedData.location.name,
                    },
                    current: {
                        condition: {
                            text: parsedData.current.condition.text,
                            icon: parsedData.current.condition.icon,
                        },
                        temp_c: parsedData.current.temp_c,
                        temp_f: parsedData.current.temp_f,
                        humidity: parsedData.current.humidity,
                        feelslike_c: parsedData.current.feelslike_c,
                        feelslike_f: parsedData.current.feelslike_f,
                    },
                };

                // Save filtered weather data to localStorage
                localStorage.setItem("weatherParsedData", JSON.stringify(filteredData));
                localStorage.setItem("weatherParsedTime", Date.now()); // Save time of last fetching
                localStorage.setItem("weatherParsedLocation", currentUserLocation); // Save user location
                localStorage.setItem("weatherParsedLang", currentLanguage); // Save language preference
            }
```

2024-12-25 07:15 UTC, prem-k-r commented
@XengShi can you please test this again

2024-12-25 12:45 UTC, itz-rj-here approved these changes

2024-12-27 13:04 UTC, prem-k-r commented
we can close some of the issues :)

2024-12-27 13:17 UTC, merged