Fix blank color in firefox
XengShi/materialYouNewTab pull request #405
Opened 2024-12-29 14:12 UTC by prem-k-r

## Description
Please describe your changes and the purpose of this pull request.

## Related Issues
- Closes #404 

## Checklist
- [ ] I have read and followed the [Contributing Guidelines](../CONTRIBUTING.md).
- [ ] I have added necessary tests.
- [ ] The project builds and runs without issues.

2024-12-29 14:32 UTC, prem-k-r commented
How can I compare current main branch and current firefox branch difference?

2024-12-29 14:37 UTC, itz-rj-here commented
> How can I compare current main branch and current firefox branch difference?

Just as @Thunder-Blaze did. Just use the compare changes and open a pr. :)

2024-12-29 14:38 UTC, itz-rj-here approved these changes

2024-12-29 14:42 UTC, prem-k-r commented
> [`main...firefox`?diff=split (compare)](https://github.com/XengShi/materialYouNewTab/compare/main...firefox?diff=split)

no, this doesnt show current difference but since the time of branching

2024-12-29 14:53 UTC, Thunder-Blaze approved these changes

2024-12-30 10:51 UTC, prem-k-r commented
@XengShi merging this will fix firefox issue

2024-12-30 10:54 UTC, itz-rj-here submitted a review, later dismissed

2024-12-30 10:56 UTC, prem-k-r commented
Updated version to v3.0.1, coz without change in extension version there wont be automatic update

2024-12-31 16:20 UTC, XengShi submitted a review, later dismissed

2024-12-31 16:53 UTC, prem-k-r commented
should we remove host permission for firefox store branch?
(search suggestions wont work without proxy)

2024-12-31 17:03 UTC, itz-rj-here commented
> should we remove host permission for firefox store branch?
> (search suggestions wont work without proxy)

@XengShi

2024-12-31 17:06 UTC, itz-rj-here commented
> should we remove host permission for firefox store branch?
> (search suggestions wont work without proxy)

Remove that. The restrictions are for the chrome store not firefox as so.

2024-12-31 17:06 UTC, itz-rj-here requested changes
Remove the hosts

2025-01-01 06:33 UTC, prem-k-r commented
Ok, let's confirm from @XengShi

2025-01-05 10:35 UTC, merged

2025-01-06 07:13 UTC, prem-k-r commented
huh, none of the issue automatically got closed