Reduced height of Search Dropdown
XengShi/materialYouNewTab pull request #407
Opened 2024-12-29 18:20 UTC by Thunder-Blaze

## Description
- Fixes the issue without overlapping or underlapping of Search Suggestions

## Issues
- Closes #406 

## Preview
![image](https://github.com/user-attachments/assets/7c633483-6f53-4dda-acc7-ce879da2b4a1)

2024-12-29 18:31 UTC, Thunder-Blaze commented
yeah sure can, just tell me the value of k

2024-12-29 18:41 UTC, prem-k-r commented
maybe 867 px

2024-12-29 18:50 UTC, itz-rj-here approved these changes

2024-12-29 19:04 UTC, prem-k-r commented
my full screen is 1080px in height, but I am still seeing 4 suggestions..
maybe we need to change k's value?

2024-12-29 19:18 UTC, Thunder-Blaze commented
@prem-k-r how ?
It's working for me in responsive view

I can't check in fullscreen though as my screen is 768px
It works when I reduce the scale

maybe you have your page scaled up ?

2024-12-29 19:22 UTC, prem-k-r commented
Nope.. I will check again tomorrow.. 
maybe I missed something

2024-12-29 19:23 UTC, Thunder-Blaze commented
ok 👍🏻

2024-12-30 07:26 UTC, prem-k-r commented
its working as expected in responsive view

this scaling is causing unexpected result.. but this is default in most system
![image](https://github.com/user-attachments/assets/2d3f053a-0cf9-439b-aa3f-fbe4d0d7cb0b)

2024-12-30 07:42 UTC, prem-k-r requested changes

2024-12-30 07:42 UTC, prem-k-r commented on style.css
> +@media screen and (max-height: 867px) {
please change it to 700px

2024-12-30 07:44 UTC, prem-k-r commented on style.css
> +@media screen and (max-height: 867px) {
ah, I can also edit now

2024-12-30 07:45 UTC, itz-rj-here commented
:)
Bro used the collab power

2024-12-30 07:45 UTC, prem-k-r approved these changes
Thanks, great work as always

2024-12-30 07:51 UTC, prem-k-r commented on style.css
> +@media screen and (max-height: 867px) {
hope you dont mind lol

2024-12-30 07:59 UTC, Thunder-Blaze commented on style.css
> +@media screen and (max-height: 867px) {
Oh 125% must be reducing your browsers height to less than 1080px in fullscreen 

Lmao I don't mind, thanks 😊

2024-12-30 08:07 UTC, itz-rj-here commented
@XengShi you can merge this now.

2024-12-30 09:03 UTC, itz-rj-here approved these changes

2025-01-05 10:36 UTC, merged