Added Hungarian language
XengShi/materialYouNewTab pull request #420
Opened 2024-12-31 23:13 UTC by Zan1456

## Description
Added Hungarian language support and localization

## Previews
![kép](https://github.com/user-attachments/assets/fc225fd4-bb23-4450-a602-cc916d30d98a)
![kép](https://github.com/user-attachments/assets/17bfd458-f19b-4543-b0bf-93efa12f0cd6)

## Checklist
- [x] I have read and followed the [Contributing Guidelines](../CONTRIBUTING.md).
- [x] I have added necessary tests.
- [x] The project builds and runs without issues.

2025-01-01 06:51 UTC, prem-k-r requested changes
Thank you for your contribution, please check the suggested change

2025-01-01 06:51 UTC, prem-k-r commented on README.md
> +## 🌐 Currently Supported Languages (20)
please change in line 27 too, 
change 19 to 20

2025-01-01 06:51 UTC, prem-k-r commented on languages.js
> +    en: '400px',
hu: '470px',

2025-01-01 06:51 UTC, prem-k-r commented on script.js
> +        hu: `${dayName} ${dayOfMonth}`, // Kedd 11
pls add `hu` in line 989 too.
![image](https://github.com/user-attachments/assets/cb3f6843-9d89-4daa-acf6-0012dee13cc8)
![image](https://github.com/user-attachments/assets/a9a5e3de-7062-4bdd-8c57-3d0939e08533)

2025-01-01 06:51 UTC, prem-k-r commented on script.js
> +            hu: `${monthName.substring(0, 3)} ${dayOfMonth}, ${dayName}`,	// Dec 22, Kedd
line 40, please add `hu: '48%',`
![image](https://github.com/user-attachments/assets/3c18092d-b973-47b8-82fb-275ac94aa473)
![image](https://github.com/user-attachments/assets/e07b9606-e207-4834-ae40-15362e3db1fb)

2025-01-01 06:52 UTC, prem-k-r commented
Also add `hu` here, line 320 and 346
https://github.com/XengShi/materialYouNewTab/blob/main/tools/languagesAnalysis.html

2025-01-01 07:03 UTC, prem-k-r commented on script.js
> +        hu: `${dayName} ${dayOfMonth}`, // Kedd 11
(digital clock: 12 hr format)

2025-01-01 07:06 UTC, prem-k-r commented
> Also add `hu` here, line 320 and 346 [`main`/tools/languagesAnalysis.html](https://github.com/XengShi/materialYouNewTab/blob/main/tools/languagesAnalysis.html?rgh-link-date=2025-01-01T06%3A52%3A57Z)

this is for tracking https://xengshi.github.io/materialYouNewTab/tools/languagesAnalysis.html

2025-01-01 08:57 UTC, Zan1456 reviewed
I made the requested changes

2025-01-01 08:59 UTC, prem-k-r commented
Menu width 400 to 445px pls.. it's cluttered right now

2025-01-01 08:59 UTC, prem-k-r commented
> Also add `hu` here, line 320 and 346 https://github.com/XengShi/materialYouNewTab/blob/main/tools/languagesAnalysis.html

And this one :)

2025-01-01 09:00 UTC, prem-k-r commented on languages.js
> +    en: '400px',
@Zan1456

2025-01-01 10:17 UTC, Zan1456 commented
Done

2025-01-01 10:22 UTC, prem-k-r commented
>> ![kép](https://private-user-images.githubusercontent.com/62830223/399530910-17bfd458-f19b-4543-b0bf-93efa12f0cd6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzU3MjcxMjAsIm5iZiI6MTczNTcyNjgyMCwicGF0aCI6Ii82MjgzMDIyMy8zOTk1MzA5MTAtMTdiZmQ0NTgtZjE5Yi00NTQzLWIwYmYtOTNlZmExMmYwY2Q2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNTAxMDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjUwMTAxVDEwMjAyMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTAwNTU3NWFmMmNhZTdjYmM3Yjg0MzkxZDk0OWNlMzU1MWViMzdkYWJkMzBlNWJhNzM5NGE4NDNiMWI4OTY5YzEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.qbG_ylK3oNjdCVekmmqsEgk2jNjpjb1MbnaBNkhfKJY)

> Menu width 400 to 445px pls.. it's cluttered right now

Great! Please increase menu width too

2025-01-01 10:32 UTC, Zan1456 commented
Done

2025-01-01 10:35 UTC, prem-k-r submitted a review, later dismissed

2025-01-01 11:41 UTC, itz-rj-here approved these changes

2025-01-05 10:40 UTC, prem-k-r commented
fIXED CONFLICTS

2025-01-05 10:44 UTC, itz-rj-here submitted a review, later dismissed

2025-01-05 10:45 UTC, prem-k-r commented
wait dont merge yet

2025-01-05 10:45 UTC, XengShi commented
> wait dont merge yet

Okay!!

2025-01-05 10:49 UTC, itz-rj-here commented
> lol again, pls wait

Bruh...

2025-01-05 10:50 UTC, prem-k-r submitted a review, later dismissed

2025-01-05 10:51 UTC, prem-k-r commented
@XengShi  good to go

2025-01-05 10:52 UTC, itz-rj-here approved these changes

2025-01-05 11:23 UTC, prem-k-r commented
fixed conflicts :(

2025-01-05 11:23 UTC, prem-k-r approved these changes

2025-01-05 11:32 UTC, merged