Search suggestions with proxy to bypass cors
XengShi/materialYouNewTab pull request #65
Opened 2024-10-16 10:47 UTC by Minuga-RC

Added a proxy to bypass CORS errors (user can host there own proxy)
Added a option to disable/enable Search suggestions and Proxy

2024-10-16 12:11 UTC, Minuga-RC commented
> @XengShi I don't use brave can you check this pull.

it should work in chrome as normal without enabling proxy @itz-rj-here

2024-10-16 12:12 UTC, ZiClaud requested changes

2024-10-16 12:12 UTC, ZiClaud commented on script.js
> +            const defaultProxyURL = 'https://mynt-proxy.rhythmcorehq.com'; //Default proxy url
The default proxy URL (https://mynt-proxy.rhythmcorehq.com) raises a conflict of interest, as it's linked to your profile. This presents a potential security risk since you could access sensitive user data.

2024-10-16 12:13 UTC, Minuga-RC commented on script.js
> +            const defaultProxyURL = 'https://mynt-proxy.rhythmcorehq.com'; //Default proxy url
yea I thought about that now I'm working on cloudflare worker thing the user can host them self

2024-10-16 12:24 UTC, itz-rj-here commented
@Minuga-RC can you check your extensions menu and check if you are also having this issue?

2024-10-16 12:25 UTC, itz-rj-here commented
I guess I'm the only one who is getting this error.

2024-10-16 12:27 UTC, Minuga-RC commented
> heck if you are also having this issue

I am not getting that error 
![image](https://github.com/user-attachments/assets/0264765f-1223-409f-b642-7df1bc9f3f31)

2024-10-16 12:27 UTC, Minuga-RC commented
> I guess I'm the only one who is getting this error.

what are you exactly trying to do there why is it showing my proxy repo as the context?

2024-10-16 12:31 UTC, itz-rj-here commented
I just saw the repository. Nothing else. 
Wait its not even your fault. Its the month configuration code line. What is the connection with the proxy repo with it?

2024-10-16 12:35 UTC, itz-rj-here commented
Thats strange.

2024-10-16 12:35 UTC, Minuga-RC commented
@itz-rj-here can u check if the same error appears in the main version?

2024-10-16 12:36 UTC, itz-rj-here commented
yup. just a min.

2024-10-16 12:43 UTC, itz-rj-here commented
![image](https://github.com/user-attachments/assets/8bb98390-0a66-44a8-9bd3-a6c97adbe286)
Same. It took some time to show me the errors.

2024-10-16 12:44 UTC, Minuga-RC commented
> ![image](https://private-user-images.githubusercontent.com/86042583/377055643-8bb98390-0a66-44a8-9bd3-a6c97adbe286.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjkwODI4ODUsIm5iZiI6MTcyOTA4MjU4NSwicGF0aCI6Ii84NjA0MjU4My8zNzcwNTU2NDMtOGJiOTgzOTAtMGE2Ni00NGE4LTliZDMtYTZjOTdhZGJlMjg2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDE2VDEyNDMwNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTRhZDI4NzRjOWVkMzYzMTZkNjIyMzYxMGViNGNhOTRlZWEwYTRjMDIyMWNmZmUzNDE2NDQxZTllMDlhODRkY2ImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.1U3zbRAzFa3ubKI2kGiiGKKXOcKdtTNHqNNSmpsmeHY) Same. It took some time to show me the errors.

I did installed the main version and I got the error too 
![image](https://github.com/user-attachments/assets/6f77378d-dc8d-4e6d-8d98-3142b1fcb279)

2024-10-16 12:45 UTC, itz-rj-here commented
I'm thinking to take some help from chatgpt. Cause none of us is understanding the issue. 😂

2024-10-16 12:46 UTC, Minuga-RC commented
I don't think this is my fault

2024-10-16 12:47 UTC, Minuga-RC commented
anyway does the search suggestions works to you without a proxy? @itz-rj-here

2024-10-16 12:47 UTC, itz-rj-here commented
I can understand.
Let me real check it with gpt.

2024-10-16 12:50 UTC, Minuga-RC commented
yea you can enable Search Suggestions in settings

2024-10-16 12:51 UTC, itz-rj-here commented
![image](https://github.com/user-attachments/assets/5057dddc-c38d-425e-84b8-f7ec0c8a5a8d)
![image](https://github.com/user-attachments/assets/cca80326-4c7a-470f-90bb-d682807d248b)
![image](https://github.com/user-attachments/assets/4f4c1630-eb53-46ce-b9ff-2d59b592a8e9)
![image](https://github.com/user-attachments/assets/85769b88-8502-40f5-867a-0df129c37554)
![image](https://github.com/user-attachments/assets/cdcf4896-9045-408b-a254-746158a60097)
![image](https://github.com/user-attachments/assets/c83a836d-09ca-447a-89a8-b4114cd51cff)
![image](https://github.com/user-attachments/assets/d2797b63-4db3-405c-ab45-0a0c31ae2f20)
Now thats something I saw here. Need to check it if it is fixed after adding gpts code.

2024-10-16 12:52 UTC, Minuga-RC commented
alr

2024-10-16 12:53 UTC, itz-rj-here commented
yup. :)

2024-10-16 12:58 UTC, itz-rj-here commented
![image](https://github.com/user-attachments/assets/33675284-acef-41f1-b0f6-7e5e7394d530)
Working properly. Great work.

2024-10-16 13:00 UTC, itz-rj-here commented on script.js
> +            const defaultProxyURL = 'https://mynt-proxy.rhythmcorehq.com'; //Default proxy url
@ZiClaud is kinda right with that.

2024-10-16 13:05 UTC, itz-rj-here commented
@Minuga-RC I got the issue. 
![image](https://github.com/user-attachments/assets/0351ebf8-21d8-4563-869e-b9a7ec37513c)
You see this thing here, this is the main issue. It have access to all sites. But as the extention it should only access the home tab. Not others.

2024-10-16 13:07 UTC, itz-rj-here commented
Or I can do this.
![image](https://github.com/user-attachments/assets/9d5c389c-9ec5-4b8f-b1df-33826fd14d0e)
This way i will not see the error anymore.

2024-10-16 13:08 UTC, Minuga-RC commented
> Working properly. Great work.

Thanks :)

2024-10-16 13:09 UTC, itz-rj-here commented
You just edited too much code. I need really a great time to check all the files changes you made. But can you fix one more issue if possible.

2024-10-16 13:10 UTC, itz-rj-here commented
![image](https://github.com/user-attachments/assets/09c749fa-59b5-4f4f-9a59-4f363d4c94f1)
Are you also having this issue too? If you also having this issue, Can you check the code and fix it?..

2024-10-16 13:10 UTC, Minuga-RC commented
> You see this thing here, this is the main issue. It have access to all sites. But as the extention it should only access the home tab. Not others.

Im not really sure but I think we can edit the mainfirst.json to fix this not really sure this is my first chrome extension project Ive done

2024-10-16 13:11 UTC, itz-rj-here commented
> > You see this thing here, this is the main issue. It have access to all sites. But as the extention it should only access the home tab. Not others.
> 
> Im not really sure but I think we can edit the mainfirst.json to fix this not really sure this is my first chrome extension project Ive done

Not that one. The double click to edit one.

2024-10-16 13:11 UTC, itz-rj-here commented
> ![image](https://private-user-images.githubusercontent.com/86042583/377065573-09c749fa-59b5-4f4f-9a59-4f363d4c94f1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjkwODQ1MjMsIm5iZiI6MTcyOTA4NDIyMywicGF0aCI6Ii84NjA0MjU4My8zNzcwNjU1NzMtMDljNzQ5ZmEtNTliNS00ZjRmLTlhNTktNGYzNjNkNGM5NGYxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDE2VDEzMTAyM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQwZWNkNzNkNTEyNDhmZGY5NWFjYzc1NTRhYzA1YjE2NWUyYzAyNTdjODE3ZGJjMzkyMTg1YWUyYmNhNzEzYzImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.4BA6C31I2qGgQlToYCm5KGw-15zK3vwMmDPGXt2QZQI) Are you also having this issue too? If you also having this issue, Can you check the code and fix it?..

this.

2024-10-16 13:12 UTC, Minuga-RC commented
oh sure I think I already know what to do to fix it

2024-10-16 13:49 UTC, Minuga-RC commented
@itz-rj-here I fixed it

2024-10-16 13:57 UTC, itz-rj-here commented
Bro. You just fixed that like it was nothing for you. Thanks a lot.

2024-10-16 14:24 UTC, Minuga-RC commented on script.js
> +            const defaultProxyURL = 'https://mynt-proxy.rhythmcorehq.com'; //Default proxy url
> @ZiClaud is kinda right with that.

then should I add an option so the user knows the default proxy is https://mynt-proxy.rhythmcorehq.com and it is really recommended to host their own?

2024-10-16 15:45 UTC, Minuga-RC commented
@ZiClaud should I add an option so the user knows the default proxy is https://mynt-proxy.rhythmcorehq.com/ and it is really recommended to host their own?

2024-10-16 19:30 UTC, XengShi commented
Excellent work, @Minuga-RC! The search suggestion feature was exactly what was holding me back from using the extension’s search bar, but now it's all fixed.  I’ve heard that proxies can have some security issues. Could you please add a disclaimer that appears on the first load of the extension? Also, it would be great to have an option to use the proxy or completely opt out of it.
Thanks for your hard work!!!

2024-10-17 02:22 UTC, ZiClaud commented
> should I add an option so the user knows the default proxy is https://mynt-proxy.rhythmcorehq.com/ 

I'd like that, yeah

> it is really recommended to host their own?

Yes, that way they can make an informed decision about which proxy to use

2024-10-17 02:22 UTC, itz-rj-here commented
> @ZiClaud should I add an option so the user knows the default proxy is https://mynt-proxy.rhythmcorehq.com/ and it is really recommended to host their own?

Yup I think you should.

2024-10-17 02:24 UTC, itz-rj-here commented
> Excellent work, @Minuga-RC! The search suggestion feature was exactly what was holding me back from using the extension’s search bar, but now it's all fixed.  I’ve heard that proxies can have some security issues. Could you please add a disclaimer that appears on the first load of the extension? Also, it would be great to have an option to use the proxy or completely opt out of it.
> Thanks for your hard work!!!

Looks like @XengShi requested some changes. A new work to do 🙃 @Minuga-RC.

2024-10-17 02:28 UTC, itz-rj-here requested changes
I think you should do one more thing. Can you add the brave search engine too and keep the google search engine as the default search engine. I don't think it's very hard work for you. As you did a lot previously.

2024-10-17 05:58 UTC, Minuga-RC commented
> Excellent work, @Minuga-RC! The search suggestion feature was exactly what was holding me back from using the extension’s search bar, but now it's all fixed.  I’ve heard that proxies can have some security issues. Could you please add a disclaimer that appears on the first load of the extension? Also, it would be great to have an option to use the proxy or completely opt out of it.
> Thanks for your hard work!!!

Alr I will do that also there is a option to opt out of proxy already I will work on the the first load message now

2024-10-17 06:00 UTC, Minuga-RC commented
> I think you should do one more thing. Can you add the brave search engine too and keep the google search engine as the default search engine. I don't think it's very hard work for you. As you did a lot previously. 

I will do that too, so make Google the default instead of duck duck go and add brave search right?

2024-10-17 07:13 UTC, itz-rj-here commented
> > I think you should do one more thing. Can you add the brave search engine too and keep the google search engine as the default search engine. I don't think it's very hard work for you. As you did a lot previously.
> 
> I will do that too, so make Google the default instead of duck duck go and add brave search right?

Yup

2024-10-17 07:14 UTC, itz-rj-here commented
> > should I add an option so the user knows the default proxy is https://mynt-proxy.rhythmcorehq.com/
> 
> I'd like that, yeah
> 
> > it is really recommended to host their own?
> 
> Yes, that way they can make an informed decision about which proxy to use

I think we can open a discusstion about it on the discusstion section.

2024-10-17 07:15 UTC, Minuga-RC commented
@itz-rj-here Added brave search I will now work on the proxy message/alert

2024-10-17 07:39 UTC, itz-rj-here requested changes
#50

2024-10-17 07:41 UTC, itz-rj-here commented
#67

2024-10-17 07:55 UTC, Minuga-RC commented
> This icon. When you keep the new tab open for like 3-5 mins the icon changes to this. It also happening with your newly coded repo too. Can you look into it?

I will first I need to recreate that issue

2024-10-17 08:57 UTC, itz-rj-here commented
> > This icon. When you keep the new tab open for like 3-5 mins the icon changes to this. It also happening with your newly coded repo too. Can you look into it?
> 
> I will first I need to recreate that issue

Just informed you.

2024-10-17 08:58 UTC, Minuga-RC commented
@itz-rj-here everything should be fixed now but that missing image thing I cant really figure out why cuz its not happening to me

2024-10-17 08:58 UTC, Minuga-RC commented
all the things you guys asked is added now :)

2024-10-17 09:02 UTC, itz-rj-here commented
![image](https://github.com/user-attachments/assets/21a8977e-ee2e-44c7-9192-d37f3237b6bf)
![image](https://github.com/user-attachments/assets/90477d67-0348-4b02-9bdc-4416e1f4475e)
Great work.

2024-10-17 09:02 UTC, itz-rj-here commented
> @itz-rj-here everything should be fixed now but that missing image thing I cant really figure out why cuz its not happening to me

let me record it and show it to you.

2024-10-17 09:03 UTC, Minuga-RC commented
Great work.

there should be a reset settings buttons added too in the settings page

2024-10-17 09:04 UTC, Minuga-RC commented
> > @itz-rj-here everything should be fixed now but that missing image thing I cant really figure out why cuz its not happening to me
> 
> let me record it and show it to you.

no like I need to see it happening in my browser I tried keeping it open for 5 mins and still the image is working

2024-10-17 09:04 UTC, itz-rj-here commented
![image](https://github.com/user-attachments/assets/b2e5c815-0c7f-4a3a-bf82-595c6805b6cc)
Found it.

2024-10-17 09:22 UTC, Minuga-RC commented
interesting let me try it my self too

2024-10-17 09:23 UTC, itz-rj-here commented
![image](https://github.com/user-attachments/assets/8aa768bf-144f-48c0-89e1-9ecf9be4a99f)
wait what?

2024-10-17 09:25 UTC, Minuga-RC commented
> https://screenrec.com/share/vfj0K9PM4S

is this done in a 2 tabs?

2024-10-17 09:29 UTC, itz-rj-here commented
> > https://screenrec.com/share/vfj0K9PM4S
> 
> is this done in a 2 tabs?

yupp

2024-10-17 09:30 UTC, itz-rj-here commented
@Minuga-RC I got some more issues. 
Let me record and show it to you.

2024-10-17 09:31 UTC, Minuga-RC commented
its maybe a microsoft edge issue cuz not happening to me

2024-10-17 09:36 UTC, itz-rj-here commented
https://screenrec.com/share/IOVL2pgeEN

2024-10-17 09:38 UTC, itz-rj-here commented
Watch this full. When selecting colors theme You can select them if you click the balls little bit upper side and at the last of the video the icon still gone too.

2024-10-17 09:41 UTC, itz-rj-here commented
Ohh one more thing, Let me inform you that in the main release version, it works properly.

2024-10-17 09:43 UTC, itz-rj-here commented
Broooo why im getting too many issues, why this work not finishing 😢

2024-10-17 09:48 UTC, itz-rj-here commented
![image](https://github.com/user-attachments/assets/75396dbd-4365-4c3c-9675-240ac69de708)
![image](https://github.com/user-attachments/assets/b79acb0e-cfe5-4f51-9561-036659f4a2da)
![image](https://github.com/user-attachments/assets/44aa5fd2-7b9d-4ec9-be10-aa9334e4a2c4)
It's better to use english only. -_-

2024-10-17 09:48 UTC, Minuga-RC commented
I didnt do the translation fyi

2024-10-17 09:49 UTC, Minuga-RC commented
wish I could help but idk whats that language is

2024-10-17 09:49 UTC, itz-rj-here commented
> ![image](https://private-user-images.githubusercontent.com/86042583/377409141-75396dbd-4365-4c3c-9675-240ac69de708.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjkxNTg3ODIsIm5iZiI6MTcyOTE1ODQ4MiwicGF0aCI6Ii84NjA0MjU4My8zNzc0MDkxNDEtNzUzOTZkYmQtNDM2NS00YzNjLTk2NzUtMjQwYWM2OWRlNzA4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDE3VDA5NDgwMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWMwZmNhOWQ5OGMxYzc4NTI2ZTRhZDUwNDU1MjM5YWY2MzljYjE3YmM0YmRmOWJiZmYyOWI4MGY0ZWY3NzA0ZmMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.Q3iz4DiKlhoCmMkg5XrUPxw3DAupNnXaac3aAdpM48c) ![image](https://private-user-images.githubusercontent.com/86042583/377409303-b79acb0e-cfe5-4f51-9561-036659f4a2da.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjkxNTg3ODIsIm5iZiI6MTcyOTE1ODQ4MiwicGF0aCI6Ii84NjA0MjU4My8zNzc0MDkzMDMtYjc5YWNiMGUtY2ZlNS00ZjUxLTk1NjEtMDM2NjU5ZjRhMmRhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDE3VDA5NDgwMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTcyZGVjMTAwNzY4NDY1MzNmM2EzOTAyZjQ3MWIxMmIxNzYyZGU3NmU1OWYwNGVkZTliN2U1MjI5NjhjMTFkZTUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.YEJup3j69FafAmKmNHYxdIhA98Xuw4q3sAJnj0MHWHM) ![image](https://private-user-images.githubusercontent.com/86042583/377409940-44aa5fd2-7b9d-4ec9-be10-aa9334e4a2c4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjkxNTg3ODIsIm5iZiI6MTcyOTE1ODQ4MiwicGF0aCI6Ii84NjA0MjU4My8zNzc0MDk5NDAtNDRhYTVmZDItN2I5ZC00ZWM5LWJlMTAtYWE5MzM0ZTRhMmM0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDE3VDA5NDgwMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWJjZTRjMzgxMzQzYjllZTkyODk1ODk0NDAyMGMzNzA1NzZmODkxMDg4MTNiNTUwNzZmZDZkZGVlNGViNThiYjUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.hYM_Q8cm5rEB5mwbbKxWj1T5fUduVKjciQFgFmdDD2I) It's better to use english only. -_-

Forget it its not even your work. 



> https://screenrec.com/share/IOVL2pgeEN

do this one.

2024-10-17 09:49 UTC, Minuga-RC commented
> https://screenrec.com/share/IOVL2pgeEN

oh I can fix that

2024-10-17 09:54 UTC, itz-rj-here commented
> I didnt do the translation fyi


@MestreWalla did it if im not wrong. 
He forgot about these.

2024-10-17 09:54 UTC, itz-rj-here commented
Yup found it. #48

2024-10-17 09:56 UTC, itz-rj-here commented
You are doing the coding thingy and I'm testing your code thingy. Also eating and doing my assignment. :)

2024-10-17 09:57 UTC, Minuga-RC commented
> You are doing the coding thingy and I'm testing your code thingy. Also eating and doing my assignment. :)

I just finished eating thats why I took some time to reply lol

2024-10-17 10:05 UTC, itz-rj-here commented
> @itz-rj-here fixed the issue

Great work @Minuga-RC. You should rest now, you did a lot of work for 2-3 days. I will not disturb you now. As everything is fixed. Thanks for the contributions.

2024-10-17 10:06 UTC, itz-rj-here approved these changes
Now need to List all the changes where made here.

2024-10-17 10:25 UTC, MestreWalla commented
I made the translation system, but I didn't understand this language, if the Google buttons and others also have to be translated into some languages, I can implement the translation for them, but I'll let you insert the translation so I only understand English and Portuguese, I can't know if Google translated it correctly.

2024-10-17 10:26 UTC, itz-rj-here commented
Added search suggestions with proxy to bypass CORS errors (user can host their own proxy).
Added an option to disable/enable search suggestions and proxy; also added a disclaimer message on the first start.
A reset button was added to the menu section. 
Fixed an issue with the double tap to edit not saving. #62 
Added Brave Search engine and Made Google search engine as a default search engine. #14 
The unfoldshortcut button (arrow in AI tools) fixed. #67 
Buttons on fixed themes are not clickable. #58 
A UI problem was resolved in the search box. #66

2024-10-17 10:35 UTC, itz-rj-here commented
> I made the translation system, but I didn't understand this language, if the Google buttons and others also have to be translated into some languages, I can implement the translation for them, but I'll let you insert the translation so I only understand English and Portuguese, I can't know if Google translated it correctly.

I understand. It can be translated into other languages, actually. It's like changing the language, but the sound of the translated Google name will be the same as the English Google name. 
Some untranslated sections like the AI tools chatgpt, Gemini, etc. 
The month and the day names. Like in the extension, we only see the short form of the days name and month name. But as we use the full names of the days and months, the translated days and months names come in half words, and the other half can't be shown. 
The English numbers. It can be translated in other languages too.
The location name. At least make it to change the only word to be translated.

Thats all.

2024-10-17 10:37 UTC, itz-rj-here commented
We will talk about the translation thing in the #68.
Keep this pr clean for now.

2024-10-17 10:37 UTC, itz-rj-here commented
@XengShi Requesting for review.

2024-10-17 11:51 UTC, Minuga-RC commented
@itz-rj-here I removed a not used style

2024-10-17 12:49 UTC, itz-rj-here commented
> @itz-rj-here I removed a not used style

Hmm. This thing is not being used. Great. 3 Lines of code is being cleaned up. 😂

2024-10-17 12:51 UTC, itz-rj-here commented
Some times I think that XengShi is a baby boss. 😂

2024-10-17 13:10 UTC, Minuga-RC commented
lol

2024-10-17 16:37 UTC, ZiClaud approved these changes

2024-10-17 17:35 UTC, Minuga-RC commented
@XengShi is there is anything that I can add/change?

2024-10-17 19:02 UTC, XengShi commented
Excellent work, @Minuga-RC! Much love to you ♥. However, the issue persists, similar to the one we had with dark mode earlier. The proxy warning appears with every reload. Kindly fix that as well. The warning or disclaimer should only appear on the first load of the extension or after resetting the extension settings.

2024-10-17 19:04 UTC, merged

2024-10-17 19:09 UTC, XengShi commented
> ![image](https://private-user-images.githubusercontent.com/86042583/377409141-75396dbd-4365-4c3c-9675-240ac69de708.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjkxOTIyNzIsIm5iZiI6MTcyOTE5MTk3MiwicGF0aCI6Ii84NjA0MjU4My8zNzc0MDkxNDEtNzUzOTZkYmQtNDM2NS00YzNjLTk2NzUtMjQwYWM2OWRlNzA4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDE3VDE5MDYxMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTcyZmQ0ZGFjNGE5ZDk1ODU4MzQzNjc3OGNjZDczYzVhY2VlZTkwMzRiZWFkZmI2ODRjZWVjZjYzOWJhYzYxMWEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.5gbNFc2Wkh-5pM9N-4RgxeT7c5bW0vjUdSvPBuZPmiE) ![image](https://private-user-images.githubusercontent.com/86042583/377409303-b79acb0e-cfe5-4f51-9561-036659f4a2da.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjkxOTIyNzIsIm5iZiI6MTcyOTE5MTk3MiwicGF0aCI6Ii84NjA0MjU4My8zNzc0MDkzMDMtYjc5YWNiMGUtY2ZlNS00ZjUxLTk1NjEtMDM2NjU5ZjRhMmRhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDE3VDE5MDYxMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTAyNzZmOTFjMGVjYjczNWRmNWYyZGYzODM5NWI2MWU2Y2Y3ZDRhNDEyYjA3NjA4NTViNWExMWJiMjQ5OTIzMDcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.B5_0VTuiI25c5k9GZQxHi6Q1zZ07lDOmYLyfcLK5anw) ![image](https://private-user-images.githubusercontent.com/86042583/377409940-44aa5fd2-7b9d-4ec9-be10-aa9334e4a2c4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjkxOTIyNzIsIm5iZiI6MTcyOTE5MTk3MiwicGF0aCI6Ii84NjA0MjU4My8zNzc0MDk5NDAtNDRhYTVmZDItN2I5ZC00ZWM5LWJlMTAtYWE5MzM0ZTRhMmM0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDE3VDE5MDYxMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWFmNzYxNDdkYWNiMmNhMmYxOWI4YzdiMjlkMTU1M2I0ZThlZGYyYzQ2MDdlMTE2MDFlNDNmODYxOTU5YWM0ODkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.AfnFlSo4M76UC116nYhVmI2E_tJH6ocg1aFeU2dQX_s) It's better to use english only. -_-

The person who could reach this extension should have basic knowledge of English ☺😊, but your points are valid.

2024-10-17 19:53 UTC, XengShi commented
> > Excellent work, @Minuga-RC! Much love to you ♥. However, the issue persists, similar to the one we had with dark mode earlier. The proxy warning appears with every reload. Kindly fix that as well. The warning or disclaimer should only appear on the first load of the extension or after resetting the extension settings.
> 
> Umm it does only appear in the first load tho I made it like that 

In [Chrome on Windows] it appears everytime after reloading or opening newTab but in Firefox it is working fine, strange!

2024-10-18 01:26 UTC, itz-rj-here commented
> > > Excellent work, @Minuga-RC! Much love to you ♥. However, the issue persists, similar to the one we had with dark mode earlier. The proxy warning appears with every reload. Kindly fix that as well. The warning or disclaimer should only appear on the first load of the extension or after resetting the extension settings.
> > 
> > Umm it does only appear in the first load tho I made it like that 
> 
> In [Chrome on Windows] it appears everytime after reloading or opening newTab but in Firefox it is working fine, strange!

Wait, i didn’t see that issue. Only when i reset the settings and first load the settings it shows. But it doesn’t show on every single load.

2024-10-18 09:51 UTC, XengShi commented
> @XengShi so you need to press Ok to the alert so it records it in the local storage ![image](https://private-user-images.githubusercontent.com/103571375/377748788-7bfbd545-aa10-4dec-804c-6eeda10f249c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjkyNDUyNzQsIm5iZiI6MTcyOTI0NDk3NCwicGF0aCI6Ii8xMDM1NzEzNzUvMzc3NzQ4Nzg4LTdiZmJkNTQ1LWFhMTAtNGRlYy04MDRjLTZlZWRhMTBmMjQ5Yy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDE4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAxOFQwOTQ5MzRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04YjVmNDI4NjZhMmZkNzA3NjYwMzM3N2NjMTFiNzQ3ZWY5OGJjNjYzNDhiNWViYTZlOWExMTgyMWZkMjY1MDAxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.HBqJ8Gv70cwTLdhsrttQUTxIX1DmuVOM9ztywA6zn7o) then it will wont come up again

Yeah, it's working fine. I was just clicking outside the dialog. Thanks for responding.