weather issue fixed and usertext issue fixed
XengShi/materialYouNewTab pull request #92
Opened 2024-10-21 07:29 UTC by Minuga-RC

#81 fixed (theme issue not fixed)
#84 fixed

2024-10-21 11:26 UTC, ZiClaud commented on script.js
> +function usertextupdate(){
Could you change `usertextupdate()` to `updateUserText()` to make it more readable?
Everything else looks good

2024-10-21 21:06 UTC, Minuga-RC commented on script.js
> +function usertextupdate(){
will do tmr

2024-10-21 21:10 UTC, Minuga-RC commented on script.js
> +function usertextupdate(){
done

2024-10-21 21:10 UTC, Minuga-RC commented
@XengShi ready to merge

2024-10-21 23:36 UTC, ZiClaud approved these changes

2024-10-22 09:52 UTC, prem12321kumar requested changes
line 79:

// Try to get the savedLocation or a previously stored location from localStorage
var currentUserLocation = savedLocation || localStorage.getItem("locationQ");

if (!currentUserLocation) {
    // If neither savedLocation nor localStorage has a location, fetch the IP-based location
    const geoLocation = 'https://ipinfo.io/json/';
    const locationData = await fetch(geoLocation);
    const parsedLocation = await locationData.json();
    currentUserLocation = parsedLocation.ip; // Update to the fetched IP-based location
    localStorage.setItem("locationQ", currentUserLocation); // Store the IP-based location in localStorage
}

var currentLanguage = getLanguageStatus('selectedLanguage') || 'en';

// Weather API call using currentUserLocation, which is either user input, localStorage, or IP address
const weatherApi = `https://api.weatherapi.com/v1/current.json?key=${apiKey}&q=${currentUserLocation}&aqi=no&lang=${currentLanguage}`;

const data = await fetch(weatherApi);
const parsedData = await data.json();

2024-10-22 09:59 UTC, prem12321kumar commented
Conflict with my #91, @Minuga-RC this is my suggestion, it merges both of our ideas.

2024-10-22 10:11 UTC, Minuga-RC commented
I don't really have time to do anything atm I'm - busy here making the rewrite

2024-10-23 13:35 UTC, closed without merging